/*
 * SLASCONE API
 * Please visit our official [Documentation](https://support.slascone.com/hc/en-us/sections/360004685737-API) and/or our [GitHub repository](https://github.com/slascone/) and/or our [NuGet package](https://www.nuget.org/packages/Slascone.Client/). Always use Version 2 of this API (Version 1.3 is deprecated).
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.slascone.api;

import com.slascone.ApiClient;
import com.slascone.ApiException;
import com.slascone.ApiResponse;
import com.slascone.Configuration;
import com.slascone.Pair;

import com.slascone.model.CommonErrorResponse;
import com.slascone.model.EmailConfigurationDto;
import com.slascone.model.LicenseMailDto;
import com.slascone.model.ProblemDetails;
import java.util.UUID;
import com.slascone.model.UserEmailTemplateDto;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import org.apache.http.HttpEntity;
import org.apache.http.NameValuePair;
import org.apache.http.entity.mime.MultipartEntityBuilder;
import org.apache.http.message.BasicNameValuePair;
import org.apache.http.client.entity.UrlEncodedFormEntity;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0-SNAPSHOT")
public class NotificationApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public NotificationApi() {
    this(Configuration.getDefaultApiClient());
  }

  public NotificationApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Adds a new user email template for the specified ISV.
   * 
   * @param isvId The ISV identifier. (required)
   * @param userEmailTemplateDto The user email template to add. (required)
   * @return UserEmailTemplateDto
   * @throws ApiException if fails to make API call
   */
  public UserEmailTemplateDto addUserEmailTemplate(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nonnull UserEmailTemplateDto userEmailTemplateDto) throws ApiException {
    return addUserEmailTemplate(isvId, userEmailTemplateDto, null);
  }

  /**
   * Adds a new user email template for the specified ISV.
   * 
   * @param isvId The ISV identifier. (required)
   * @param userEmailTemplateDto The user email template to add. (required)
   * @param headers Optional headers to include in the request
   * @return UserEmailTemplateDto
   * @throws ApiException if fails to make API call
   */
  public UserEmailTemplateDto addUserEmailTemplate(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nonnull UserEmailTemplateDto userEmailTemplateDto, Map<String, String> headers) throws ApiException {
    ApiResponse<UserEmailTemplateDto> localVarResponse = addUserEmailTemplateWithHttpInfo(isvId, userEmailTemplateDto, headers);
    return localVarResponse.getData();
  }

  /**
   * Adds a new user email template for the specified ISV.
   * 
   * @param isvId The ISV identifier. (required)
   * @param userEmailTemplateDto The user email template to add. (required)
   * @return ApiResponse&lt;UserEmailTemplateDto&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<UserEmailTemplateDto> addUserEmailTemplateWithHttpInfo(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nonnull UserEmailTemplateDto userEmailTemplateDto) throws ApiException {
    return addUserEmailTemplateWithHttpInfo(isvId, userEmailTemplateDto, null);
  }

  /**
   * Adds a new user email template for the specified ISV.
   * 
   * @param isvId The ISV identifier. (required)
   * @param userEmailTemplateDto The user email template to add. (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;UserEmailTemplateDto&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<UserEmailTemplateDto> addUserEmailTemplateWithHttpInfo(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nonnull UserEmailTemplateDto userEmailTemplateDto, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = addUserEmailTemplateRequestBuilder(isvId, userEmailTemplateDto, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("addUserEmailTemplate", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<UserEmailTemplateDto>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        UserEmailTemplateDto responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<UserEmailTemplateDto>() {});
        

        return new ApiResponse<UserEmailTemplateDto>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder addUserEmailTemplateRequestBuilder(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nonnull UserEmailTemplateDto userEmailTemplateDto, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'isvId' is set
    if (isvId == null) {
      throw new ApiException(400, "Missing the required parameter 'isvId' when calling addUserEmailTemplate");
    }
    // verify the required parameter 'userEmailTemplateDto' is set
    if (userEmailTemplateDto == null) {
      throw new ApiException(400, "Missing the required parameter 'userEmailTemplateDto' when calling addUserEmailTemplate");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v2/isv/{isv_id}/notifications/useremailtemplates"
        .replace("{isv_id}", ApiClient.urlEncode(isvId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(userEmailTemplateDto);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Deletes a user email template for the specified ISV.
   * 
   * @param isvId The ISV identifier. (required)
   * @param emailTemplateId The email template identifier. (required)
   * @throws ApiException if fails to make API call
   */
  public void deleteUserEmailTemplate(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nonnull UUID emailTemplateId) throws ApiException {
    deleteUserEmailTemplate(isvId, emailTemplateId, null);
  }

  /**
   * Deletes a user email template for the specified ISV.
   * 
   * @param isvId The ISV identifier. (required)
   * @param emailTemplateId The email template identifier. (required)
   * @param headers Optional headers to include in the request
   * @throws ApiException if fails to make API call
   */
  public void deleteUserEmailTemplate(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nonnull UUID emailTemplateId, Map<String, String> headers) throws ApiException {
    deleteUserEmailTemplateWithHttpInfo(isvId, emailTemplateId, headers);
  }

  /**
   * Deletes a user email template for the specified ISV.
   * 
   * @param isvId The ISV identifier. (required)
   * @param emailTemplateId The email template identifier. (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> deleteUserEmailTemplateWithHttpInfo(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nonnull UUID emailTemplateId) throws ApiException {
    return deleteUserEmailTemplateWithHttpInfo(isvId, emailTemplateId, null);
  }

  /**
   * Deletes a user email template for the specified ISV.
   * 
   * @param isvId The ISV identifier. (required)
   * @param emailTemplateId The email template identifier. (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> deleteUserEmailTemplateWithHttpInfo(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nonnull UUID emailTemplateId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = deleteUserEmailTemplateRequestBuilder(isvId, emailTemplateId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("deleteUserEmailTemplate", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody != null) {
          localVarResponseBody.readAllBytes();
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder deleteUserEmailTemplateRequestBuilder(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nonnull UUID emailTemplateId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'isvId' is set
    if (isvId == null) {
      throw new ApiException(400, "Missing the required parameter 'isvId' when calling deleteUserEmailTemplate");
    }
    // verify the required parameter 'emailTemplateId' is set
    if (emailTemplateId == null) {
      throw new ApiException(400, "Missing the required parameter 'emailTemplateId' when calling deleteUserEmailTemplate");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v2/isv/{isv_id}/notifications/useremailtemplates/{email_template_id}"
        .replace("{isv_id}", ApiClient.urlEncode(isvId.toString()))
        .replace("{email_template_id}", ApiClient.urlEncode(emailTemplateId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Gets all user email templates for the specified ISV.
   * 
   * @param isvId The ISV identifier. (required)
   * @return List&lt;UserEmailTemplateDto&gt;
   * @throws ApiException if fails to make API call
   */
  public List<UserEmailTemplateDto> getAllUserEmailTemplates(@jakarta.annotation.Nonnull UUID isvId) throws ApiException {
    return getAllUserEmailTemplates(isvId, null);
  }

  /**
   * Gets all user email templates for the specified ISV.
   * 
   * @param isvId The ISV identifier. (required)
   * @param headers Optional headers to include in the request
   * @return List&lt;UserEmailTemplateDto&gt;
   * @throws ApiException if fails to make API call
   */
  public List<UserEmailTemplateDto> getAllUserEmailTemplates(@jakarta.annotation.Nonnull UUID isvId, Map<String, String> headers) throws ApiException {
    ApiResponse<List<UserEmailTemplateDto>> localVarResponse = getAllUserEmailTemplatesWithHttpInfo(isvId, headers);
    return localVarResponse.getData();
  }

  /**
   * Gets all user email templates for the specified ISV.
   * 
   * @param isvId The ISV identifier. (required)
   * @return ApiResponse&lt;List&lt;UserEmailTemplateDto&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<UserEmailTemplateDto>> getAllUserEmailTemplatesWithHttpInfo(@jakarta.annotation.Nonnull UUID isvId) throws ApiException {
    return getAllUserEmailTemplatesWithHttpInfo(isvId, null);
  }

  /**
   * Gets all user email templates for the specified ISV.
   * 
   * @param isvId The ISV identifier. (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;List&lt;UserEmailTemplateDto&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<UserEmailTemplateDto>> getAllUserEmailTemplatesWithHttpInfo(@jakarta.annotation.Nonnull UUID isvId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getAllUserEmailTemplatesRequestBuilder(isvId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getAllUserEmailTemplates", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<List<UserEmailTemplateDto>>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        List<UserEmailTemplateDto> responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<List<UserEmailTemplateDto>>() {});
        

        return new ApiResponse<List<UserEmailTemplateDto>>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getAllUserEmailTemplatesRequestBuilder(@jakarta.annotation.Nonnull UUID isvId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'isvId' is set
    if (isvId == null) {
      throw new ApiException(400, "Missing the required parameter 'isvId' when calling getAllUserEmailTemplates");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v2/isv/{isv_id}/notifications/useremailtemplates"
        .replace("{isv_id}", ApiClient.urlEncode(isvId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Gets the current email notification settings for the specified ISV.
   * 
   * @param isvId The ISV identifier. (required)
   * @return EmailConfigurationDto
   * @throws ApiException if fails to make API call
   */
  public EmailConfigurationDto getNotificationSettings(@jakarta.annotation.Nonnull UUID isvId) throws ApiException {
    return getNotificationSettings(isvId, null);
  }

  /**
   * Gets the current email notification settings for the specified ISV.
   * 
   * @param isvId The ISV identifier. (required)
   * @param headers Optional headers to include in the request
   * @return EmailConfigurationDto
   * @throws ApiException if fails to make API call
   */
  public EmailConfigurationDto getNotificationSettings(@jakarta.annotation.Nonnull UUID isvId, Map<String, String> headers) throws ApiException {
    ApiResponse<EmailConfigurationDto> localVarResponse = getNotificationSettingsWithHttpInfo(isvId, headers);
    return localVarResponse.getData();
  }

  /**
   * Gets the current email notification settings for the specified ISV.
   * 
   * @param isvId The ISV identifier. (required)
   * @return ApiResponse&lt;EmailConfigurationDto&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<EmailConfigurationDto> getNotificationSettingsWithHttpInfo(@jakarta.annotation.Nonnull UUID isvId) throws ApiException {
    return getNotificationSettingsWithHttpInfo(isvId, null);
  }

  /**
   * Gets the current email notification settings for the specified ISV.
   * 
   * @param isvId The ISV identifier. (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;EmailConfigurationDto&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<EmailConfigurationDto> getNotificationSettingsWithHttpInfo(@jakarta.annotation.Nonnull UUID isvId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getNotificationSettingsRequestBuilder(isvId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getNotificationSettings", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<EmailConfigurationDto>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        EmailConfigurationDto responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<EmailConfigurationDto>() {});
        

        return new ApiResponse<EmailConfigurationDto>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getNotificationSettingsRequestBuilder(@jakarta.annotation.Nonnull UUID isvId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'isvId' is set
    if (isvId == null) {
      throw new ApiException(400, "Missing the required parameter 'isvId' when calling getNotificationSettings");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v2/isv/{isv_id}/notifications/configurations"
        .replace("{isv_id}", ApiClient.urlEncode(isvId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Gets a specific user email template by its identifier.
   * 
   * @param isvId The ISV identifier. (required)
   * @param emailTemplateId The email template identifier. (required)
   * @return UserEmailTemplateDto
   * @throws ApiException if fails to make API call
   */
  public UserEmailTemplateDto getUserEmailTemplate(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nonnull UUID emailTemplateId) throws ApiException {
    return getUserEmailTemplate(isvId, emailTemplateId, null);
  }

  /**
   * Gets a specific user email template by its identifier.
   * 
   * @param isvId The ISV identifier. (required)
   * @param emailTemplateId The email template identifier. (required)
   * @param headers Optional headers to include in the request
   * @return UserEmailTemplateDto
   * @throws ApiException if fails to make API call
   */
  public UserEmailTemplateDto getUserEmailTemplate(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nonnull UUID emailTemplateId, Map<String, String> headers) throws ApiException {
    ApiResponse<UserEmailTemplateDto> localVarResponse = getUserEmailTemplateWithHttpInfo(isvId, emailTemplateId, headers);
    return localVarResponse.getData();
  }

  /**
   * Gets a specific user email template by its identifier.
   * 
   * @param isvId The ISV identifier. (required)
   * @param emailTemplateId The email template identifier. (required)
   * @return ApiResponse&lt;UserEmailTemplateDto&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<UserEmailTemplateDto> getUserEmailTemplateWithHttpInfo(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nonnull UUID emailTemplateId) throws ApiException {
    return getUserEmailTemplateWithHttpInfo(isvId, emailTemplateId, null);
  }

  /**
   * Gets a specific user email template by its identifier.
   * 
   * @param isvId The ISV identifier. (required)
   * @param emailTemplateId The email template identifier. (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;UserEmailTemplateDto&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<UserEmailTemplateDto> getUserEmailTemplateWithHttpInfo(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nonnull UUID emailTemplateId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getUserEmailTemplateRequestBuilder(isvId, emailTemplateId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getUserEmailTemplate", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<UserEmailTemplateDto>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        UserEmailTemplateDto responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<UserEmailTemplateDto>() {});
        

        return new ApiResponse<UserEmailTemplateDto>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getUserEmailTemplateRequestBuilder(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nonnull UUID emailTemplateId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'isvId' is set
    if (isvId == null) {
      throw new ApiException(400, "Missing the required parameter 'isvId' when calling getUserEmailTemplate");
    }
    // verify the required parameter 'emailTemplateId' is set
    if (emailTemplateId == null) {
      throw new ApiException(400, "Missing the required parameter 'emailTemplateId' when calling getUserEmailTemplate");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v2/isv/{isv_id}/notifications/useremailtemplates/{email_template_id}"
        .replace("{isv_id}", ApiClient.urlEncode(isvId.toString()))
        .replace("{email_template_id}", ApiClient.urlEncode(emailTemplateId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Gets user email templates by their purpose.
   * 
   * @param isvId The ISV identifier. (required)
   * @param purpose The purpose of the email templates. (required)
   * @return List&lt;UserEmailTemplateDto&gt;
   * @throws ApiException if fails to make API call
   */
  public List<UserEmailTemplateDto> getUserEmailTemplatesByPurpose(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nonnull String purpose) throws ApiException {
    return getUserEmailTemplatesByPurpose(isvId, purpose, null);
  }

  /**
   * Gets user email templates by their purpose.
   * 
   * @param isvId The ISV identifier. (required)
   * @param purpose The purpose of the email templates. (required)
   * @param headers Optional headers to include in the request
   * @return List&lt;UserEmailTemplateDto&gt;
   * @throws ApiException if fails to make API call
   */
  public List<UserEmailTemplateDto> getUserEmailTemplatesByPurpose(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nonnull String purpose, Map<String, String> headers) throws ApiException {
    ApiResponse<List<UserEmailTemplateDto>> localVarResponse = getUserEmailTemplatesByPurposeWithHttpInfo(isvId, purpose, headers);
    return localVarResponse.getData();
  }

  /**
   * Gets user email templates by their purpose.
   * 
   * @param isvId The ISV identifier. (required)
   * @param purpose The purpose of the email templates. (required)
   * @return ApiResponse&lt;List&lt;UserEmailTemplateDto&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<UserEmailTemplateDto>> getUserEmailTemplatesByPurposeWithHttpInfo(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nonnull String purpose) throws ApiException {
    return getUserEmailTemplatesByPurposeWithHttpInfo(isvId, purpose, null);
  }

  /**
   * Gets user email templates by their purpose.
   * 
   * @param isvId The ISV identifier. (required)
   * @param purpose The purpose of the email templates. (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;List&lt;UserEmailTemplateDto&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<UserEmailTemplateDto>> getUserEmailTemplatesByPurposeWithHttpInfo(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nonnull String purpose, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getUserEmailTemplatesByPurposeRequestBuilder(isvId, purpose, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getUserEmailTemplatesByPurpose", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<List<UserEmailTemplateDto>>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        List<UserEmailTemplateDto> responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<List<UserEmailTemplateDto>>() {});
        

        return new ApiResponse<List<UserEmailTemplateDto>>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getUserEmailTemplatesByPurposeRequestBuilder(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nonnull String purpose, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'isvId' is set
    if (isvId == null) {
      throw new ApiException(400, "Missing the required parameter 'isvId' when calling getUserEmailTemplatesByPurpose");
    }
    // verify the required parameter 'purpose' is set
    if (purpose == null) {
      throw new ApiException(400, "Missing the required parameter 'purpose' when calling getUserEmailTemplatesByPurpose");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v2/isv/{isv_id}/notifications/useremailtemplates/purpose/{purpose}"
        .replace("{isv_id}", ApiClient.urlEncode(isvId.toString()))
        .replace("{purpose}", ApiClient.urlEncode(purpose.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Partially updates a user email template for the specified ISV.
   * 
   * @param isvId The ISV identifier. (required)
   * @param emailTemplateId The email template identifier. (required)
   * @param userEmailTemplateDto The user email template with updated fields. (required)
   * @return UserEmailTemplateDto
   * @throws ApiException if fails to make API call
   */
  public UserEmailTemplateDto patchUserEmailTemplate(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nonnull UUID emailTemplateId, @jakarta.annotation.Nonnull UserEmailTemplateDto userEmailTemplateDto) throws ApiException {
    return patchUserEmailTemplate(isvId, emailTemplateId, userEmailTemplateDto, null);
  }

  /**
   * Partially updates a user email template for the specified ISV.
   * 
   * @param isvId The ISV identifier. (required)
   * @param emailTemplateId The email template identifier. (required)
   * @param userEmailTemplateDto The user email template with updated fields. (required)
   * @param headers Optional headers to include in the request
   * @return UserEmailTemplateDto
   * @throws ApiException if fails to make API call
   */
  public UserEmailTemplateDto patchUserEmailTemplate(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nonnull UUID emailTemplateId, @jakarta.annotation.Nonnull UserEmailTemplateDto userEmailTemplateDto, Map<String, String> headers) throws ApiException {
    ApiResponse<UserEmailTemplateDto> localVarResponse = patchUserEmailTemplateWithHttpInfo(isvId, emailTemplateId, userEmailTemplateDto, headers);
    return localVarResponse.getData();
  }

  /**
   * Partially updates a user email template for the specified ISV.
   * 
   * @param isvId The ISV identifier. (required)
   * @param emailTemplateId The email template identifier. (required)
   * @param userEmailTemplateDto The user email template with updated fields. (required)
   * @return ApiResponse&lt;UserEmailTemplateDto&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<UserEmailTemplateDto> patchUserEmailTemplateWithHttpInfo(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nonnull UUID emailTemplateId, @jakarta.annotation.Nonnull UserEmailTemplateDto userEmailTemplateDto) throws ApiException {
    return patchUserEmailTemplateWithHttpInfo(isvId, emailTemplateId, userEmailTemplateDto, null);
  }

  /**
   * Partially updates a user email template for the specified ISV.
   * 
   * @param isvId The ISV identifier. (required)
   * @param emailTemplateId The email template identifier. (required)
   * @param userEmailTemplateDto The user email template with updated fields. (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;UserEmailTemplateDto&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<UserEmailTemplateDto> patchUserEmailTemplateWithHttpInfo(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nonnull UUID emailTemplateId, @jakarta.annotation.Nonnull UserEmailTemplateDto userEmailTemplateDto, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = patchUserEmailTemplateRequestBuilder(isvId, emailTemplateId, userEmailTemplateDto, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("patchUserEmailTemplate", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<UserEmailTemplateDto>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        UserEmailTemplateDto responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<UserEmailTemplateDto>() {});
        

        return new ApiResponse<UserEmailTemplateDto>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder patchUserEmailTemplateRequestBuilder(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nonnull UUID emailTemplateId, @jakarta.annotation.Nonnull UserEmailTemplateDto userEmailTemplateDto, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'isvId' is set
    if (isvId == null) {
      throw new ApiException(400, "Missing the required parameter 'isvId' when calling patchUserEmailTemplate");
    }
    // verify the required parameter 'emailTemplateId' is set
    if (emailTemplateId == null) {
      throw new ApiException(400, "Missing the required parameter 'emailTemplateId' when calling patchUserEmailTemplate");
    }
    // verify the required parameter 'userEmailTemplateDto' is set
    if (userEmailTemplateDto == null) {
      throw new ApiException(400, "Missing the required parameter 'userEmailTemplateDto' when calling patchUserEmailTemplate");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v2/isv/{isv_id}/notifications/useremailtemplates/{email_template_id}"
        .replace("{isv_id}", ApiClient.urlEncode(isvId.toString()))
        .replace("{email_template_id}", ApiClient.urlEncode(emailTemplateId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(userEmailTemplateDto);
      localVarRequestBuilder.method("PATCH", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Sends a license-related email using the specified template and recipients.
   * 
   * @param isvId The ISV identifier. (required)
   * @param licenseMailDto The license mail details including template and recipients. (required)
   * @return String
   * @throws ApiException if fails to make API call
   */
  public String sendLicenseMail(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nonnull LicenseMailDto licenseMailDto) throws ApiException {
    return sendLicenseMail(isvId, licenseMailDto, null);
  }

  /**
   * Sends a license-related email using the specified template and recipients.
   * 
   * @param isvId The ISV identifier. (required)
   * @param licenseMailDto The license mail details including template and recipients. (required)
   * @param headers Optional headers to include in the request
   * @return String
   * @throws ApiException if fails to make API call
   */
  public String sendLicenseMail(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nonnull LicenseMailDto licenseMailDto, Map<String, String> headers) throws ApiException {
    ApiResponse<String> localVarResponse = sendLicenseMailWithHttpInfo(isvId, licenseMailDto, headers);
    return localVarResponse.getData();
  }

  /**
   * Sends a license-related email using the specified template and recipients.
   * 
   * @param isvId The ISV identifier. (required)
   * @param licenseMailDto The license mail details including template and recipients. (required)
   * @return ApiResponse&lt;String&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<String> sendLicenseMailWithHttpInfo(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nonnull LicenseMailDto licenseMailDto) throws ApiException {
    return sendLicenseMailWithHttpInfo(isvId, licenseMailDto, null);
  }

  /**
   * Sends a license-related email using the specified template and recipients.
   * 
   * @param isvId The ISV identifier. (required)
   * @param licenseMailDto The license mail details including template and recipients. (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;String&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<String> sendLicenseMailWithHttpInfo(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nonnull LicenseMailDto licenseMailDto, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = sendLicenseMailRequestBuilder(isvId, licenseMailDto, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("sendLicenseMail", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<String>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        String responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<String>() {});
        

        return new ApiResponse<String>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder sendLicenseMailRequestBuilder(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nonnull LicenseMailDto licenseMailDto, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'isvId' is set
    if (isvId == null) {
      throw new ApiException(400, "Missing the required parameter 'isvId' when calling sendLicenseMail");
    }
    // verify the required parameter 'licenseMailDto' is set
    if (licenseMailDto == null) {
      throw new ApiException(400, "Missing the required parameter 'licenseMailDto' when calling sendLicenseMail");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v2/isv/{isv_id}/notifications/emails"
        .replace("{isv_id}", ApiClient.urlEncode(isvId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(licenseMailDto);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Sends a test email to verify the email configuration for the specified ISV.
   * 
   * @param isvId The ISV identifier. (required)
   * @param toEmail The recipient email address. (optional)
   * @return String
   * @throws ApiException if fails to make API call
   */
  public String sendTestEmail(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nullable String toEmail) throws ApiException {
    return sendTestEmail(isvId, toEmail, null);
  }

  /**
   * Sends a test email to verify the email configuration for the specified ISV.
   * 
   * @param isvId The ISV identifier. (required)
   * @param toEmail The recipient email address. (optional)
   * @param headers Optional headers to include in the request
   * @return String
   * @throws ApiException if fails to make API call
   */
  public String sendTestEmail(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nullable String toEmail, Map<String, String> headers) throws ApiException {
    ApiResponse<String> localVarResponse = sendTestEmailWithHttpInfo(isvId, toEmail, headers);
    return localVarResponse.getData();
  }

  /**
   * Sends a test email to verify the email configuration for the specified ISV.
   * 
   * @param isvId The ISV identifier. (required)
   * @param toEmail The recipient email address. (optional)
   * @return ApiResponse&lt;String&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<String> sendTestEmailWithHttpInfo(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nullable String toEmail) throws ApiException {
    return sendTestEmailWithHttpInfo(isvId, toEmail, null);
  }

  /**
   * Sends a test email to verify the email configuration for the specified ISV.
   * 
   * @param isvId The ISV identifier. (required)
   * @param toEmail The recipient email address. (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;String&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<String> sendTestEmailWithHttpInfo(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nullable String toEmail, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = sendTestEmailRequestBuilder(isvId, toEmail, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("sendTestEmail", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<String>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        String responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<String>() {});
        

        return new ApiResponse<String>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder sendTestEmailRequestBuilder(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nullable String toEmail, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'isvId' is set
    if (isvId == null) {
      throw new ApiException(400, "Missing the required parameter 'isvId' when calling sendTestEmail");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v2/isv/{isv_id}/notifications/configurations/tests"
        .replace("{isv_id}", ApiClient.urlEncode(isvId.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "to_email";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("to_email", toEmail));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Updates the email notification settings for the specified ISV.
   * 
   * @param isvId The ISV identifier. (required)
   * @param emailConfigurationDto The email configuration settings. (required)
   * @return String
   * @throws ApiException if fails to make API call
   */
  public String updateNotificationSettings(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nonnull EmailConfigurationDto emailConfigurationDto) throws ApiException {
    return updateNotificationSettings(isvId, emailConfigurationDto, null);
  }

  /**
   * Updates the email notification settings for the specified ISV.
   * 
   * @param isvId The ISV identifier. (required)
   * @param emailConfigurationDto The email configuration settings. (required)
   * @param headers Optional headers to include in the request
   * @return String
   * @throws ApiException if fails to make API call
   */
  public String updateNotificationSettings(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nonnull EmailConfigurationDto emailConfigurationDto, Map<String, String> headers) throws ApiException {
    ApiResponse<String> localVarResponse = updateNotificationSettingsWithHttpInfo(isvId, emailConfigurationDto, headers);
    return localVarResponse.getData();
  }

  /**
   * Updates the email notification settings for the specified ISV.
   * 
   * @param isvId The ISV identifier. (required)
   * @param emailConfigurationDto The email configuration settings. (required)
   * @return ApiResponse&lt;String&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<String> updateNotificationSettingsWithHttpInfo(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nonnull EmailConfigurationDto emailConfigurationDto) throws ApiException {
    return updateNotificationSettingsWithHttpInfo(isvId, emailConfigurationDto, null);
  }

  /**
   * Updates the email notification settings for the specified ISV.
   * 
   * @param isvId The ISV identifier. (required)
   * @param emailConfigurationDto The email configuration settings. (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;String&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<String> updateNotificationSettingsWithHttpInfo(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nonnull EmailConfigurationDto emailConfigurationDto, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = updateNotificationSettingsRequestBuilder(isvId, emailConfigurationDto, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("updateNotificationSettings", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<String>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        String responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<String>() {});
        

        return new ApiResponse<String>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder updateNotificationSettingsRequestBuilder(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nonnull EmailConfigurationDto emailConfigurationDto, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'isvId' is set
    if (isvId == null) {
      throw new ApiException(400, "Missing the required parameter 'isvId' when calling updateNotificationSettings");
    }
    // verify the required parameter 'emailConfigurationDto' is set
    if (emailConfigurationDto == null) {
      throw new ApiException(400, "Missing the required parameter 'emailConfigurationDto' when calling updateNotificationSettings");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v2/isv/{isv_id}/notifications/configurations"
        .replace("{isv_id}", ApiClient.urlEncode(isvId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(emailConfigurationDto);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Updates an existing user email template for the specified ISV.
   * 
   * @param isvId The ISV identifier. (required)
   * @param userEmailTemplateDto The user email template to update. (required)
   * @return UserEmailTemplateDto
   * @throws ApiException if fails to make API call
   */
  public UserEmailTemplateDto updateUserEmailTemplate(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nonnull UserEmailTemplateDto userEmailTemplateDto) throws ApiException {
    return updateUserEmailTemplate(isvId, userEmailTemplateDto, null);
  }

  /**
   * Updates an existing user email template for the specified ISV.
   * 
   * @param isvId The ISV identifier. (required)
   * @param userEmailTemplateDto The user email template to update. (required)
   * @param headers Optional headers to include in the request
   * @return UserEmailTemplateDto
   * @throws ApiException if fails to make API call
   */
  public UserEmailTemplateDto updateUserEmailTemplate(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nonnull UserEmailTemplateDto userEmailTemplateDto, Map<String, String> headers) throws ApiException {
    ApiResponse<UserEmailTemplateDto> localVarResponse = updateUserEmailTemplateWithHttpInfo(isvId, userEmailTemplateDto, headers);
    return localVarResponse.getData();
  }

  /**
   * Updates an existing user email template for the specified ISV.
   * 
   * @param isvId The ISV identifier. (required)
   * @param userEmailTemplateDto The user email template to update. (required)
   * @return ApiResponse&lt;UserEmailTemplateDto&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<UserEmailTemplateDto> updateUserEmailTemplateWithHttpInfo(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nonnull UserEmailTemplateDto userEmailTemplateDto) throws ApiException {
    return updateUserEmailTemplateWithHttpInfo(isvId, userEmailTemplateDto, null);
  }

  /**
   * Updates an existing user email template for the specified ISV.
   * 
   * @param isvId The ISV identifier. (required)
   * @param userEmailTemplateDto The user email template to update. (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;UserEmailTemplateDto&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<UserEmailTemplateDto> updateUserEmailTemplateWithHttpInfo(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nonnull UserEmailTemplateDto userEmailTemplateDto, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = updateUserEmailTemplateRequestBuilder(isvId, userEmailTemplateDto, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("updateUserEmailTemplate", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<UserEmailTemplateDto>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        UserEmailTemplateDto responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<UserEmailTemplateDto>() {});
        

        return new ApiResponse<UserEmailTemplateDto>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder updateUserEmailTemplateRequestBuilder(@jakarta.annotation.Nonnull UUID isvId, @jakarta.annotation.Nonnull UserEmailTemplateDto userEmailTemplateDto, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'isvId' is set
    if (isvId == null) {
      throw new ApiException(400, "Missing the required parameter 'isvId' when calling updateUserEmailTemplate");
    }
    // verify the required parameter 'userEmailTemplateDto' is set
    if (userEmailTemplateDto == null) {
      throw new ApiException(400, "Missing the required parameter 'userEmailTemplateDto' when calling updateUserEmailTemplate");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v2/isv/{isv_id}/notifications/useremailtemplates"
        .replace("{isv_id}", ApiClient.urlEncode(isvId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(userEmailTemplateDto);
      localVarRequestBuilder.method("PUT", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
