/*
 * SLASCONE API
 * Please visit our official [Documentation](https://support.slascone.com/hc/en-us/sections/360004685737-API) and/or our [GitHub repository](https://github.com/slascone/) and/or our [NuGet package](https://www.nuget.org/packages/Slascone.Client/). Always use Version 2 of this API (Version 1.3 is deprecated).
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.slascone.api;

import com.slascone.ApiException;
import com.slascone.model.CommonErrorResponse;
import com.slascone.model.ProblemDetails;
import java.util.UUID;
import com.slascone.model.UserRoleContextDto;
import com.slascone.model.UserRolesDto;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for RolesApi
 */
@Disabled
public class RolesApiTest {

    private final RolesApi api = new RolesApi();

    
    /**
     * Get user roles and last active context for the authenticated user.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllUserRolesAndLastActiveContextTest() throws ApiException {
        UserRolesDto response = 
        api.getAllUserRolesAndLastActiveContext();
        
        // TODO: test validations
    }
    
    /**
     * Get user roles and last active context for the authenticated user.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserRolesAndLastActiveContextTest() throws ApiException {
        UUID isvId = null;
        UserRolesDto response = 
        api.getUserRolesAndLastActiveContext(isvId);
        
        // TODO: test validations
    }
    
    /**
     * Get user role for the authenticated user in the specified ISV context.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void switchUserContextTest() throws ApiException {
        UserRoleContextDto userRoleContextDto = null;
        
        api.switchUserContext(userRoleContextDto);
        
        // TODO: test validations
    }
    
}
