/*
 * SLASCONE API
 * Please visit our official [Documentation](https://support.slascone.com/hc/en-us/sections/360004685737-API) and/or our [GitHub repository](https://github.com/slascone/) and/or our [NuGet package](https://www.nuget.org/packages/Slascone.Client/). Always use Version 2 of this API (Version 1.3 is deprecated).
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.slascone.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.slascone.model.AnalyticalFieldValueDto;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.slascone.JSON;

/**
 * AnalyticalHeartbeatDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class AnalyticalHeartbeatDto {
  public static final String SERIALIZED_NAME_CLIENT_ID = "client_id";
  @SerializedName(SERIALIZED_NAME_CLIENT_ID)
  @javax.annotation.Nonnull
  private String clientId;

  public static final String SERIALIZED_NAME_USER_ID = "user_id";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  @javax.annotation.Nullable
  private String userId;

  public static final String SERIALIZED_NAME_ANALYTICAL_HEARTBEAT = "analytical_heartbeat";
  @SerializedName(SERIALIZED_NAME_ANALYTICAL_HEARTBEAT)
  @javax.annotation.Nonnull
  private List<AnalyticalFieldValueDto> analyticalHeartbeat = new ArrayList<>();

  public static final String SERIALIZED_NAME_TOKEN_KEY = "token_key";
  @SerializedName(SERIALIZED_NAME_TOKEN_KEY)
  @javax.annotation.Nullable
  private UUID tokenKey;

  public AnalyticalHeartbeatDto() {
  }

  public AnalyticalHeartbeatDto clientId(@javax.annotation.Nonnull String clientId) {
    this.clientId = clientId;
    return this;
  }

  /**
   * Get clientId
   * @return clientId
   */
  @javax.annotation.Nonnull
  public String getClientId() {
    return clientId;
  }

  public void setClientId(@javax.annotation.Nonnull String clientId) {
    this.clientId = clientId;
  }


  public AnalyticalHeartbeatDto userId(@javax.annotation.Nullable String userId) {
    this.userId = userId;
    return this;
  }

  /**
   * Get userId
   * @return userId
   */
  @javax.annotation.Nullable
  public String getUserId() {
    return userId;
  }

  public void setUserId(@javax.annotation.Nullable String userId) {
    this.userId = userId;
  }


  public AnalyticalHeartbeatDto analyticalHeartbeat(@javax.annotation.Nonnull List<AnalyticalFieldValueDto> analyticalHeartbeat) {
    this.analyticalHeartbeat = analyticalHeartbeat;
    return this;
  }

  public AnalyticalHeartbeatDto addAnalyticalHeartbeatItem(AnalyticalFieldValueDto analyticalHeartbeatItem) {
    if (this.analyticalHeartbeat == null) {
      this.analyticalHeartbeat = new ArrayList<>();
    }
    this.analyticalHeartbeat.add(analyticalHeartbeatItem);
    return this;
  }

  /**
   * Get analyticalHeartbeat
   * @return analyticalHeartbeat
   */
  @javax.annotation.Nonnull
  public List<AnalyticalFieldValueDto> getAnalyticalHeartbeat() {
    return analyticalHeartbeat;
  }

  public void setAnalyticalHeartbeat(@javax.annotation.Nonnull List<AnalyticalFieldValueDto> analyticalHeartbeat) {
    this.analyticalHeartbeat = analyticalHeartbeat;
  }


  public AnalyticalHeartbeatDto tokenKey(@javax.annotation.Nullable UUID tokenKey) {
    this.tokenKey = tokenKey;
    return this;
  }

  /**
   * Get tokenKey
   * @return tokenKey
   */
  @javax.annotation.Nullable
  public UUID getTokenKey() {
    return tokenKey;
  }

  public void setTokenKey(@javax.annotation.Nullable UUID tokenKey) {
    this.tokenKey = tokenKey;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AnalyticalHeartbeatDto analyticalHeartbeatDto = (AnalyticalHeartbeatDto) o;
    return Objects.equals(this.clientId, analyticalHeartbeatDto.clientId) &&
        Objects.equals(this.userId, analyticalHeartbeatDto.userId) &&
        Objects.equals(this.analyticalHeartbeat, analyticalHeartbeatDto.analyticalHeartbeat) &&
        Objects.equals(this.tokenKey, analyticalHeartbeatDto.tokenKey);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(clientId, userId, analyticalHeartbeat, tokenKey);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AnalyticalHeartbeatDto {\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    analyticalHeartbeat: ").append(toIndentedString(analyticalHeartbeat)).append("\n");
    sb.append("    tokenKey: ").append(toIndentedString(tokenKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("client_id", "user_id", "analytical_heartbeat", "token_key"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("client_id", "analytical_heartbeat"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AnalyticalHeartbeatDto
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AnalyticalHeartbeatDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AnalyticalHeartbeatDto is not found in the empty JSON string", AnalyticalHeartbeatDto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AnalyticalHeartbeatDto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AnalyticalHeartbeatDto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AnalyticalHeartbeatDto.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("client_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `client_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("client_id").toString()));
      }
      if ((jsonObj.get("user_id") != null && !jsonObj.get("user_id").isJsonNull()) && !jsonObj.get("user_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `user_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("user_id").toString()));
      }
      // ensure the json data is an array
      if (!jsonObj.get("analytical_heartbeat").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `analytical_heartbeat` to be an array in the JSON string but got `%s`", jsonObj.get("analytical_heartbeat").toString()));
      }

      JsonArray jsonArrayanalyticalHeartbeat = jsonObj.getAsJsonArray("analytical_heartbeat");
      // validate the required field `analytical_heartbeat` (array)
      for (int i = 0; i < jsonArrayanalyticalHeartbeat.size(); i++) {
        AnalyticalFieldValueDto.validateJsonElement(jsonArrayanalyticalHeartbeat.get(i));
      };
      if ((jsonObj.get("token_key") != null && !jsonObj.get("token_key").isJsonNull()) && !jsonObj.get("token_key").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `token_key` to be a primitive type in the JSON string but got `%s`", jsonObj.get("token_key").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AnalyticalHeartbeatDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AnalyticalHeartbeatDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AnalyticalHeartbeatDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AnalyticalHeartbeatDto.class));

       return (TypeAdapter<T>) new TypeAdapter<AnalyticalHeartbeatDto>() {
           @Override
           public void write(JsonWriter out, AnalyticalHeartbeatDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AnalyticalHeartbeatDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AnalyticalHeartbeatDto given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AnalyticalHeartbeatDto
   * @throws IOException if the JSON string is invalid with respect to AnalyticalHeartbeatDto
   */
  public static AnalyticalHeartbeatDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AnalyticalHeartbeatDto.class);
  }

  /**
   * Convert an instance of AnalyticalHeartbeatDto to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

