/*
 * SLASCONE API
 * Please visit our official [Documentation](https://support.slascone.com/hc/en-us/sections/360004685737-API) and/or our [GitHub repository](https://github.com/slascone/) and/or our [NuGet package](https://www.nuget.org/packages/Slascone.Client/). Always use Version 2 of this API (Version 1.3 is deprecated).
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.slascone.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.slascone.model.ConsumptionHeartbeatDto;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.slascone.ApiClient;
/**
 * ConsumptionHeartbeatLazyLoadDto
 */
@JsonPropertyOrder({
  ConsumptionHeartbeatLazyLoadDto.JSON_PROPERTY_CONSUMPTION_HEARTBEATS,
  ConsumptionHeartbeatLazyLoadDto.JSON_PROPERTY_MAX_COUNT,
  ConsumptionHeartbeatLazyLoadDto.JSON_PROPERTY_AGGREGATE_VALUE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0-SNAPSHOT")
public class ConsumptionHeartbeatLazyLoadDto {
  public static final String JSON_PROPERTY_CONSUMPTION_HEARTBEATS = "consumption_heartbeats";
  private JsonNullable<List<ConsumptionHeartbeatDto>> consumptionHeartbeats = JsonNullable.<List<ConsumptionHeartbeatDto>>undefined();

  public static final String JSON_PROPERTY_MAX_COUNT = "max_count";
  @jakarta.annotation.Nullable
  private Integer maxCount;

  public static final String JSON_PROPERTY_AGGREGATE_VALUE = "aggregate_value";
  private JsonNullable<BigDecimal> aggregateValue = JsonNullable.<BigDecimal>undefined();

  public ConsumptionHeartbeatLazyLoadDto() { 
  }

  public ConsumptionHeartbeatLazyLoadDto consumptionHeartbeats(@jakarta.annotation.Nullable List<ConsumptionHeartbeatDto> consumptionHeartbeats) {
    this.consumptionHeartbeats = JsonNullable.<List<ConsumptionHeartbeatDto>>of(consumptionHeartbeats);
    return this;
  }

  public ConsumptionHeartbeatLazyLoadDto addConsumptionHeartbeatsItem(ConsumptionHeartbeatDto consumptionHeartbeatsItem) {
    if (this.consumptionHeartbeats == null || !this.consumptionHeartbeats.isPresent()) {
      this.consumptionHeartbeats = JsonNullable.<List<ConsumptionHeartbeatDto>>of(new ArrayList<>());
    }
    try {
      this.consumptionHeartbeats.get().add(consumptionHeartbeatsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get consumptionHeartbeats
   * @return consumptionHeartbeats
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public List<ConsumptionHeartbeatDto> getConsumptionHeartbeats() {
        return consumptionHeartbeats.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_CONSUMPTION_HEARTBEATS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<ConsumptionHeartbeatDto>> getConsumptionHeartbeats_JsonNullable() {
    return consumptionHeartbeats;
  }
  
  @JsonProperty(JSON_PROPERTY_CONSUMPTION_HEARTBEATS)
  public void setConsumptionHeartbeats_JsonNullable(JsonNullable<List<ConsumptionHeartbeatDto>> consumptionHeartbeats) {
    this.consumptionHeartbeats = consumptionHeartbeats;
  }

  public void setConsumptionHeartbeats(@jakarta.annotation.Nullable List<ConsumptionHeartbeatDto> consumptionHeartbeats) {
    this.consumptionHeartbeats = JsonNullable.<List<ConsumptionHeartbeatDto>>of(consumptionHeartbeats);
  }


  public ConsumptionHeartbeatLazyLoadDto maxCount(@jakarta.annotation.Nullable Integer maxCount) {
    this.maxCount = maxCount;
    return this;
  }

  /**
   * Get maxCount
   * @return maxCount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MAX_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getMaxCount() {
    return maxCount;
  }


  @JsonProperty(value = JSON_PROPERTY_MAX_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxCount(@jakarta.annotation.Nullable Integer maxCount) {
    this.maxCount = maxCount;
  }


  public ConsumptionHeartbeatLazyLoadDto aggregateValue(@jakarta.annotation.Nullable BigDecimal aggregateValue) {
    this.aggregateValue = JsonNullable.<BigDecimal>of(aggregateValue);
    return this;
  }

  /**
   * Get aggregateValue
   * @return aggregateValue
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public BigDecimal getAggregateValue() {
        return aggregateValue.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_AGGREGATE_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<BigDecimal> getAggregateValue_JsonNullable() {
    return aggregateValue;
  }
  
  @JsonProperty(JSON_PROPERTY_AGGREGATE_VALUE)
  public void setAggregateValue_JsonNullable(JsonNullable<BigDecimal> aggregateValue) {
    this.aggregateValue = aggregateValue;
  }

  public void setAggregateValue(@jakarta.annotation.Nullable BigDecimal aggregateValue) {
    this.aggregateValue = JsonNullable.<BigDecimal>of(aggregateValue);
  }


  /**
   * Return true if this ConsumptionHeartbeatLazyLoadDto object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConsumptionHeartbeatLazyLoadDto consumptionHeartbeatLazyLoadDto = (ConsumptionHeartbeatLazyLoadDto) o;
    return equalsNullable(this.consumptionHeartbeats, consumptionHeartbeatLazyLoadDto.consumptionHeartbeats) &&
        Objects.equals(this.maxCount, consumptionHeartbeatLazyLoadDto.maxCount) &&
        equalsNullable(this.aggregateValue, consumptionHeartbeatLazyLoadDto.aggregateValue);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(consumptionHeartbeats), maxCount, hashCodeNullable(aggregateValue));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConsumptionHeartbeatLazyLoadDto {\n");
    sb.append("    consumptionHeartbeats: ").append(toIndentedString(consumptionHeartbeats)).append("\n");
    sb.append("    maxCount: ").append(toIndentedString(maxCount)).append("\n");
    sb.append("    aggregateValue: ").append(toIndentedString(aggregateValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `consumption_heartbeats` to the URL query string
    if (getConsumptionHeartbeats() != null) {
      for (int i = 0; i < getConsumptionHeartbeats().size(); i++) {
        if (getConsumptionHeartbeats().get(i) != null) {
          joiner.add(getConsumptionHeartbeats().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sconsumption_heartbeats%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `max_count` to the URL query string
    if (getMaxCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smax_count%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMaxCount()))));
    }

    // add `aggregate_value` to the URL query string
    if (getAggregateValue() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%saggregate_value%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAggregateValue()))));
    }

    return joiner.toString();
  }
}

