/*
 * SLASCONE API
 * Please visit our official [Documentation](https://support.slascone.com/hc/en-us/sections/360004685737-API) and/or our [GitHub repository](https://github.com/slascone/) and/or our [NuGet package](https://www.nuget.org/packages/Slascone.Client/). Always use Version 2 of this API (Version 1.3 is deprecated).
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.slascone.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.slascone.model.ConsumptionHeartbeatDto;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.slascone.JSON;

/**
 * ConsumptionHeartbeatLazyLoadDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class ConsumptionHeartbeatLazyLoadDto {
  public static final String SERIALIZED_NAME_CONSUMPTION_HEARTBEATS = "consumption_heartbeats";
  @SerializedName(SERIALIZED_NAME_CONSUMPTION_HEARTBEATS)
  @javax.annotation.Nullable
  private List<ConsumptionHeartbeatDto> consumptionHeartbeats;

  public static final String SERIALIZED_NAME_MAX_COUNT = "max_count";
  @SerializedName(SERIALIZED_NAME_MAX_COUNT)
  @javax.annotation.Nullable
  private Integer maxCount;

  public static final String SERIALIZED_NAME_AGGREGATE_VALUE = "aggregate_value";
  @SerializedName(SERIALIZED_NAME_AGGREGATE_VALUE)
  @javax.annotation.Nullable
  private BigDecimal aggregateValue;

  public ConsumptionHeartbeatLazyLoadDto() {
  }

  public ConsumptionHeartbeatLazyLoadDto consumptionHeartbeats(@javax.annotation.Nullable List<ConsumptionHeartbeatDto> consumptionHeartbeats) {
    this.consumptionHeartbeats = consumptionHeartbeats;
    return this;
  }

  public ConsumptionHeartbeatLazyLoadDto addConsumptionHeartbeatsItem(ConsumptionHeartbeatDto consumptionHeartbeatsItem) {
    if (this.consumptionHeartbeats == null) {
      this.consumptionHeartbeats = new ArrayList<>();
    }
    this.consumptionHeartbeats.add(consumptionHeartbeatsItem);
    return this;
  }

  /**
   * Get consumptionHeartbeats
   * @return consumptionHeartbeats
   */
  @javax.annotation.Nullable
  public List<ConsumptionHeartbeatDto> getConsumptionHeartbeats() {
    return consumptionHeartbeats;
  }

  public void setConsumptionHeartbeats(@javax.annotation.Nullable List<ConsumptionHeartbeatDto> consumptionHeartbeats) {
    this.consumptionHeartbeats = consumptionHeartbeats;
  }


  public ConsumptionHeartbeatLazyLoadDto maxCount(@javax.annotation.Nullable Integer maxCount) {
    this.maxCount = maxCount;
    return this;
  }

  /**
   * Get maxCount
   * @return maxCount
   */
  @javax.annotation.Nullable
  public Integer getMaxCount() {
    return maxCount;
  }

  public void setMaxCount(@javax.annotation.Nullable Integer maxCount) {
    this.maxCount = maxCount;
  }


  public ConsumptionHeartbeatLazyLoadDto aggregateValue(@javax.annotation.Nullable BigDecimal aggregateValue) {
    this.aggregateValue = aggregateValue;
    return this;
  }

  /**
   * Get aggregateValue
   * @return aggregateValue
   */
  @javax.annotation.Nullable
  public BigDecimal getAggregateValue() {
    return aggregateValue;
  }

  public void setAggregateValue(@javax.annotation.Nullable BigDecimal aggregateValue) {
    this.aggregateValue = aggregateValue;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConsumptionHeartbeatLazyLoadDto consumptionHeartbeatLazyLoadDto = (ConsumptionHeartbeatLazyLoadDto) o;
    return Objects.equals(this.consumptionHeartbeats, consumptionHeartbeatLazyLoadDto.consumptionHeartbeats) &&
        Objects.equals(this.maxCount, consumptionHeartbeatLazyLoadDto.maxCount) &&
        Objects.equals(this.aggregateValue, consumptionHeartbeatLazyLoadDto.aggregateValue);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(consumptionHeartbeats, maxCount, aggregateValue);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConsumptionHeartbeatLazyLoadDto {\n");
    sb.append("    consumptionHeartbeats: ").append(toIndentedString(consumptionHeartbeats)).append("\n");
    sb.append("    maxCount: ").append(toIndentedString(maxCount)).append("\n");
    sb.append("    aggregateValue: ").append(toIndentedString(aggregateValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("consumption_heartbeats", "max_count", "aggregate_value"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ConsumptionHeartbeatLazyLoadDto
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ConsumptionHeartbeatLazyLoadDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ConsumptionHeartbeatLazyLoadDto is not found in the empty JSON string", ConsumptionHeartbeatLazyLoadDto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ConsumptionHeartbeatLazyLoadDto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ConsumptionHeartbeatLazyLoadDto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("consumption_heartbeats") != null && !jsonObj.get("consumption_heartbeats").isJsonNull()) {
        JsonArray jsonArrayconsumptionHeartbeats = jsonObj.getAsJsonArray("consumption_heartbeats");
        if (jsonArrayconsumptionHeartbeats != null) {
          // ensure the json data is an array
          if (!jsonObj.get("consumption_heartbeats").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `consumption_heartbeats` to be an array in the JSON string but got `%s`", jsonObj.get("consumption_heartbeats").toString()));
          }

          // validate the optional field `consumption_heartbeats` (array)
          for (int i = 0; i < jsonArrayconsumptionHeartbeats.size(); i++) {
            ConsumptionHeartbeatDto.validateJsonElement(jsonArrayconsumptionHeartbeats.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ConsumptionHeartbeatLazyLoadDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ConsumptionHeartbeatLazyLoadDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ConsumptionHeartbeatLazyLoadDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ConsumptionHeartbeatLazyLoadDto.class));

       return (TypeAdapter<T>) new TypeAdapter<ConsumptionHeartbeatLazyLoadDto>() {
           @Override
           public void write(JsonWriter out, ConsumptionHeartbeatLazyLoadDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ConsumptionHeartbeatLazyLoadDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ConsumptionHeartbeatLazyLoadDto given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ConsumptionHeartbeatLazyLoadDto
   * @throws IOException if the JSON string is invalid with respect to ConsumptionHeartbeatLazyLoadDto
   */
  public static ConsumptionHeartbeatLazyLoadDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ConsumptionHeartbeatLazyLoadDto.class);
  }

  /**
   * Convert an instance of ConsumptionHeartbeatLazyLoadDto to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

