/*
 * SLASCONE API
 * Please visit our official [Documentation](https://support.slascone.com/hc/en-us/sections/360004685737-API) and/or our [GitHub repository](https://github.com/slascone/) and/or our [NuGet package](https://www.nuget.org/packages/Slascone.Client/). Always use Version 2 of this API (Version 1.3 is deprecated).
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.slascone.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.slascone.model.DeviceAnalyticalHeartbeatDto;
import com.slascone.model.DeviceHeartbeatDto;
import com.slascone.model.LicenseActivationType;
import com.slascone.model.TagAssignmentDto;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.slascone.ApiClient;
/**
 * DeviceLicenseAssignmentDto
 */
@JsonPropertyOrder({
  DeviceLicenseAssignmentDto.JSON_PROPERTY_ID,
  DeviceLicenseAssignmentDto.JSON_PROPERTY_LICENSE_ID,
  DeviceLicenseAssignmentDto.JSON_PROPERTY_PRODUCT_ID,
  DeviceLicenseAssignmentDto.JSON_PROPERTY_DEVICE_NAME,
  DeviceLicenseAssignmentDto.JSON_PROPERTY_DEVICE_DESCRIPTION,
  DeviceLicenseAssignmentDto.JSON_PROPERTY_TOKEN_KEY,
  DeviceLicenseAssignmentDto.JSON_PROPERTY_USER_EMAIL,
  DeviceLicenseAssignmentDto.JSON_PROPERTY_USER_ID,
  DeviceLicenseAssignmentDto.JSON_PROPERTY_CLIENT_ID,
  DeviceLicenseAssignmentDto.JSON_PROPERTY_ACTIVATED,
  DeviceLicenseAssignmentDto.JSON_PROPERTY_IS_SOFTWARE_VERSION_VALID,
  DeviceLicenseAssignmentDto.JSON_PROPERTY_IS_GOODWILL_LICENSE,
  DeviceLicenseAssignmentDto.JSON_PROPERTY_HAS_HEARTBEATS,
  DeviceLicenseAssignmentDto.JSON_PROPERTY_HAS_CONSUMPTION_HEARTBEATS,
  DeviceLicenseAssignmentDto.JSON_PROPERTY_ACTIVATED_DATE_UTC,
  DeviceLicenseAssignmentDto.JSON_PROPERTY_HEARTBEAT_INFO,
  DeviceLicenseAssignmentDto.JSON_PROPERTY_ENFORCE_SOFTWARE_VERSION_UPGRADE,
  DeviceLicenseAssignmentDto.JSON_PROPERTY_DEVICE_ANALYTICAL_HEARTBEATS,
  DeviceLicenseAssignmentDto.JSON_PROPERTY_SOFTWARE_VERSION,
  DeviceLicenseAssignmentDto.JSON_PROPERTY_OPERATING_SYSTEM,
  DeviceLicenseAssignmentDto.JSON_PROPERTY_TAG_ASSIGNMENTS,
  DeviceLicenseAssignmentDto.JSON_PROPERTY_LICENSE_ACTIVATION_TYPE,
  DeviceLicenseAssignmentDto.JSON_PROPERTY_SUSPENDED_UNTIL_UTC,
  DeviceLicenseAssignmentDto.JSON_PROPERTY_CREATED_DATE_UTC,
  DeviceLicenseAssignmentDto.JSON_PROPERTY_MODIFIED_DATE_UTC,
  DeviceLicenseAssignmentDto.JSON_PROPERTY_LAST_MODIFIED_BY
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0-SNAPSHOT")
public class DeviceLicenseAssignmentDto {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private UUID id;

  public static final String JSON_PROPERTY_LICENSE_ID = "license_id";
  @jakarta.annotation.Nullable
  private UUID licenseId;

  public static final String JSON_PROPERTY_PRODUCT_ID = "product_id";
  @jakarta.annotation.Nullable
  private UUID productId;

  public static final String JSON_PROPERTY_DEVICE_NAME = "device_name";
  private JsonNullable<String> deviceName = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_DEVICE_DESCRIPTION = "device_description";
  private JsonNullable<String> deviceDescription = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_TOKEN_KEY = "token_key";
  @jakarta.annotation.Nullable
  private UUID tokenKey;

  public static final String JSON_PROPERTY_USER_EMAIL = "user_email";
  private JsonNullable<String> userEmail = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_USER_ID = "user_id";
  @jakarta.annotation.Nullable
  private UUID userId;

  public static final String JSON_PROPERTY_CLIENT_ID = "client_id";
  private JsonNullable<String> clientId = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_ACTIVATED = "activated";
  @jakarta.annotation.Nullable
  private Boolean activated;

  public static final String JSON_PROPERTY_IS_SOFTWARE_VERSION_VALID = "is_software_version_valid";
  @jakarta.annotation.Nullable
  private Boolean isSoftwareVersionValid;

  public static final String JSON_PROPERTY_IS_GOODWILL_LICENSE = "is_goodwill_license";
  @jakarta.annotation.Nullable
  private Boolean isGoodwillLicense;

  public static final String JSON_PROPERTY_HAS_HEARTBEATS = "has_heartbeats";
  @jakarta.annotation.Nullable
  private Boolean hasHeartbeats;

  public static final String JSON_PROPERTY_HAS_CONSUMPTION_HEARTBEATS = "has_consumption_heartbeats";
  @jakarta.annotation.Nullable
  private Boolean hasConsumptionHeartbeats;

  public static final String JSON_PROPERTY_ACTIVATED_DATE_UTC = "activated_date_utc";
  @jakarta.annotation.Nullable
  private OffsetDateTime activatedDateUtc;

  public static final String JSON_PROPERTY_HEARTBEAT_INFO = "heartbeat_info";
  private JsonNullable<DeviceHeartbeatDto> heartbeatInfo = JsonNullable.<DeviceHeartbeatDto>undefined();

  public static final String JSON_PROPERTY_ENFORCE_SOFTWARE_VERSION_UPGRADE = "enforce_software_version_upgrade";
  @jakarta.annotation.Nullable
  private Boolean enforceSoftwareVersionUpgrade;

  public static final String JSON_PROPERTY_DEVICE_ANALYTICAL_HEARTBEATS = "device_analytical_heartbeats";
  private JsonNullable<List<DeviceAnalyticalHeartbeatDto>> deviceAnalyticalHeartbeats = JsonNullable.<List<DeviceAnalyticalHeartbeatDto>>undefined();

  public static final String JSON_PROPERTY_SOFTWARE_VERSION = "software_version";
  private JsonNullable<String> softwareVersion = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_OPERATING_SYSTEM = "operating_system";
  private JsonNullable<String> operatingSystem = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_TAG_ASSIGNMENTS = "tag_assignments";
  private JsonNullable<List<TagAssignmentDto>> tagAssignments = JsonNullable.<List<TagAssignmentDto>>undefined();

  public static final String JSON_PROPERTY_LICENSE_ACTIVATION_TYPE = "license_activation_type";
  @jakarta.annotation.Nullable
  private LicenseActivationType licenseActivationType;

  public static final String JSON_PROPERTY_SUSPENDED_UNTIL_UTC = "suspended_until_utc";
  private JsonNullable<OffsetDateTime> suspendedUntilUtc = JsonNullable.<OffsetDateTime>undefined();

  public static final String JSON_PROPERTY_CREATED_DATE_UTC = "created_date_utc";
  private JsonNullable<OffsetDateTime> createdDateUtc = JsonNullable.<OffsetDateTime>undefined();

  public static final String JSON_PROPERTY_MODIFIED_DATE_UTC = "modified_date_utc";
  private JsonNullable<OffsetDateTime> modifiedDateUtc = JsonNullable.<OffsetDateTime>undefined();

  public static final String JSON_PROPERTY_LAST_MODIFIED_BY = "last_modified_by";
  private JsonNullable<String> lastModifiedBy = JsonNullable.<String>undefined();

  public DeviceLicenseAssignmentDto() { 
  }

  public DeviceLicenseAssignmentDto id(@jakarta.annotation.Nullable UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable UUID id) {
    this.id = id;
  }


  public DeviceLicenseAssignmentDto licenseId(@jakarta.annotation.Nullable UUID licenseId) {
    this.licenseId = licenseId;
    return this;
  }

  /**
   * Get licenseId
   * @return licenseId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LICENSE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getLicenseId() {
    return licenseId;
  }


  @JsonProperty(value = JSON_PROPERTY_LICENSE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLicenseId(@jakarta.annotation.Nullable UUID licenseId) {
    this.licenseId = licenseId;
  }


  public DeviceLicenseAssignmentDto productId(@jakarta.annotation.Nullable UUID productId) {
    this.productId = productId;
    return this;
  }

  /**
   * Get productId
   * @return productId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRODUCT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getProductId() {
    return productId;
  }


  @JsonProperty(value = JSON_PROPERTY_PRODUCT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProductId(@jakarta.annotation.Nullable UUID productId) {
    this.productId = productId;
  }


  public DeviceLicenseAssignmentDto deviceName(@jakarta.annotation.Nullable String deviceName) {
    this.deviceName = JsonNullable.<String>of(deviceName);
    return this;
  }

  /**
   * Get deviceName
   * @return deviceName
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getDeviceName() {
        return deviceName.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_DEVICE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getDeviceName_JsonNullable() {
    return deviceName;
  }
  
  @JsonProperty(JSON_PROPERTY_DEVICE_NAME)
  public void setDeviceName_JsonNullable(JsonNullable<String> deviceName) {
    this.deviceName = deviceName;
  }

  public void setDeviceName(@jakarta.annotation.Nullable String deviceName) {
    this.deviceName = JsonNullable.<String>of(deviceName);
  }


  public DeviceLicenseAssignmentDto deviceDescription(@jakarta.annotation.Nullable String deviceDescription) {
    this.deviceDescription = JsonNullable.<String>of(deviceDescription);
    return this;
  }

  /**
   * Get deviceDescription
   * @return deviceDescription
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getDeviceDescription() {
        return deviceDescription.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_DEVICE_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getDeviceDescription_JsonNullable() {
    return deviceDescription;
  }
  
  @JsonProperty(JSON_PROPERTY_DEVICE_DESCRIPTION)
  public void setDeviceDescription_JsonNullable(JsonNullable<String> deviceDescription) {
    this.deviceDescription = deviceDescription;
  }

  public void setDeviceDescription(@jakarta.annotation.Nullable String deviceDescription) {
    this.deviceDescription = JsonNullable.<String>of(deviceDescription);
  }


  public DeviceLicenseAssignmentDto tokenKey(@jakarta.annotation.Nullable UUID tokenKey) {
    this.tokenKey = tokenKey;
    return this;
  }

  /**
   * Get tokenKey
   * @return tokenKey
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOKEN_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getTokenKey() {
    return tokenKey;
  }


  @JsonProperty(value = JSON_PROPERTY_TOKEN_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTokenKey(@jakarta.annotation.Nullable UUID tokenKey) {
    this.tokenKey = tokenKey;
  }


  public DeviceLicenseAssignmentDto userEmail(@jakarta.annotation.Nullable String userEmail) {
    this.userEmail = JsonNullable.<String>of(userEmail);
    return this;
  }

  /**
   * Get userEmail
   * @return userEmail
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getUserEmail() {
        return userEmail.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_USER_EMAIL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getUserEmail_JsonNullable() {
    return userEmail;
  }
  
  @JsonProperty(JSON_PROPERTY_USER_EMAIL)
  public void setUserEmail_JsonNullable(JsonNullable<String> userEmail) {
    this.userEmail = userEmail;
  }

  public void setUserEmail(@jakarta.annotation.Nullable String userEmail) {
    this.userEmail = JsonNullable.<String>of(userEmail);
  }


  public DeviceLicenseAssignmentDto userId(@jakarta.annotation.Nullable UUID userId) {
    this.userId = userId;
    return this;
  }

  /**
   * Get userId
   * @return userId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_USER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getUserId() {
    return userId;
  }


  @JsonProperty(value = JSON_PROPERTY_USER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserId(@jakarta.annotation.Nullable UUID userId) {
    this.userId = userId;
  }


  public DeviceLicenseAssignmentDto clientId(@jakarta.annotation.Nullable String clientId) {
    this.clientId = JsonNullable.<String>of(clientId);
    return this;
  }

  /**
   * Get clientId
   * @return clientId
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getClientId() {
        return clientId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_CLIENT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getClientId_JsonNullable() {
    return clientId;
  }
  
  @JsonProperty(JSON_PROPERTY_CLIENT_ID)
  public void setClientId_JsonNullable(JsonNullable<String> clientId) {
    this.clientId = clientId;
  }

  public void setClientId(@jakarta.annotation.Nullable String clientId) {
    this.clientId = JsonNullable.<String>of(clientId);
  }


  public DeviceLicenseAssignmentDto activated(@jakarta.annotation.Nullable Boolean activated) {
    this.activated = activated;
    return this;
  }

  /**
   * Get activated
   * @return activated
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACTIVATED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getActivated() {
    return activated;
  }


  @JsonProperty(value = JSON_PROPERTY_ACTIVATED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActivated(@jakarta.annotation.Nullable Boolean activated) {
    this.activated = activated;
  }


  public DeviceLicenseAssignmentDto isSoftwareVersionValid(@jakarta.annotation.Nullable Boolean isSoftwareVersionValid) {
    this.isSoftwareVersionValid = isSoftwareVersionValid;
    return this;
  }

  /**
   * Get isSoftwareVersionValid
   * @return isSoftwareVersionValid
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IS_SOFTWARE_VERSION_VALID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsSoftwareVersionValid() {
    return isSoftwareVersionValid;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_SOFTWARE_VERSION_VALID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsSoftwareVersionValid(@jakarta.annotation.Nullable Boolean isSoftwareVersionValid) {
    this.isSoftwareVersionValid = isSoftwareVersionValid;
  }


  public DeviceLicenseAssignmentDto isGoodwillLicense(@jakarta.annotation.Nullable Boolean isGoodwillLicense) {
    this.isGoodwillLicense = isGoodwillLicense;
    return this;
  }

  /**
   * Get isGoodwillLicense
   * @return isGoodwillLicense
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IS_GOODWILL_LICENSE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsGoodwillLicense() {
    return isGoodwillLicense;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_GOODWILL_LICENSE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsGoodwillLicense(@jakarta.annotation.Nullable Boolean isGoodwillLicense) {
    this.isGoodwillLicense = isGoodwillLicense;
  }


  public DeviceLicenseAssignmentDto hasHeartbeats(@jakarta.annotation.Nullable Boolean hasHeartbeats) {
    this.hasHeartbeats = hasHeartbeats;
    return this;
  }

  /**
   * Get hasHeartbeats
   * @return hasHeartbeats
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HAS_HEARTBEATS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getHasHeartbeats() {
    return hasHeartbeats;
  }


  @JsonProperty(value = JSON_PROPERTY_HAS_HEARTBEATS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHasHeartbeats(@jakarta.annotation.Nullable Boolean hasHeartbeats) {
    this.hasHeartbeats = hasHeartbeats;
  }


  public DeviceLicenseAssignmentDto hasConsumptionHeartbeats(@jakarta.annotation.Nullable Boolean hasConsumptionHeartbeats) {
    this.hasConsumptionHeartbeats = hasConsumptionHeartbeats;
    return this;
  }

  /**
   * Get hasConsumptionHeartbeats
   * @return hasConsumptionHeartbeats
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HAS_CONSUMPTION_HEARTBEATS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getHasConsumptionHeartbeats() {
    return hasConsumptionHeartbeats;
  }


  @JsonProperty(value = JSON_PROPERTY_HAS_CONSUMPTION_HEARTBEATS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHasConsumptionHeartbeats(@jakarta.annotation.Nullable Boolean hasConsumptionHeartbeats) {
    this.hasConsumptionHeartbeats = hasConsumptionHeartbeats;
  }


  public DeviceLicenseAssignmentDto activatedDateUtc(@jakarta.annotation.Nullable OffsetDateTime activatedDateUtc) {
    this.activatedDateUtc = activatedDateUtc;
    return this;
  }

  /**
   * Get activatedDateUtc
   * @return activatedDateUtc
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACTIVATED_DATE_UTC, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getActivatedDateUtc() {
    return activatedDateUtc;
  }


  @JsonProperty(value = JSON_PROPERTY_ACTIVATED_DATE_UTC, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActivatedDateUtc(@jakarta.annotation.Nullable OffsetDateTime activatedDateUtc) {
    this.activatedDateUtc = activatedDateUtc;
  }


  public DeviceLicenseAssignmentDto heartbeatInfo(@jakarta.annotation.Nullable DeviceHeartbeatDto heartbeatInfo) {
    this.heartbeatInfo = JsonNullable.<DeviceHeartbeatDto>of(heartbeatInfo);
    return this;
  }

  /**
   * Get heartbeatInfo
   * @return heartbeatInfo
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public DeviceHeartbeatDto getHeartbeatInfo() {
        return heartbeatInfo.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_HEARTBEAT_INFO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<DeviceHeartbeatDto> getHeartbeatInfo_JsonNullable() {
    return heartbeatInfo;
  }
  
  @JsonProperty(JSON_PROPERTY_HEARTBEAT_INFO)
  public void setHeartbeatInfo_JsonNullable(JsonNullable<DeviceHeartbeatDto> heartbeatInfo) {
    this.heartbeatInfo = heartbeatInfo;
  }

  public void setHeartbeatInfo(@jakarta.annotation.Nullable DeviceHeartbeatDto heartbeatInfo) {
    this.heartbeatInfo = JsonNullable.<DeviceHeartbeatDto>of(heartbeatInfo);
  }


  public DeviceLicenseAssignmentDto enforceSoftwareVersionUpgrade(@jakarta.annotation.Nullable Boolean enforceSoftwareVersionUpgrade) {
    this.enforceSoftwareVersionUpgrade = enforceSoftwareVersionUpgrade;
    return this;
  }

  /**
   * Get enforceSoftwareVersionUpgrade
   * @return enforceSoftwareVersionUpgrade
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENFORCE_SOFTWARE_VERSION_UPGRADE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getEnforceSoftwareVersionUpgrade() {
    return enforceSoftwareVersionUpgrade;
  }


  @JsonProperty(value = JSON_PROPERTY_ENFORCE_SOFTWARE_VERSION_UPGRADE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnforceSoftwareVersionUpgrade(@jakarta.annotation.Nullable Boolean enforceSoftwareVersionUpgrade) {
    this.enforceSoftwareVersionUpgrade = enforceSoftwareVersionUpgrade;
  }


  public DeviceLicenseAssignmentDto deviceAnalyticalHeartbeats(@jakarta.annotation.Nullable List<DeviceAnalyticalHeartbeatDto> deviceAnalyticalHeartbeats) {
    this.deviceAnalyticalHeartbeats = JsonNullable.<List<DeviceAnalyticalHeartbeatDto>>of(deviceAnalyticalHeartbeats);
    return this;
  }

  public DeviceLicenseAssignmentDto addDeviceAnalyticalHeartbeatsItem(DeviceAnalyticalHeartbeatDto deviceAnalyticalHeartbeatsItem) {
    if (this.deviceAnalyticalHeartbeats == null || !this.deviceAnalyticalHeartbeats.isPresent()) {
      this.deviceAnalyticalHeartbeats = JsonNullable.<List<DeviceAnalyticalHeartbeatDto>>of(new ArrayList<>());
    }
    try {
      this.deviceAnalyticalHeartbeats.get().add(deviceAnalyticalHeartbeatsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get deviceAnalyticalHeartbeats
   * @return deviceAnalyticalHeartbeats
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public List<DeviceAnalyticalHeartbeatDto> getDeviceAnalyticalHeartbeats() {
        return deviceAnalyticalHeartbeats.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_DEVICE_ANALYTICAL_HEARTBEATS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<DeviceAnalyticalHeartbeatDto>> getDeviceAnalyticalHeartbeats_JsonNullable() {
    return deviceAnalyticalHeartbeats;
  }
  
  @JsonProperty(JSON_PROPERTY_DEVICE_ANALYTICAL_HEARTBEATS)
  public void setDeviceAnalyticalHeartbeats_JsonNullable(JsonNullable<List<DeviceAnalyticalHeartbeatDto>> deviceAnalyticalHeartbeats) {
    this.deviceAnalyticalHeartbeats = deviceAnalyticalHeartbeats;
  }

  public void setDeviceAnalyticalHeartbeats(@jakarta.annotation.Nullable List<DeviceAnalyticalHeartbeatDto> deviceAnalyticalHeartbeats) {
    this.deviceAnalyticalHeartbeats = JsonNullable.<List<DeviceAnalyticalHeartbeatDto>>of(deviceAnalyticalHeartbeats);
  }


  public DeviceLicenseAssignmentDto softwareVersion(@jakarta.annotation.Nullable String softwareVersion) {
    this.softwareVersion = JsonNullable.<String>of(softwareVersion);
    return this;
  }

  /**
   * Get softwareVersion
   * @return softwareVersion
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getSoftwareVersion() {
        return softwareVersion.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_SOFTWARE_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getSoftwareVersion_JsonNullable() {
    return softwareVersion;
  }
  
  @JsonProperty(JSON_PROPERTY_SOFTWARE_VERSION)
  public void setSoftwareVersion_JsonNullable(JsonNullable<String> softwareVersion) {
    this.softwareVersion = softwareVersion;
  }

  public void setSoftwareVersion(@jakarta.annotation.Nullable String softwareVersion) {
    this.softwareVersion = JsonNullable.<String>of(softwareVersion);
  }


  public DeviceLicenseAssignmentDto operatingSystem(@jakarta.annotation.Nullable String operatingSystem) {
    this.operatingSystem = JsonNullable.<String>of(operatingSystem);
    return this;
  }

  /**
   * Get operatingSystem
   * @return operatingSystem
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getOperatingSystem() {
        return operatingSystem.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_OPERATING_SYSTEM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getOperatingSystem_JsonNullable() {
    return operatingSystem;
  }
  
  @JsonProperty(JSON_PROPERTY_OPERATING_SYSTEM)
  public void setOperatingSystem_JsonNullable(JsonNullable<String> operatingSystem) {
    this.operatingSystem = operatingSystem;
  }

  public void setOperatingSystem(@jakarta.annotation.Nullable String operatingSystem) {
    this.operatingSystem = JsonNullable.<String>of(operatingSystem);
  }


  public DeviceLicenseAssignmentDto tagAssignments(@jakarta.annotation.Nullable List<TagAssignmentDto> tagAssignments) {
    this.tagAssignments = JsonNullable.<List<TagAssignmentDto>>of(tagAssignments);
    return this;
  }

  public DeviceLicenseAssignmentDto addTagAssignmentsItem(TagAssignmentDto tagAssignmentsItem) {
    if (this.tagAssignments == null || !this.tagAssignments.isPresent()) {
      this.tagAssignments = JsonNullable.<List<TagAssignmentDto>>of(new ArrayList<>());
    }
    try {
      this.tagAssignments.get().add(tagAssignmentsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get tagAssignments
   * @return tagAssignments
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public List<TagAssignmentDto> getTagAssignments() {
        return tagAssignments.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_TAG_ASSIGNMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<TagAssignmentDto>> getTagAssignments_JsonNullable() {
    return tagAssignments;
  }
  
  @JsonProperty(JSON_PROPERTY_TAG_ASSIGNMENTS)
  public void setTagAssignments_JsonNullable(JsonNullable<List<TagAssignmentDto>> tagAssignments) {
    this.tagAssignments = tagAssignments;
  }

  public void setTagAssignments(@jakarta.annotation.Nullable List<TagAssignmentDto> tagAssignments) {
    this.tagAssignments = JsonNullable.<List<TagAssignmentDto>>of(tagAssignments);
  }


  public DeviceLicenseAssignmentDto licenseActivationType(@jakarta.annotation.Nullable LicenseActivationType licenseActivationType) {
    this.licenseActivationType = licenseActivationType;
    return this;
  }

  /**
   * Get licenseActivationType
   * @return licenseActivationType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LICENSE_ACTIVATION_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public LicenseActivationType getLicenseActivationType() {
    return licenseActivationType;
  }


  @JsonProperty(value = JSON_PROPERTY_LICENSE_ACTIVATION_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLicenseActivationType(@jakarta.annotation.Nullable LicenseActivationType licenseActivationType) {
    this.licenseActivationType = licenseActivationType;
  }


  public DeviceLicenseAssignmentDto suspendedUntilUtc(@jakarta.annotation.Nullable OffsetDateTime suspendedUntilUtc) {
    this.suspendedUntilUtc = JsonNullable.<OffsetDateTime>of(suspendedUntilUtc);
    return this;
  }

  /**
   * Get suspendedUntilUtc
   * @return suspendedUntilUtc
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public OffsetDateTime getSuspendedUntilUtc() {
        return suspendedUntilUtc.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_SUSPENDED_UNTIL_UTC, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getSuspendedUntilUtc_JsonNullable() {
    return suspendedUntilUtc;
  }
  
  @JsonProperty(JSON_PROPERTY_SUSPENDED_UNTIL_UTC)
  public void setSuspendedUntilUtc_JsonNullable(JsonNullable<OffsetDateTime> suspendedUntilUtc) {
    this.suspendedUntilUtc = suspendedUntilUtc;
  }

  public void setSuspendedUntilUtc(@jakarta.annotation.Nullable OffsetDateTime suspendedUntilUtc) {
    this.suspendedUntilUtc = JsonNullable.<OffsetDateTime>of(suspendedUntilUtc);
  }


  public DeviceLicenseAssignmentDto createdDateUtc(@jakarta.annotation.Nullable OffsetDateTime createdDateUtc) {
    this.createdDateUtc = JsonNullable.<OffsetDateTime>of(createdDateUtc);
    return this;
  }

  /**
   * Get createdDateUtc
   * @return createdDateUtc
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public OffsetDateTime getCreatedDateUtc() {
        return createdDateUtc.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_CREATED_DATE_UTC, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getCreatedDateUtc_JsonNullable() {
    return createdDateUtc;
  }
  
  @JsonProperty(JSON_PROPERTY_CREATED_DATE_UTC)
  public void setCreatedDateUtc_JsonNullable(JsonNullable<OffsetDateTime> createdDateUtc) {
    this.createdDateUtc = createdDateUtc;
  }

  public void setCreatedDateUtc(@jakarta.annotation.Nullable OffsetDateTime createdDateUtc) {
    this.createdDateUtc = JsonNullable.<OffsetDateTime>of(createdDateUtc);
  }


  public DeviceLicenseAssignmentDto modifiedDateUtc(@jakarta.annotation.Nullable OffsetDateTime modifiedDateUtc) {
    this.modifiedDateUtc = JsonNullable.<OffsetDateTime>of(modifiedDateUtc);
    return this;
  }

  /**
   * Get modifiedDateUtc
   * @return modifiedDateUtc
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public OffsetDateTime getModifiedDateUtc() {
        return modifiedDateUtc.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_MODIFIED_DATE_UTC, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getModifiedDateUtc_JsonNullable() {
    return modifiedDateUtc;
  }
  
  @JsonProperty(JSON_PROPERTY_MODIFIED_DATE_UTC)
  public void setModifiedDateUtc_JsonNullable(JsonNullable<OffsetDateTime> modifiedDateUtc) {
    this.modifiedDateUtc = modifiedDateUtc;
  }

  public void setModifiedDateUtc(@jakarta.annotation.Nullable OffsetDateTime modifiedDateUtc) {
    this.modifiedDateUtc = JsonNullable.<OffsetDateTime>of(modifiedDateUtc);
  }


  public DeviceLicenseAssignmentDto lastModifiedBy(@jakarta.annotation.Nullable String lastModifiedBy) {
    this.lastModifiedBy = JsonNullable.<String>of(lastModifiedBy);
    return this;
  }

  /**
   * Get lastModifiedBy
   * @return lastModifiedBy
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getLastModifiedBy() {
        return lastModifiedBy.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_LAST_MODIFIED_BY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLastModifiedBy_JsonNullable() {
    return lastModifiedBy;
  }
  
  @JsonProperty(JSON_PROPERTY_LAST_MODIFIED_BY)
  public void setLastModifiedBy_JsonNullable(JsonNullable<String> lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }

  public void setLastModifiedBy(@jakarta.annotation.Nullable String lastModifiedBy) {
    this.lastModifiedBy = JsonNullable.<String>of(lastModifiedBy);
  }


  /**
   * Return true if this DeviceLicenseAssignmentDto object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeviceLicenseAssignmentDto deviceLicenseAssignmentDto = (DeviceLicenseAssignmentDto) o;
    return Objects.equals(this.id, deviceLicenseAssignmentDto.id) &&
        Objects.equals(this.licenseId, deviceLicenseAssignmentDto.licenseId) &&
        Objects.equals(this.productId, deviceLicenseAssignmentDto.productId) &&
        equalsNullable(this.deviceName, deviceLicenseAssignmentDto.deviceName) &&
        equalsNullable(this.deviceDescription, deviceLicenseAssignmentDto.deviceDescription) &&
        Objects.equals(this.tokenKey, deviceLicenseAssignmentDto.tokenKey) &&
        equalsNullable(this.userEmail, deviceLicenseAssignmentDto.userEmail) &&
        Objects.equals(this.userId, deviceLicenseAssignmentDto.userId) &&
        equalsNullable(this.clientId, deviceLicenseAssignmentDto.clientId) &&
        Objects.equals(this.activated, deviceLicenseAssignmentDto.activated) &&
        Objects.equals(this.isSoftwareVersionValid, deviceLicenseAssignmentDto.isSoftwareVersionValid) &&
        Objects.equals(this.isGoodwillLicense, deviceLicenseAssignmentDto.isGoodwillLicense) &&
        Objects.equals(this.hasHeartbeats, deviceLicenseAssignmentDto.hasHeartbeats) &&
        Objects.equals(this.hasConsumptionHeartbeats, deviceLicenseAssignmentDto.hasConsumptionHeartbeats) &&
        Objects.equals(this.activatedDateUtc, deviceLicenseAssignmentDto.activatedDateUtc) &&
        equalsNullable(this.heartbeatInfo, deviceLicenseAssignmentDto.heartbeatInfo) &&
        Objects.equals(this.enforceSoftwareVersionUpgrade, deviceLicenseAssignmentDto.enforceSoftwareVersionUpgrade) &&
        equalsNullable(this.deviceAnalyticalHeartbeats, deviceLicenseAssignmentDto.deviceAnalyticalHeartbeats) &&
        equalsNullable(this.softwareVersion, deviceLicenseAssignmentDto.softwareVersion) &&
        equalsNullable(this.operatingSystem, deviceLicenseAssignmentDto.operatingSystem) &&
        equalsNullable(this.tagAssignments, deviceLicenseAssignmentDto.tagAssignments) &&
        Objects.equals(this.licenseActivationType, deviceLicenseAssignmentDto.licenseActivationType) &&
        equalsNullable(this.suspendedUntilUtc, deviceLicenseAssignmentDto.suspendedUntilUtc) &&
        equalsNullable(this.createdDateUtc, deviceLicenseAssignmentDto.createdDateUtc) &&
        equalsNullable(this.modifiedDateUtc, deviceLicenseAssignmentDto.modifiedDateUtc) &&
        equalsNullable(this.lastModifiedBy, deviceLicenseAssignmentDto.lastModifiedBy);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, licenseId, productId, hashCodeNullable(deviceName), hashCodeNullable(deviceDescription), tokenKey, hashCodeNullable(userEmail), userId, hashCodeNullable(clientId), activated, isSoftwareVersionValid, isGoodwillLicense, hasHeartbeats, hasConsumptionHeartbeats, activatedDateUtc, hashCodeNullable(heartbeatInfo), enforceSoftwareVersionUpgrade, hashCodeNullable(deviceAnalyticalHeartbeats), hashCodeNullable(softwareVersion), hashCodeNullable(operatingSystem), hashCodeNullable(tagAssignments), licenseActivationType, hashCodeNullable(suspendedUntilUtc), hashCodeNullable(createdDateUtc), hashCodeNullable(modifiedDateUtc), hashCodeNullable(lastModifiedBy));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceLicenseAssignmentDto {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    licenseId: ").append(toIndentedString(licenseId)).append("\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    deviceName: ").append(toIndentedString(deviceName)).append("\n");
    sb.append("    deviceDescription: ").append(toIndentedString(deviceDescription)).append("\n");
    sb.append("    tokenKey: ").append(toIndentedString(tokenKey)).append("\n");
    sb.append("    userEmail: ").append(toIndentedString(userEmail)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    activated: ").append(toIndentedString(activated)).append("\n");
    sb.append("    isSoftwareVersionValid: ").append(toIndentedString(isSoftwareVersionValid)).append("\n");
    sb.append("    isGoodwillLicense: ").append(toIndentedString(isGoodwillLicense)).append("\n");
    sb.append("    hasHeartbeats: ").append(toIndentedString(hasHeartbeats)).append("\n");
    sb.append("    hasConsumptionHeartbeats: ").append(toIndentedString(hasConsumptionHeartbeats)).append("\n");
    sb.append("    activatedDateUtc: ").append(toIndentedString(activatedDateUtc)).append("\n");
    sb.append("    heartbeatInfo: ").append(toIndentedString(heartbeatInfo)).append("\n");
    sb.append("    enforceSoftwareVersionUpgrade: ").append(toIndentedString(enforceSoftwareVersionUpgrade)).append("\n");
    sb.append("    deviceAnalyticalHeartbeats: ").append(toIndentedString(deviceAnalyticalHeartbeats)).append("\n");
    sb.append("    softwareVersion: ").append(toIndentedString(softwareVersion)).append("\n");
    sb.append("    operatingSystem: ").append(toIndentedString(operatingSystem)).append("\n");
    sb.append("    tagAssignments: ").append(toIndentedString(tagAssignments)).append("\n");
    sb.append("    licenseActivationType: ").append(toIndentedString(licenseActivationType)).append("\n");
    sb.append("    suspendedUntilUtc: ").append(toIndentedString(suspendedUntilUtc)).append("\n");
    sb.append("    createdDateUtc: ").append(toIndentedString(createdDateUtc)).append("\n");
    sb.append("    modifiedDateUtc: ").append(toIndentedString(modifiedDateUtc)).append("\n");
    sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `license_id` to the URL query string
    if (getLicenseId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slicense_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLicenseId()))));
    }

    // add `product_id` to the URL query string
    if (getProductId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sproduct_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProductId()))));
    }

    // add `device_name` to the URL query string
    if (getDeviceName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdevice_name%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDeviceName()))));
    }

    // add `device_description` to the URL query string
    if (getDeviceDescription() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdevice_description%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDeviceDescription()))));
    }

    // add `token_key` to the URL query string
    if (getTokenKey() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stoken_key%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTokenKey()))));
    }

    // add `user_email` to the URL query string
    if (getUserEmail() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%suser_email%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUserEmail()))));
    }

    // add `user_id` to the URL query string
    if (getUserId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%suser_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUserId()))));
    }

    // add `client_id` to the URL query string
    if (getClientId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sclient_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getClientId()))));
    }

    // add `activated` to the URL query string
    if (getActivated() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sactivated%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getActivated()))));
    }

    // add `is_software_version_valid` to the URL query string
    if (getIsSoftwareVersionValid() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sis_software_version_valid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsSoftwareVersionValid()))));
    }

    // add `is_goodwill_license` to the URL query string
    if (getIsGoodwillLicense() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sis_goodwill_license%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsGoodwillLicense()))));
    }

    // add `has_heartbeats` to the URL query string
    if (getHasHeartbeats() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%shas_heartbeats%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHasHeartbeats()))));
    }

    // add `has_consumption_heartbeats` to the URL query string
    if (getHasConsumptionHeartbeats() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%shas_consumption_heartbeats%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHasConsumptionHeartbeats()))));
    }

    // add `activated_date_utc` to the URL query string
    if (getActivatedDateUtc() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sactivated_date_utc%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getActivatedDateUtc()))));
    }

    // add `heartbeat_info` to the URL query string
    if (getHeartbeatInfo() != null) {
      joiner.add(getHeartbeatInfo().toUrlQueryString(prefix + "heartbeat_info" + suffix));
    }

    // add `enforce_software_version_upgrade` to the URL query string
    if (getEnforceSoftwareVersionUpgrade() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%senforce_software_version_upgrade%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEnforceSoftwareVersionUpgrade()))));
    }

    // add `device_analytical_heartbeats` to the URL query string
    if (getDeviceAnalyticalHeartbeats() != null) {
      for (int i = 0; i < getDeviceAnalyticalHeartbeats().size(); i++) {
        if (getDeviceAnalyticalHeartbeats().get(i) != null) {
          joiner.add(getDeviceAnalyticalHeartbeats().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sdevice_analytical_heartbeats%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `software_version` to the URL query string
    if (getSoftwareVersion() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssoftware_version%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSoftwareVersion()))));
    }

    // add `operating_system` to the URL query string
    if (getOperatingSystem() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%soperating_system%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOperatingSystem()))));
    }

    // add `tag_assignments` to the URL query string
    if (getTagAssignments() != null) {
      for (int i = 0; i < getTagAssignments().size(); i++) {
        if (getTagAssignments().get(i) != null) {
          joiner.add(getTagAssignments().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%stag_assignments%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `license_activation_type` to the URL query string
    if (getLicenseActivationType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slicense_activation_type%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLicenseActivationType()))));
    }

    // add `suspended_until_utc` to the URL query string
    if (getSuspendedUntilUtc() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssuspended_until_utc%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSuspendedUntilUtc()))));
    }

    // add `created_date_utc` to the URL query string
    if (getCreatedDateUtc() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screated_date_utc%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedDateUtc()))));
    }

    // add `modified_date_utc` to the URL query string
    if (getModifiedDateUtc() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smodified_date_utc%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getModifiedDateUtc()))));
    }

    // add `last_modified_by` to the URL query string
    if (getLastModifiedBy() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slast_modified_by%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLastModifiedBy()))));
    }

    return joiner.toString();
  }
}

