/*
 * SLASCONE API
 * Please visit our official [Documentation](https://support.slascone.com/hc/en-us/sections/360004685737-API) and/or our [GitHub repository](https://github.com/slascone/) and/or our [NuGet package](https://www.nuget.org/packages/Slascone.Client/). Always use Version 2 of this API (Version 1.3 is deprecated).
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.slascone.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.slascone.model.AnalyticalFieldDto;
import com.slascone.model.LicenseUserDto;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.slascone.ApiClient;
/**
 * DeviceAnalyticalHeartbeatDto
 */
@JsonPropertyOrder({
  DeviceAnalyticalHeartbeatDto.JSON_PROPERTY_LICENSE_ASSIGNMENT_ID,
  DeviceAnalyticalHeartbeatDto.JSON_PROPERTY_ANALYTICAL_FIELD_ID,
  DeviceAnalyticalHeartbeatDto.JSON_PROPERTY_VALUE,
  DeviceAnalyticalHeartbeatDto.JSON_PROPERTY_VALUE_ARRAY,
  DeviceAnalyticalHeartbeatDto.JSON_PROPERTY_TRANSACTION_ID,
  DeviceAnalyticalHeartbeatDto.JSON_PROPERTY_SOFTWARE_VERSION,
  DeviceAnalyticalHeartbeatDto.JSON_PROPERTY_CREATED_DATE_UTC,
  DeviceAnalyticalHeartbeatDto.JSON_PROPERTY_MODIFIED_DATE_UTC,
  DeviceAnalyticalHeartbeatDto.JSON_PROPERTY_IS_LAST,
  DeviceAnalyticalHeartbeatDto.JSON_PROPERTY_ANALYTICAL_FIELD,
  DeviceAnalyticalHeartbeatDto.JSON_PROPERTY_USER_ID,
  DeviceAnalyticalHeartbeatDto.JSON_PROPERTY_LICENSE_USER
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0-SNAPSHOT")
public class DeviceAnalyticalHeartbeatDto {
  public static final String JSON_PROPERTY_LICENSE_ASSIGNMENT_ID = "license_assignment_id";
  @jakarta.annotation.Nullable
  private UUID licenseAssignmentId;

  public static final String JSON_PROPERTY_ANALYTICAL_FIELD_ID = "analytical_field_id";
  @jakarta.annotation.Nullable
  private UUID analyticalFieldId;

  public static final String JSON_PROPERTY_VALUE = "value";
  private JsonNullable<String> value = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_VALUE_ARRAY = "value_array";
  private JsonNullable<List<String>> valueArray = JsonNullable.<List<String>>undefined();

  public static final String JSON_PROPERTY_TRANSACTION_ID = "transaction_id";
  @jakarta.annotation.Nullable
  private UUID transactionId;

  public static final String JSON_PROPERTY_SOFTWARE_VERSION = "software_version";
  private JsonNullable<String> softwareVersion = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_CREATED_DATE_UTC = "created_date_utc";
  @jakarta.annotation.Nullable
  private OffsetDateTime createdDateUtc;

  public static final String JSON_PROPERTY_MODIFIED_DATE_UTC = "modified_date_utc";
  @jakarta.annotation.Nullable
  private OffsetDateTime modifiedDateUtc;

  public static final String JSON_PROPERTY_IS_LAST = "is_last";
  @jakarta.annotation.Nullable
  private Boolean isLast;

  public static final String JSON_PROPERTY_ANALYTICAL_FIELD = "analytical_field";
  private JsonNullable<AnalyticalFieldDto> analyticalField = JsonNullable.<AnalyticalFieldDto>undefined();

  public static final String JSON_PROPERTY_USER_ID = "user_id";
  private JsonNullable<String> userId = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_LICENSE_USER = "license_user";
  private JsonNullable<LicenseUserDto> licenseUser = JsonNullable.<LicenseUserDto>undefined();

  public DeviceAnalyticalHeartbeatDto() { 
  }

  public DeviceAnalyticalHeartbeatDto licenseAssignmentId(@jakarta.annotation.Nullable UUID licenseAssignmentId) {
    this.licenseAssignmentId = licenseAssignmentId;
    return this;
  }

  /**
   * Get licenseAssignmentId
   * @return licenseAssignmentId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LICENSE_ASSIGNMENT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getLicenseAssignmentId() {
    return licenseAssignmentId;
  }


  @JsonProperty(value = JSON_PROPERTY_LICENSE_ASSIGNMENT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLicenseAssignmentId(@jakarta.annotation.Nullable UUID licenseAssignmentId) {
    this.licenseAssignmentId = licenseAssignmentId;
  }


  public DeviceAnalyticalHeartbeatDto analyticalFieldId(@jakarta.annotation.Nullable UUID analyticalFieldId) {
    this.analyticalFieldId = analyticalFieldId;
    return this;
  }

  /**
   * Get analyticalFieldId
   * @return analyticalFieldId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ANALYTICAL_FIELD_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getAnalyticalFieldId() {
    return analyticalFieldId;
  }


  @JsonProperty(value = JSON_PROPERTY_ANALYTICAL_FIELD_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAnalyticalFieldId(@jakarta.annotation.Nullable UUID analyticalFieldId) {
    this.analyticalFieldId = analyticalFieldId;
  }


  public DeviceAnalyticalHeartbeatDto value(@jakarta.annotation.Nullable String value) {
    this.value = JsonNullable.<String>of(value);
    return this;
  }

  /**
   * Get value
   * @return value
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getValue() {
        return value.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getValue_JsonNullable() {
    return value;
  }
  
  @JsonProperty(JSON_PROPERTY_VALUE)
  public void setValue_JsonNullable(JsonNullable<String> value) {
    this.value = value;
  }

  public void setValue(@jakarta.annotation.Nullable String value) {
    this.value = JsonNullable.<String>of(value);
  }


  public DeviceAnalyticalHeartbeatDto valueArray(@jakarta.annotation.Nullable List<String> valueArray) {
    this.valueArray = JsonNullable.<List<String>>of(valueArray);
    return this;
  }

  public DeviceAnalyticalHeartbeatDto addValueArrayItem(String valueArrayItem) {
    if (this.valueArray == null || !this.valueArray.isPresent()) {
      this.valueArray = JsonNullable.<List<String>>of(new ArrayList<>());
    }
    try {
      this.valueArray.get().add(valueArrayItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get valueArray
   * @return valueArray
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public List<String> getValueArray() {
        return valueArray.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_VALUE_ARRAY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<String>> getValueArray_JsonNullable() {
    return valueArray;
  }
  
  @JsonProperty(JSON_PROPERTY_VALUE_ARRAY)
  public void setValueArray_JsonNullable(JsonNullable<List<String>> valueArray) {
    this.valueArray = valueArray;
  }

  public void setValueArray(@jakarta.annotation.Nullable List<String> valueArray) {
    this.valueArray = JsonNullable.<List<String>>of(valueArray);
  }


  public DeviceAnalyticalHeartbeatDto transactionId(@jakarta.annotation.Nullable UUID transactionId) {
    this.transactionId = transactionId;
    return this;
  }

  /**
   * Get transactionId
   * @return transactionId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRANSACTION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getTransactionId() {
    return transactionId;
  }


  @JsonProperty(value = JSON_PROPERTY_TRANSACTION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTransactionId(@jakarta.annotation.Nullable UUID transactionId) {
    this.transactionId = transactionId;
  }


  public DeviceAnalyticalHeartbeatDto softwareVersion(@jakarta.annotation.Nullable String softwareVersion) {
    this.softwareVersion = JsonNullable.<String>of(softwareVersion);
    return this;
  }

  /**
   * Get softwareVersion
   * @return softwareVersion
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getSoftwareVersion() {
        return softwareVersion.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_SOFTWARE_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getSoftwareVersion_JsonNullable() {
    return softwareVersion;
  }
  
  @JsonProperty(JSON_PROPERTY_SOFTWARE_VERSION)
  public void setSoftwareVersion_JsonNullable(JsonNullable<String> softwareVersion) {
    this.softwareVersion = softwareVersion;
  }

  public void setSoftwareVersion(@jakarta.annotation.Nullable String softwareVersion) {
    this.softwareVersion = JsonNullable.<String>of(softwareVersion);
  }


  public DeviceAnalyticalHeartbeatDto createdDateUtc(@jakarta.annotation.Nullable OffsetDateTime createdDateUtc) {
    this.createdDateUtc = createdDateUtc;
    return this;
  }

  /**
   * Get createdDateUtc
   * @return createdDateUtc
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_DATE_UTC, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getCreatedDateUtc() {
    return createdDateUtc;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_DATE_UTC, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedDateUtc(@jakarta.annotation.Nullable OffsetDateTime createdDateUtc) {
    this.createdDateUtc = createdDateUtc;
  }


  public DeviceAnalyticalHeartbeatDto modifiedDateUtc(@jakarta.annotation.Nullable OffsetDateTime modifiedDateUtc) {
    this.modifiedDateUtc = modifiedDateUtc;
    return this;
  }

  /**
   * Get modifiedDateUtc
   * @return modifiedDateUtc
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MODIFIED_DATE_UTC, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getModifiedDateUtc() {
    return modifiedDateUtc;
  }


  @JsonProperty(value = JSON_PROPERTY_MODIFIED_DATE_UTC, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setModifiedDateUtc(@jakarta.annotation.Nullable OffsetDateTime modifiedDateUtc) {
    this.modifiedDateUtc = modifiedDateUtc;
  }


  public DeviceAnalyticalHeartbeatDto isLast(@jakarta.annotation.Nullable Boolean isLast) {
    this.isLast = isLast;
    return this;
  }

  /**
   * Get isLast
   * @return isLast
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IS_LAST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsLast() {
    return isLast;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_LAST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsLast(@jakarta.annotation.Nullable Boolean isLast) {
    this.isLast = isLast;
  }


  public DeviceAnalyticalHeartbeatDto analyticalField(@jakarta.annotation.Nullable AnalyticalFieldDto analyticalField) {
    this.analyticalField = JsonNullable.<AnalyticalFieldDto>of(analyticalField);
    return this;
  }

  /**
   * Get analyticalField
   * @return analyticalField
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public AnalyticalFieldDto getAnalyticalField() {
        return analyticalField.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_ANALYTICAL_FIELD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<AnalyticalFieldDto> getAnalyticalField_JsonNullable() {
    return analyticalField;
  }
  
  @JsonProperty(JSON_PROPERTY_ANALYTICAL_FIELD)
  public void setAnalyticalField_JsonNullable(JsonNullable<AnalyticalFieldDto> analyticalField) {
    this.analyticalField = analyticalField;
  }

  public void setAnalyticalField(@jakarta.annotation.Nullable AnalyticalFieldDto analyticalField) {
    this.analyticalField = JsonNullable.<AnalyticalFieldDto>of(analyticalField);
  }


  public DeviceAnalyticalHeartbeatDto userId(@jakarta.annotation.Nullable String userId) {
    this.userId = JsonNullable.<String>of(userId);
    return this;
  }

  /**
   * Get userId
   * @return userId
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getUserId() {
        return userId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_USER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getUserId_JsonNullable() {
    return userId;
  }
  
  @JsonProperty(JSON_PROPERTY_USER_ID)
  public void setUserId_JsonNullable(JsonNullable<String> userId) {
    this.userId = userId;
  }

  public void setUserId(@jakarta.annotation.Nullable String userId) {
    this.userId = JsonNullable.<String>of(userId);
  }


  public DeviceAnalyticalHeartbeatDto licenseUser(@jakarta.annotation.Nullable LicenseUserDto licenseUser) {
    this.licenseUser = JsonNullable.<LicenseUserDto>of(licenseUser);
    return this;
  }

  /**
   * Get licenseUser
   * @return licenseUser
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public LicenseUserDto getLicenseUser() {
        return licenseUser.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_LICENSE_USER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<LicenseUserDto> getLicenseUser_JsonNullable() {
    return licenseUser;
  }
  
  @JsonProperty(JSON_PROPERTY_LICENSE_USER)
  public void setLicenseUser_JsonNullable(JsonNullable<LicenseUserDto> licenseUser) {
    this.licenseUser = licenseUser;
  }

  public void setLicenseUser(@jakarta.annotation.Nullable LicenseUserDto licenseUser) {
    this.licenseUser = JsonNullable.<LicenseUserDto>of(licenseUser);
  }


  /**
   * Return true if this DeviceAnalyticalHeartbeatDto object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeviceAnalyticalHeartbeatDto deviceAnalyticalHeartbeatDto = (DeviceAnalyticalHeartbeatDto) o;
    return Objects.equals(this.licenseAssignmentId, deviceAnalyticalHeartbeatDto.licenseAssignmentId) &&
        Objects.equals(this.analyticalFieldId, deviceAnalyticalHeartbeatDto.analyticalFieldId) &&
        equalsNullable(this.value, deviceAnalyticalHeartbeatDto.value) &&
        equalsNullable(this.valueArray, deviceAnalyticalHeartbeatDto.valueArray) &&
        Objects.equals(this.transactionId, deviceAnalyticalHeartbeatDto.transactionId) &&
        equalsNullable(this.softwareVersion, deviceAnalyticalHeartbeatDto.softwareVersion) &&
        Objects.equals(this.createdDateUtc, deviceAnalyticalHeartbeatDto.createdDateUtc) &&
        Objects.equals(this.modifiedDateUtc, deviceAnalyticalHeartbeatDto.modifiedDateUtc) &&
        Objects.equals(this.isLast, deviceAnalyticalHeartbeatDto.isLast) &&
        equalsNullable(this.analyticalField, deviceAnalyticalHeartbeatDto.analyticalField) &&
        equalsNullable(this.userId, deviceAnalyticalHeartbeatDto.userId) &&
        equalsNullable(this.licenseUser, deviceAnalyticalHeartbeatDto.licenseUser);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(licenseAssignmentId, analyticalFieldId, hashCodeNullable(value), hashCodeNullable(valueArray), transactionId, hashCodeNullable(softwareVersion), createdDateUtc, modifiedDateUtc, isLast, hashCodeNullable(analyticalField), hashCodeNullable(userId), hashCodeNullable(licenseUser));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceAnalyticalHeartbeatDto {\n");
    sb.append("    licenseAssignmentId: ").append(toIndentedString(licenseAssignmentId)).append("\n");
    sb.append("    analyticalFieldId: ").append(toIndentedString(analyticalFieldId)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    valueArray: ").append(toIndentedString(valueArray)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    softwareVersion: ").append(toIndentedString(softwareVersion)).append("\n");
    sb.append("    createdDateUtc: ").append(toIndentedString(createdDateUtc)).append("\n");
    sb.append("    modifiedDateUtc: ").append(toIndentedString(modifiedDateUtc)).append("\n");
    sb.append("    isLast: ").append(toIndentedString(isLast)).append("\n");
    sb.append("    analyticalField: ").append(toIndentedString(analyticalField)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    licenseUser: ").append(toIndentedString(licenseUser)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `license_assignment_id` to the URL query string
    if (getLicenseAssignmentId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slicense_assignment_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLicenseAssignmentId()))));
    }

    // add `analytical_field_id` to the URL query string
    if (getAnalyticalFieldId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sanalytical_field_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAnalyticalFieldId()))));
    }

    // add `value` to the URL query string
    if (getValue() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%svalue%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getValue()))));
    }

    // add `value_array` to the URL query string
    if (getValueArray() != null) {
      for (int i = 0; i < getValueArray().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%svalue_array%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getValueArray().get(i)))));
      }
    }

    // add `transaction_id` to the URL query string
    if (getTransactionId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stransaction_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTransactionId()))));
    }

    // add `software_version` to the URL query string
    if (getSoftwareVersion() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssoftware_version%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSoftwareVersion()))));
    }

    // add `created_date_utc` to the URL query string
    if (getCreatedDateUtc() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screated_date_utc%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedDateUtc()))));
    }

    // add `modified_date_utc` to the URL query string
    if (getModifiedDateUtc() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smodified_date_utc%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getModifiedDateUtc()))));
    }

    // add `is_last` to the URL query string
    if (getIsLast() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sis_last%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsLast()))));
    }

    // add `analytical_field` to the URL query string
    if (getAnalyticalField() != null) {
      joiner.add(getAnalyticalField().toUrlQueryString(prefix + "analytical_field" + suffix));
    }

    // add `user_id` to the URL query string
    if (getUserId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%suser_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUserId()))));
    }

    // add `license_user` to the URL query string
    if (getLicenseUser() != null) {
      joiner.add(getLicenseUser().toUrlQueryString(prefix + "license_user" + suffix));
    }

    return joiner.toString();
  }
}

