/*
 * SLASCONE API
 * Please visit our official [Documentation](https://support.slascone.com/hc/en-us/sections/360004685737-API) and/or our [GitHub repository](https://github.com/slascone/) and/or our [NuGet package](https://www.nuget.org/packages/Slascone.Client/). Always use Version 2 of this API (Version 1.3 is deprecated).
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.slascone.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.slascone.model.HeartbeatTypeDto;
import com.slascone.model.LicenseUserDto;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.slascone.ApiClient;
/**
 * DeviceHeartbeatDto
 */
@JsonPropertyOrder({
  DeviceHeartbeatDto.JSON_PROPERTY_ID,
  DeviceHeartbeatDto.JSON_PROPERTY_SOFTWARE_VERSION,
  DeviceHeartbeatDto.JSON_PROPERTY_OPERATING_SYSTEM,
  DeviceHeartbeatDto.JSON_PROPERTY_IP_ADDRESS,
  DeviceHeartbeatDto.JSON_PROPERTY_CLIENT_ID,
  DeviceHeartbeatDto.JSON_PROPERTY_COUNTRY,
  DeviceHeartbeatDto.JSON_PROPERTY_CITY,
  DeviceHeartbeatDto.JSON_PROPERTY_ZIP,
  DeviceHeartbeatDto.JSON_PROPERTY_LATITUDE,
  DeviceHeartbeatDto.JSON_PROPERTY_LONGITUDE,
  DeviceHeartbeatDto.JSON_PROPERTY_CREATED_DATE_UTC,
  DeviceHeartbeatDto.JSON_PROPERTY_DEVICE_LICENSE_ASSIGNMENT_ID,
  DeviceHeartbeatDto.JSON_PROPERTY_DEVICE_LICENSE_ID,
  DeviceHeartbeatDto.JSON_PROPERTY_CUSTOMER_NAME,
  DeviceHeartbeatDto.JSON_PROPERTY_HEARTBEAT_TYPE_ID,
  DeviceHeartbeatDto.JSON_PROPERTY_HEARTBEAT_TYPE,
  DeviceHeartbeatDto.JSON_PROPERTY_USER_ID,
  DeviceHeartbeatDto.JSON_PROPERTY_LICENSE_USER,
  DeviceHeartbeatDto.JSON_PROPERTY_GROUP_ID,
  DeviceHeartbeatDto.JSON_PROPERTY_VALUE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0-SNAPSHOT")
public class DeviceHeartbeatDto {
  public static final String JSON_PROPERTY_ID = "id";
  private JsonNullable<UUID> id = JsonNullable.<UUID>undefined();

  public static final String JSON_PROPERTY_SOFTWARE_VERSION = "software_version";
  private JsonNullable<String> softwareVersion = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_OPERATING_SYSTEM = "operating_system";
  private JsonNullable<String> operatingSystem = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_IP_ADDRESS = "ip_address";
  private JsonNullable<String> ipAddress = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_CLIENT_ID = "client_id";
  private JsonNullable<String> clientId = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_COUNTRY = "country";
  private JsonNullable<String> country = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_CITY = "city";
  private JsonNullable<String> city = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_ZIP = "zip";
  private JsonNullable<String> zip = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_LATITUDE = "latitude";
  private JsonNullable<String> latitude = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_LONGITUDE = "longitude";
  private JsonNullable<String> longitude = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_CREATED_DATE_UTC = "created_date_utc";
  @jakarta.annotation.Nullable
  private OffsetDateTime createdDateUtc;

  public static final String JSON_PROPERTY_DEVICE_LICENSE_ASSIGNMENT_ID = "device_license_assignment_id";
  @jakarta.annotation.Nullable
  private UUID deviceLicenseAssignmentId;

  public static final String JSON_PROPERTY_DEVICE_LICENSE_ID = "device_license_id";
  @jakarta.annotation.Nullable
  private UUID deviceLicenseId;

  public static final String JSON_PROPERTY_CUSTOMER_NAME = "customer_name";
  private JsonNullable<String> customerName = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_HEARTBEAT_TYPE_ID = "heartbeat_type_id";
  private JsonNullable<UUID> heartbeatTypeId = JsonNullable.<UUID>undefined();

  public static final String JSON_PROPERTY_HEARTBEAT_TYPE = "heartbeat_type";
  private JsonNullable<HeartbeatTypeDto> heartbeatType = JsonNullable.<HeartbeatTypeDto>undefined();

  public static final String JSON_PROPERTY_USER_ID = "user_id";
  private JsonNullable<String> userId = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_LICENSE_USER = "license_user";
  private JsonNullable<LicenseUserDto> licenseUser = JsonNullable.<LicenseUserDto>undefined();

  public static final String JSON_PROPERTY_GROUP_ID = "group_id";
  private JsonNullable<String> groupId = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_VALUE = "value";
  @jakarta.annotation.Nullable
  private Integer value;

  public DeviceHeartbeatDto() { 
  }

  public DeviceHeartbeatDto id(@jakarta.annotation.Nullable UUID id) {
    this.id = JsonNullable.<UUID>of(id);
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public UUID getId() {
        return id.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<UUID> getId_JsonNullable() {
    return id;
  }
  
  @JsonProperty(JSON_PROPERTY_ID)
  public void setId_JsonNullable(JsonNullable<UUID> id) {
    this.id = id;
  }

  public void setId(@jakarta.annotation.Nullable UUID id) {
    this.id = JsonNullable.<UUID>of(id);
  }


  public DeviceHeartbeatDto softwareVersion(@jakarta.annotation.Nullable String softwareVersion) {
    this.softwareVersion = JsonNullable.<String>of(softwareVersion);
    return this;
  }

  /**
   * Get softwareVersion
   * @return softwareVersion
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getSoftwareVersion() {
        return softwareVersion.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_SOFTWARE_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getSoftwareVersion_JsonNullable() {
    return softwareVersion;
  }
  
  @JsonProperty(JSON_PROPERTY_SOFTWARE_VERSION)
  public void setSoftwareVersion_JsonNullable(JsonNullable<String> softwareVersion) {
    this.softwareVersion = softwareVersion;
  }

  public void setSoftwareVersion(@jakarta.annotation.Nullable String softwareVersion) {
    this.softwareVersion = JsonNullable.<String>of(softwareVersion);
  }


  public DeviceHeartbeatDto operatingSystem(@jakarta.annotation.Nullable String operatingSystem) {
    this.operatingSystem = JsonNullable.<String>of(operatingSystem);
    return this;
  }

  /**
   * Get operatingSystem
   * @return operatingSystem
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getOperatingSystem() {
        return operatingSystem.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_OPERATING_SYSTEM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getOperatingSystem_JsonNullable() {
    return operatingSystem;
  }
  
  @JsonProperty(JSON_PROPERTY_OPERATING_SYSTEM)
  public void setOperatingSystem_JsonNullable(JsonNullable<String> operatingSystem) {
    this.operatingSystem = operatingSystem;
  }

  public void setOperatingSystem(@jakarta.annotation.Nullable String operatingSystem) {
    this.operatingSystem = JsonNullable.<String>of(operatingSystem);
  }


  public DeviceHeartbeatDto ipAddress(@jakarta.annotation.Nullable String ipAddress) {
    this.ipAddress = JsonNullable.<String>of(ipAddress);
    return this;
  }

  /**
   * Get ipAddress
   * @return ipAddress
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getIpAddress() {
        return ipAddress.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_IP_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getIpAddress_JsonNullable() {
    return ipAddress;
  }
  
  @JsonProperty(JSON_PROPERTY_IP_ADDRESS)
  public void setIpAddress_JsonNullable(JsonNullable<String> ipAddress) {
    this.ipAddress = ipAddress;
  }

  public void setIpAddress(@jakarta.annotation.Nullable String ipAddress) {
    this.ipAddress = JsonNullable.<String>of(ipAddress);
  }


  public DeviceHeartbeatDto clientId(@jakarta.annotation.Nullable String clientId) {
    this.clientId = JsonNullable.<String>of(clientId);
    return this;
  }

  /**
   * Get clientId
   * @return clientId
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getClientId() {
        return clientId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_CLIENT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getClientId_JsonNullable() {
    return clientId;
  }
  
  @JsonProperty(JSON_PROPERTY_CLIENT_ID)
  public void setClientId_JsonNullable(JsonNullable<String> clientId) {
    this.clientId = clientId;
  }

  public void setClientId(@jakarta.annotation.Nullable String clientId) {
    this.clientId = JsonNullable.<String>of(clientId);
  }


  public DeviceHeartbeatDto country(@jakarta.annotation.Nullable String country) {
    this.country = JsonNullable.<String>of(country);
    return this;
  }

  /**
   * Get country
   * @return country
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getCountry() {
        return country.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_COUNTRY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getCountry_JsonNullable() {
    return country;
  }
  
  @JsonProperty(JSON_PROPERTY_COUNTRY)
  public void setCountry_JsonNullable(JsonNullable<String> country) {
    this.country = country;
  }

  public void setCountry(@jakarta.annotation.Nullable String country) {
    this.country = JsonNullable.<String>of(country);
  }


  public DeviceHeartbeatDto city(@jakarta.annotation.Nullable String city) {
    this.city = JsonNullable.<String>of(city);
    return this;
  }

  /**
   * Get city
   * @return city
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getCity() {
        return city.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_CITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getCity_JsonNullable() {
    return city;
  }
  
  @JsonProperty(JSON_PROPERTY_CITY)
  public void setCity_JsonNullable(JsonNullable<String> city) {
    this.city = city;
  }

  public void setCity(@jakarta.annotation.Nullable String city) {
    this.city = JsonNullable.<String>of(city);
  }


  public DeviceHeartbeatDto zip(@jakarta.annotation.Nullable String zip) {
    this.zip = JsonNullable.<String>of(zip);
    return this;
  }

  /**
   * Get zip
   * @return zip
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getZip() {
        return zip.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_ZIP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getZip_JsonNullable() {
    return zip;
  }
  
  @JsonProperty(JSON_PROPERTY_ZIP)
  public void setZip_JsonNullable(JsonNullable<String> zip) {
    this.zip = zip;
  }

  public void setZip(@jakarta.annotation.Nullable String zip) {
    this.zip = JsonNullable.<String>of(zip);
  }


  public DeviceHeartbeatDto latitude(@jakarta.annotation.Nullable String latitude) {
    this.latitude = JsonNullable.<String>of(latitude);
    return this;
  }

  /**
   * Get latitude
   * @return latitude
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getLatitude() {
        return latitude.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_LATITUDE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLatitude_JsonNullable() {
    return latitude;
  }
  
  @JsonProperty(JSON_PROPERTY_LATITUDE)
  public void setLatitude_JsonNullable(JsonNullable<String> latitude) {
    this.latitude = latitude;
  }

  public void setLatitude(@jakarta.annotation.Nullable String latitude) {
    this.latitude = JsonNullable.<String>of(latitude);
  }


  public DeviceHeartbeatDto longitude(@jakarta.annotation.Nullable String longitude) {
    this.longitude = JsonNullable.<String>of(longitude);
    return this;
  }

  /**
   * Get longitude
   * @return longitude
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getLongitude() {
        return longitude.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_LONGITUDE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLongitude_JsonNullable() {
    return longitude;
  }
  
  @JsonProperty(JSON_PROPERTY_LONGITUDE)
  public void setLongitude_JsonNullable(JsonNullable<String> longitude) {
    this.longitude = longitude;
  }

  public void setLongitude(@jakarta.annotation.Nullable String longitude) {
    this.longitude = JsonNullable.<String>of(longitude);
  }


  public DeviceHeartbeatDto createdDateUtc(@jakarta.annotation.Nullable OffsetDateTime createdDateUtc) {
    this.createdDateUtc = createdDateUtc;
    return this;
  }

  /**
   * Get createdDateUtc
   * @return createdDateUtc
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_DATE_UTC, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getCreatedDateUtc() {
    return createdDateUtc;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_DATE_UTC, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedDateUtc(@jakarta.annotation.Nullable OffsetDateTime createdDateUtc) {
    this.createdDateUtc = createdDateUtc;
  }


  public DeviceHeartbeatDto deviceLicenseAssignmentId(@jakarta.annotation.Nullable UUID deviceLicenseAssignmentId) {
    this.deviceLicenseAssignmentId = deviceLicenseAssignmentId;
    return this;
  }

  /**
   * Get deviceLicenseAssignmentId
   * @return deviceLicenseAssignmentId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DEVICE_LICENSE_ASSIGNMENT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getDeviceLicenseAssignmentId() {
    return deviceLicenseAssignmentId;
  }


  @JsonProperty(value = JSON_PROPERTY_DEVICE_LICENSE_ASSIGNMENT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeviceLicenseAssignmentId(@jakarta.annotation.Nullable UUID deviceLicenseAssignmentId) {
    this.deviceLicenseAssignmentId = deviceLicenseAssignmentId;
  }


  public DeviceHeartbeatDto deviceLicenseId(@jakarta.annotation.Nullable UUID deviceLicenseId) {
    this.deviceLicenseId = deviceLicenseId;
    return this;
  }

  /**
   * Get deviceLicenseId
   * @return deviceLicenseId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DEVICE_LICENSE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getDeviceLicenseId() {
    return deviceLicenseId;
  }


  @JsonProperty(value = JSON_PROPERTY_DEVICE_LICENSE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeviceLicenseId(@jakarta.annotation.Nullable UUID deviceLicenseId) {
    this.deviceLicenseId = deviceLicenseId;
  }


  public DeviceHeartbeatDto customerName(@jakarta.annotation.Nullable String customerName) {
    this.customerName = JsonNullable.<String>of(customerName);
    return this;
  }

  /**
   * Get customerName
   * @return customerName
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getCustomerName() {
        return customerName.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_CUSTOMER_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getCustomerName_JsonNullable() {
    return customerName;
  }
  
  @JsonProperty(JSON_PROPERTY_CUSTOMER_NAME)
  public void setCustomerName_JsonNullable(JsonNullable<String> customerName) {
    this.customerName = customerName;
  }

  public void setCustomerName(@jakarta.annotation.Nullable String customerName) {
    this.customerName = JsonNullable.<String>of(customerName);
  }


  public DeviceHeartbeatDto heartbeatTypeId(@jakarta.annotation.Nullable UUID heartbeatTypeId) {
    this.heartbeatTypeId = JsonNullable.<UUID>of(heartbeatTypeId);
    return this;
  }

  /**
   * Get heartbeatTypeId
   * @return heartbeatTypeId
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public UUID getHeartbeatTypeId() {
        return heartbeatTypeId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_HEARTBEAT_TYPE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<UUID> getHeartbeatTypeId_JsonNullable() {
    return heartbeatTypeId;
  }
  
  @JsonProperty(JSON_PROPERTY_HEARTBEAT_TYPE_ID)
  public void setHeartbeatTypeId_JsonNullable(JsonNullable<UUID> heartbeatTypeId) {
    this.heartbeatTypeId = heartbeatTypeId;
  }

  public void setHeartbeatTypeId(@jakarta.annotation.Nullable UUID heartbeatTypeId) {
    this.heartbeatTypeId = JsonNullable.<UUID>of(heartbeatTypeId);
  }


  public DeviceHeartbeatDto heartbeatType(@jakarta.annotation.Nullable HeartbeatTypeDto heartbeatType) {
    this.heartbeatType = JsonNullable.<HeartbeatTypeDto>of(heartbeatType);
    return this;
  }

  /**
   * Get heartbeatType
   * @return heartbeatType
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public HeartbeatTypeDto getHeartbeatType() {
        return heartbeatType.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_HEARTBEAT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<HeartbeatTypeDto> getHeartbeatType_JsonNullable() {
    return heartbeatType;
  }
  
  @JsonProperty(JSON_PROPERTY_HEARTBEAT_TYPE)
  public void setHeartbeatType_JsonNullable(JsonNullable<HeartbeatTypeDto> heartbeatType) {
    this.heartbeatType = heartbeatType;
  }

  public void setHeartbeatType(@jakarta.annotation.Nullable HeartbeatTypeDto heartbeatType) {
    this.heartbeatType = JsonNullable.<HeartbeatTypeDto>of(heartbeatType);
  }


  public DeviceHeartbeatDto userId(@jakarta.annotation.Nullable String userId) {
    this.userId = JsonNullable.<String>of(userId);
    return this;
  }

  /**
   * Get userId
   * @return userId
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getUserId() {
        return userId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_USER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getUserId_JsonNullable() {
    return userId;
  }
  
  @JsonProperty(JSON_PROPERTY_USER_ID)
  public void setUserId_JsonNullable(JsonNullable<String> userId) {
    this.userId = userId;
  }

  public void setUserId(@jakarta.annotation.Nullable String userId) {
    this.userId = JsonNullable.<String>of(userId);
  }


  public DeviceHeartbeatDto licenseUser(@jakarta.annotation.Nullable LicenseUserDto licenseUser) {
    this.licenseUser = JsonNullable.<LicenseUserDto>of(licenseUser);
    return this;
  }

  /**
   * Get licenseUser
   * @return licenseUser
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public LicenseUserDto getLicenseUser() {
        return licenseUser.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_LICENSE_USER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<LicenseUserDto> getLicenseUser_JsonNullable() {
    return licenseUser;
  }
  
  @JsonProperty(JSON_PROPERTY_LICENSE_USER)
  public void setLicenseUser_JsonNullable(JsonNullable<LicenseUserDto> licenseUser) {
    this.licenseUser = licenseUser;
  }

  public void setLicenseUser(@jakarta.annotation.Nullable LicenseUserDto licenseUser) {
    this.licenseUser = JsonNullable.<LicenseUserDto>of(licenseUser);
  }


  public DeviceHeartbeatDto groupId(@jakarta.annotation.Nullable String groupId) {
    this.groupId = JsonNullable.<String>of(groupId);
    return this;
  }

  /**
   * Get groupId
   * @return groupId
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getGroupId() {
        return groupId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_GROUP_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getGroupId_JsonNullable() {
    return groupId;
  }
  
  @JsonProperty(JSON_PROPERTY_GROUP_ID)
  public void setGroupId_JsonNullable(JsonNullable<String> groupId) {
    this.groupId = groupId;
  }

  public void setGroupId(@jakarta.annotation.Nullable String groupId) {
    this.groupId = JsonNullable.<String>of(groupId);
  }


  public DeviceHeartbeatDto value(@jakarta.annotation.Nullable Integer value) {
    this.value = value;
    return this;
  }

  /**
   * Get value
   * @return value
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getValue() {
    return value;
  }


  @JsonProperty(value = JSON_PROPERTY_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValue(@jakarta.annotation.Nullable Integer value) {
    this.value = value;
  }


  /**
   * Return true if this DeviceHeartbeatDto object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeviceHeartbeatDto deviceHeartbeatDto = (DeviceHeartbeatDto) o;
    return equalsNullable(this.id, deviceHeartbeatDto.id) &&
        equalsNullable(this.softwareVersion, deviceHeartbeatDto.softwareVersion) &&
        equalsNullable(this.operatingSystem, deviceHeartbeatDto.operatingSystem) &&
        equalsNullable(this.ipAddress, deviceHeartbeatDto.ipAddress) &&
        equalsNullable(this.clientId, deviceHeartbeatDto.clientId) &&
        equalsNullable(this.country, deviceHeartbeatDto.country) &&
        equalsNullable(this.city, deviceHeartbeatDto.city) &&
        equalsNullable(this.zip, deviceHeartbeatDto.zip) &&
        equalsNullable(this.latitude, deviceHeartbeatDto.latitude) &&
        equalsNullable(this.longitude, deviceHeartbeatDto.longitude) &&
        Objects.equals(this.createdDateUtc, deviceHeartbeatDto.createdDateUtc) &&
        Objects.equals(this.deviceLicenseAssignmentId, deviceHeartbeatDto.deviceLicenseAssignmentId) &&
        Objects.equals(this.deviceLicenseId, deviceHeartbeatDto.deviceLicenseId) &&
        equalsNullable(this.customerName, deviceHeartbeatDto.customerName) &&
        equalsNullable(this.heartbeatTypeId, deviceHeartbeatDto.heartbeatTypeId) &&
        equalsNullable(this.heartbeatType, deviceHeartbeatDto.heartbeatType) &&
        equalsNullable(this.userId, deviceHeartbeatDto.userId) &&
        equalsNullable(this.licenseUser, deviceHeartbeatDto.licenseUser) &&
        equalsNullable(this.groupId, deviceHeartbeatDto.groupId) &&
        Objects.equals(this.value, deviceHeartbeatDto.value);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(id), hashCodeNullable(softwareVersion), hashCodeNullable(operatingSystem), hashCodeNullable(ipAddress), hashCodeNullable(clientId), hashCodeNullable(country), hashCodeNullable(city), hashCodeNullable(zip), hashCodeNullable(latitude), hashCodeNullable(longitude), createdDateUtc, deviceLicenseAssignmentId, deviceLicenseId, hashCodeNullable(customerName), hashCodeNullable(heartbeatTypeId), hashCodeNullable(heartbeatType), hashCodeNullable(userId), hashCodeNullable(licenseUser), hashCodeNullable(groupId), value);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceHeartbeatDto {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    softwareVersion: ").append(toIndentedString(softwareVersion)).append("\n");
    sb.append("    operatingSystem: ").append(toIndentedString(operatingSystem)).append("\n");
    sb.append("    ipAddress: ").append(toIndentedString(ipAddress)).append("\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    zip: ").append(toIndentedString(zip)).append("\n");
    sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
    sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
    sb.append("    createdDateUtc: ").append(toIndentedString(createdDateUtc)).append("\n");
    sb.append("    deviceLicenseAssignmentId: ").append(toIndentedString(deviceLicenseAssignmentId)).append("\n");
    sb.append("    deviceLicenseId: ").append(toIndentedString(deviceLicenseId)).append("\n");
    sb.append("    customerName: ").append(toIndentedString(customerName)).append("\n");
    sb.append("    heartbeatTypeId: ").append(toIndentedString(heartbeatTypeId)).append("\n");
    sb.append("    heartbeatType: ").append(toIndentedString(heartbeatType)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    licenseUser: ").append(toIndentedString(licenseUser)).append("\n");
    sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `software_version` to the URL query string
    if (getSoftwareVersion() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssoftware_version%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSoftwareVersion()))));
    }

    // add `operating_system` to the URL query string
    if (getOperatingSystem() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%soperating_system%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOperatingSystem()))));
    }

    // add `ip_address` to the URL query string
    if (getIpAddress() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sip_address%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIpAddress()))));
    }

    // add `client_id` to the URL query string
    if (getClientId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sclient_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getClientId()))));
    }

    // add `country` to the URL query string
    if (getCountry() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scountry%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCountry()))));
    }

    // add `city` to the URL query string
    if (getCity() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scity%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCity()))));
    }

    // add `zip` to the URL query string
    if (getZip() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%szip%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getZip()))));
    }

    // add `latitude` to the URL query string
    if (getLatitude() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slatitude%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLatitude()))));
    }

    // add `longitude` to the URL query string
    if (getLongitude() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slongitude%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLongitude()))));
    }

    // add `created_date_utc` to the URL query string
    if (getCreatedDateUtc() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screated_date_utc%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedDateUtc()))));
    }

    // add `device_license_assignment_id` to the URL query string
    if (getDeviceLicenseAssignmentId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdevice_license_assignment_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDeviceLicenseAssignmentId()))));
    }

    // add `device_license_id` to the URL query string
    if (getDeviceLicenseId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdevice_license_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDeviceLicenseId()))));
    }

    // add `customer_name` to the URL query string
    if (getCustomerName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scustomer_name%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCustomerName()))));
    }

    // add `heartbeat_type_id` to the URL query string
    if (getHeartbeatTypeId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sheartbeat_type_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHeartbeatTypeId()))));
    }

    // add `heartbeat_type` to the URL query string
    if (getHeartbeatType() != null) {
      joiner.add(getHeartbeatType().toUrlQueryString(prefix + "heartbeat_type" + suffix));
    }

    // add `user_id` to the URL query string
    if (getUserId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%suser_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUserId()))));
    }

    // add `license_user` to the URL query string
    if (getLicenseUser() != null) {
      joiner.add(getLicenseUser().toUrlQueryString(prefix + "license_user" + suffix));
    }

    // add `group_id` to the URL query string
    if (getGroupId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sgroup_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getGroupId()))));
    }

    // add `value` to the URL query string
    if (getValue() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%svalue%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getValue()))));
    }

    return joiner.toString();
  }
}

