/*
 * SLASCONE API
 * Please visit our official [Documentation](https://support.slascone.com/hc/en-us/sections/360004685737-API) and/or our [GitHub repository](https://github.com/slascone/) and/or our [NuGet package](https://www.nuget.org/packages/Slascone.Client/). Always use Version 2 of this API (Version 1.3 is deprecated).
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.slascone.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.slascone.model.UsageHeartbeatValueDto;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.slascone.JSON;

/**
 * FullUsageHeartbeatDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class FullUsageHeartbeatDto {
  public static final String SERIALIZED_NAME_CLIENT_ID = "client_id";
  @SerializedName(SERIALIZED_NAME_CLIENT_ID)
  @javax.annotation.Nonnull
  private String clientId;

  public static final String SERIALIZED_NAME_USER_ID = "user_id";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  @javax.annotation.Nullable
  private String userId;

  public static final String SERIALIZED_NAME_USAGE_HEARTBEAT = "usage_heartbeat";
  @SerializedName(SERIALIZED_NAME_USAGE_HEARTBEAT)
  @javax.annotation.Nonnull
  private List<UsageHeartbeatValueDto> usageHeartbeat = new ArrayList<>();

  public static final String SERIALIZED_NAME_TOKEN_KEY = "token_key";
  @SerializedName(SERIALIZED_NAME_TOKEN_KEY)
  @javax.annotation.Nullable
  private UUID tokenKey;

  public FullUsageHeartbeatDto() {
  }

  public FullUsageHeartbeatDto clientId(@javax.annotation.Nonnull String clientId) {
    this.clientId = clientId;
    return this;
  }

  /**
   * Get clientId
   * @return clientId
   */
  @javax.annotation.Nonnull
  public String getClientId() {
    return clientId;
  }

  public void setClientId(@javax.annotation.Nonnull String clientId) {
    this.clientId = clientId;
  }


  public FullUsageHeartbeatDto userId(@javax.annotation.Nullable String userId) {
    this.userId = userId;
    return this;
  }

  /**
   * Get userId
   * @return userId
   */
  @javax.annotation.Nullable
  public String getUserId() {
    return userId;
  }

  public void setUserId(@javax.annotation.Nullable String userId) {
    this.userId = userId;
  }


  public FullUsageHeartbeatDto usageHeartbeat(@javax.annotation.Nonnull List<UsageHeartbeatValueDto> usageHeartbeat) {
    this.usageHeartbeat = usageHeartbeat;
    return this;
  }

  public FullUsageHeartbeatDto addUsageHeartbeatItem(UsageHeartbeatValueDto usageHeartbeatItem) {
    if (this.usageHeartbeat == null) {
      this.usageHeartbeat = new ArrayList<>();
    }
    this.usageHeartbeat.add(usageHeartbeatItem);
    return this;
  }

  /**
   * Get usageHeartbeat
   * @return usageHeartbeat
   */
  @javax.annotation.Nonnull
  public List<UsageHeartbeatValueDto> getUsageHeartbeat() {
    return usageHeartbeat;
  }

  public void setUsageHeartbeat(@javax.annotation.Nonnull List<UsageHeartbeatValueDto> usageHeartbeat) {
    this.usageHeartbeat = usageHeartbeat;
  }


  public FullUsageHeartbeatDto tokenKey(@javax.annotation.Nullable UUID tokenKey) {
    this.tokenKey = tokenKey;
    return this;
  }

  /**
   * Get tokenKey
   * @return tokenKey
   */
  @javax.annotation.Nullable
  public UUID getTokenKey() {
    return tokenKey;
  }

  public void setTokenKey(@javax.annotation.Nullable UUID tokenKey) {
    this.tokenKey = tokenKey;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FullUsageHeartbeatDto fullUsageHeartbeatDto = (FullUsageHeartbeatDto) o;
    return Objects.equals(this.clientId, fullUsageHeartbeatDto.clientId) &&
        Objects.equals(this.userId, fullUsageHeartbeatDto.userId) &&
        Objects.equals(this.usageHeartbeat, fullUsageHeartbeatDto.usageHeartbeat) &&
        Objects.equals(this.tokenKey, fullUsageHeartbeatDto.tokenKey);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(clientId, userId, usageHeartbeat, tokenKey);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FullUsageHeartbeatDto {\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    usageHeartbeat: ").append(toIndentedString(usageHeartbeat)).append("\n");
    sb.append("    tokenKey: ").append(toIndentedString(tokenKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("client_id", "user_id", "usage_heartbeat", "token_key"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("client_id", "usage_heartbeat"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to FullUsageHeartbeatDto
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!FullUsageHeartbeatDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException("The required field(s) %s in FullUsageHeartbeatDto is not found in the empty JSON string".formatted(FullUsageHeartbeatDto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!FullUsageHeartbeatDto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException("The field `%s` in the JSON string is not defined in the `FullUsageHeartbeatDto` properties. JSON: %s".formatted(entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : FullUsageHeartbeatDto.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException("The required field `%s` is not found in the JSON string: %s".formatted(requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("client_id").isJsonPrimitive()) {
        throw new IllegalArgumentException("Expected the field `client_id` to be a primitive type in the JSON string but got `%s`".formatted(jsonObj.get("client_id").toString()));
      }
      if ((jsonObj.get("user_id") != null && !jsonObj.get("user_id").isJsonNull()) && !jsonObj.get("user_id").isJsonPrimitive()) {
        throw new IllegalArgumentException("Expected the field `user_id` to be a primitive type in the JSON string but got `%s`".formatted(jsonObj.get("user_id").toString()));
      }
      // ensure the json data is an array
      if (!jsonObj.get("usage_heartbeat").isJsonArray()) {
        throw new IllegalArgumentException("Expected the field `usage_heartbeat` to be an array in the JSON string but got `%s`".formatted(jsonObj.get("usage_heartbeat").toString()));
      }

      JsonArray jsonArrayusageHeartbeat = jsonObj.getAsJsonArray("usage_heartbeat");
      // validate the required field `usage_heartbeat` (array)
      for (int i = 0; i < jsonArrayusageHeartbeat.size(); i++) {
        UsageHeartbeatValueDto.validateJsonElement(jsonArrayusageHeartbeat.get(i));
      };
      if ((jsonObj.get("token_key") != null && !jsonObj.get("token_key").isJsonNull()) && !jsonObj.get("token_key").isJsonPrimitive()) {
        throw new IllegalArgumentException("Expected the field `token_key` to be a primitive type in the JSON string but got `%s`".formatted(jsonObj.get("token_key").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!FullUsageHeartbeatDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'FullUsageHeartbeatDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<FullUsageHeartbeatDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(FullUsageHeartbeatDto.class));

       return (TypeAdapter<T>) new TypeAdapter<FullUsageHeartbeatDto>() {
           @Override
           public void write(JsonWriter out, FullUsageHeartbeatDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public FullUsageHeartbeatDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of FullUsageHeartbeatDto given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of FullUsageHeartbeatDto
   * @throws IOException if the JSON string is invalid with respect to FullUsageHeartbeatDto
   */
  public static FullUsageHeartbeatDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FullUsageHeartbeatDto.class);
  }

  /**
   * Convert an instance of FullUsageHeartbeatDto to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

