/*
 * SLASCONE API
 * Please visit our official [Documentation](https://support.slascone.com/hc/en-us/sections/360004685737-API) and/or our [GitHub repository](https://github.com/slascone/) and/or our [NuGet package](https://www.nuget.org/packages/Slascone.Client/). Always use Version 2 of this API (Version 1.3 is deprecated).
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.slascone.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.slascone.ApiClient;
/**
 * GetLicensesByLicenseKeyDto
 */
@JsonPropertyOrder({
  GetLicensesByLicenseKeyDto.JSON_PROPERTY_PRODUCT_ID,
  GetLicensesByLicenseKeyDto.JSON_PROPERTY_LICENSE_KEY
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0-SNAPSHOT")
public class GetLicensesByLicenseKeyDto {
  public static final String JSON_PROPERTY_PRODUCT_ID = "product_id";
  @jakarta.annotation.Nullable
  private UUID productId;

  public static final String JSON_PROPERTY_LICENSE_KEY = "license_key";
  private JsonNullable<String> licenseKey = JsonNullable.<String>undefined();

  public GetLicensesByLicenseKeyDto() { 
  }

  public GetLicensesByLicenseKeyDto productId(@jakarta.annotation.Nullable UUID productId) {
    this.productId = productId;
    return this;
  }

  /**
   * Get productId
   * @return productId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRODUCT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getProductId() {
    return productId;
  }


  @JsonProperty(value = JSON_PROPERTY_PRODUCT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProductId(@jakarta.annotation.Nullable UUID productId) {
    this.productId = productId;
  }


  public GetLicensesByLicenseKeyDto licenseKey(@jakarta.annotation.Nullable String licenseKey) {
    this.licenseKey = JsonNullable.<String>of(licenseKey);
    return this;
  }

  /**
   * Get licenseKey
   * @return licenseKey
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getLicenseKey() {
        return licenseKey.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_LICENSE_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLicenseKey_JsonNullable() {
    return licenseKey;
  }
  
  @JsonProperty(JSON_PROPERTY_LICENSE_KEY)
  public void setLicenseKey_JsonNullable(JsonNullable<String> licenseKey) {
    this.licenseKey = licenseKey;
  }

  public void setLicenseKey(@jakarta.annotation.Nullable String licenseKey) {
    this.licenseKey = JsonNullable.<String>of(licenseKey);
  }


  /**
   * Return true if this GetLicensesByLicenseKeyDto object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetLicensesByLicenseKeyDto getLicensesByLicenseKeyDto = (GetLicensesByLicenseKeyDto) o;
    return Objects.equals(this.productId, getLicensesByLicenseKeyDto.productId) &&
        equalsNullable(this.licenseKey, getLicensesByLicenseKeyDto.licenseKey);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(productId, hashCodeNullable(licenseKey));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetLicensesByLicenseKeyDto {\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    licenseKey: ").append(toIndentedString(licenseKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `product_id` to the URL query string
    if (getProductId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sproduct_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProductId()))));
    }

    // add `license_key` to the URL query string
    if (getLicenseKey() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slicense_key%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLicenseKey()))));
    }

    return joiner.toString();
  }
}

