/*
 * SLASCONE API
 * Please visit our official [Documentation](https://support.slascone.com/hc/en-us/sections/360004685737-API) and/or our [GitHub repository](https://github.com/slascone/) and/or our [NuGet package](https://www.nuget.org/packages/Slascone.Client/). Always use Version 2 of this API (Version 1.3 is deprecated).
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.slascone.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.slascone.model.LicenseImportConstrainedVariableDto;
import com.slascone.model.LicenseImportLimitationDto;
import com.slascone.model.LicenseImportVariableDto;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.slascone.ApiClient;
/**
 * LicenseImportByDetailsPutDto
 */
@JsonPropertyOrder({
  LicenseImportByDetailsPutDto.JSON_PROPERTY_LICENSE_KEY,
  LicenseImportByDetailsPutDto.JSON_PROPERTY_PRODUCT_ID,
  LicenseImportByDetailsPutDto.JSON_PROPERTY_CUSTOMER_NUMBER,
  LicenseImportByDetailsPutDto.JSON_PROPERTY_TEMPLATE,
  LicenseImportByDetailsPutDto.JSON_PROPERTY_LEGACY_LICENSE_KEY,
  LicenseImportByDetailsPutDto.JSON_PROPERTY_NAME,
  LicenseImportByDetailsPutDto.JSON_PROPERTY_DESCRIPTION,
  LicenseImportByDetailsPutDto.JSON_PROPERTY_TOKEN_LIMIT,
  LicenseImportByDetailsPutDto.JSON_PROPERTY_GOODWILL_TOKEN_LIMIT,
  LicenseImportByDetailsPutDto.JSON_PROPERTY_FLOATING_TOKEN_LIMIT,
  LicenseImportByDetailsPutDto.JSON_PROPERTY_USER_LIMIT,
  LicenseImportByDetailsPutDto.JSON_PROPERTY_START_DATE,
  LicenseImportByDetailsPutDto.JSON_PROPERTY_EXPIRATION_DATE,
  LicenseImportByDetailsPutDto.JSON_PROPERTY_LICENSE_TYPE,
  LicenseImportByDetailsPutDto.JSON_PROPERTY_SOFTWARE_RELEASE_LIMITATION,
  LicenseImportByDetailsPutDto.JSON_PROPERTY_LICENSE_FEATURES,
  LicenseImportByDetailsPutDto.JSON_PROPERTY_LICENSE_LIMITATIONS,
  LicenseImportByDetailsPutDto.JSON_PROPERTY_LICENSE_VARIABLES,
  LicenseImportByDetailsPutDto.JSON_PROPERTY_LICENSE_CONSTRAINED_VARIABLES,
  LicenseImportByDetailsPutDto.JSON_PROPERTY_TAGS,
  LicenseImportByDetailsPutDto.JSON_PROPERTY_IS_ACTIVE,
  LicenseImportByDetailsPutDto.JSON_PROPERTY_RESUME_ON_ERROR
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0-SNAPSHOT")
public class LicenseImportByDetailsPutDto {
  public static final String JSON_PROPERTY_LICENSE_KEY = "license_key";
  @jakarta.annotation.Nonnull
  private String licenseKey;

  public static final String JSON_PROPERTY_PRODUCT_ID = "product_id";
  @jakarta.annotation.Nonnull
  private UUID productId;

  public static final String JSON_PROPERTY_CUSTOMER_NUMBER = "customer_number";
  @jakarta.annotation.Nonnull
  private String customerNumber;

  public static final String JSON_PROPERTY_TEMPLATE = "template";
  @jakarta.annotation.Nonnull
  private String template;

  public static final String JSON_PROPERTY_LEGACY_LICENSE_KEY = "legacy_license_key";
  private JsonNullable<String> legacyLicenseKey = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_NAME = "name";
  private JsonNullable<String> name = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private JsonNullable<String> description = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_TOKEN_LIMIT = "token_limit";
  private JsonNullable<Integer> tokenLimit = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_GOODWILL_TOKEN_LIMIT = "goodwill_token_limit";
  private JsonNullable<Integer> goodwillTokenLimit = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_FLOATING_TOKEN_LIMIT = "floating_token_limit";
  private JsonNullable<Integer> floatingTokenLimit = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_USER_LIMIT = "user_limit";
  private JsonNullable<Integer> userLimit = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_START_DATE = "start_date";
  private JsonNullable<String> startDate = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_EXPIRATION_DATE = "expiration_date";
  private JsonNullable<String> expirationDate = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_LICENSE_TYPE = "license_type";
  private JsonNullable<String> licenseType = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_SOFTWARE_RELEASE_LIMITATION = "software_release_limitation";
  private JsonNullable<String> softwareReleaseLimitation = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_LICENSE_FEATURES = "license_features";
  private JsonNullable<List<String>> licenseFeatures = JsonNullable.<List<String>>undefined();

  public static final String JSON_PROPERTY_LICENSE_LIMITATIONS = "license_limitations";
  private JsonNullable<List<LicenseImportLimitationDto>> licenseLimitations = JsonNullable.<List<LicenseImportLimitationDto>>undefined();

  public static final String JSON_PROPERTY_LICENSE_VARIABLES = "license_variables";
  private JsonNullable<List<LicenseImportVariableDto>> licenseVariables = JsonNullable.<List<LicenseImportVariableDto>>undefined();

  public static final String JSON_PROPERTY_LICENSE_CONSTRAINED_VARIABLES = "license_constrained_variables";
  private JsonNullable<List<LicenseImportConstrainedVariableDto>> licenseConstrainedVariables = JsonNullable.<List<LicenseImportConstrainedVariableDto>>undefined();

  public static final String JSON_PROPERTY_TAGS = "tags";
  private JsonNullable<List<String>> tags = JsonNullable.<List<String>>undefined();

  public static final String JSON_PROPERTY_IS_ACTIVE = "is_active";
  private JsonNullable<Boolean> isActive = JsonNullable.<Boolean>of(true);

  public static final String JSON_PROPERTY_RESUME_ON_ERROR = "resume_on_error";
  @jakarta.annotation.Nullable
  private Boolean resumeOnError = false;

  public LicenseImportByDetailsPutDto() { 
  }

  public LicenseImportByDetailsPutDto licenseKey(@jakarta.annotation.Nonnull String licenseKey) {
    this.licenseKey = licenseKey;
    return this;
  }

  /**
   * Get licenseKey
   * @return licenseKey
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LICENSE_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getLicenseKey() {
    return licenseKey;
  }


  @JsonProperty(value = JSON_PROPERTY_LICENSE_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLicenseKey(@jakarta.annotation.Nonnull String licenseKey) {
    this.licenseKey = licenseKey;
  }


  public LicenseImportByDetailsPutDto productId(@jakarta.annotation.Nonnull UUID productId) {
    this.productId = productId;
    return this;
  }

  /**
   * Get productId
   * @return productId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PRODUCT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getProductId() {
    return productId;
  }


  @JsonProperty(value = JSON_PROPERTY_PRODUCT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProductId(@jakarta.annotation.Nonnull UUID productId) {
    this.productId = productId;
  }


  public LicenseImportByDetailsPutDto customerNumber(@jakarta.annotation.Nonnull String customerNumber) {
    this.customerNumber = customerNumber;
    return this;
  }

  /**
   * Get customerNumber
   * @return customerNumber
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CUSTOMER_NUMBER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCustomerNumber() {
    return customerNumber;
  }


  @JsonProperty(value = JSON_PROPERTY_CUSTOMER_NUMBER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCustomerNumber(@jakarta.annotation.Nonnull String customerNumber) {
    this.customerNumber = customerNumber;
  }


  public LicenseImportByDetailsPutDto template(@jakarta.annotation.Nonnull String template) {
    this.template = template;
    return this;
  }

  /**
   * Get template
   * @return template
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TEMPLATE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getTemplate() {
    return template;
  }


  @JsonProperty(value = JSON_PROPERTY_TEMPLATE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTemplate(@jakarta.annotation.Nonnull String template) {
    this.template = template;
  }


  public LicenseImportByDetailsPutDto legacyLicenseKey(@jakarta.annotation.Nullable String legacyLicenseKey) {
    this.legacyLicenseKey = JsonNullable.<String>of(legacyLicenseKey);
    return this;
  }

  /**
   * Get legacyLicenseKey
   * @return legacyLicenseKey
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getLegacyLicenseKey() {
        return legacyLicenseKey.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_LEGACY_LICENSE_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLegacyLicenseKey_JsonNullable() {
    return legacyLicenseKey;
  }
  
  @JsonProperty(JSON_PROPERTY_LEGACY_LICENSE_KEY)
  public void setLegacyLicenseKey_JsonNullable(JsonNullable<String> legacyLicenseKey) {
    this.legacyLicenseKey = legacyLicenseKey;
  }

  public void setLegacyLicenseKey(@jakarta.annotation.Nullable String legacyLicenseKey) {
    this.legacyLicenseKey = JsonNullable.<String>of(legacyLicenseKey);
  }


  public LicenseImportByDetailsPutDto name(@jakarta.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getName() {
        return name.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getName_JsonNullable() {
    return name;
  }
  
  @JsonProperty(JSON_PROPERTY_NAME)
  public void setName_JsonNullable(JsonNullable<String> name) {
    this.name = name;
  }

  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
  }


  public LicenseImportByDetailsPutDto description(@jakarta.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getDescription() {
        return description.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getDescription_JsonNullable() {
    return description;
  }
  
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  public void setDescription_JsonNullable(JsonNullable<String> description) {
    this.description = description;
  }

  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
  }


  public LicenseImportByDetailsPutDto tokenLimit(@jakarta.annotation.Nullable Integer tokenLimit) {
    this.tokenLimit = JsonNullable.<Integer>of(tokenLimit);
    return this;
  }

  /**
   * Get tokenLimit
   * @return tokenLimit
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public Integer getTokenLimit() {
        return tokenLimit.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_TOKEN_LIMIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getTokenLimit_JsonNullable() {
    return tokenLimit;
  }
  
  @JsonProperty(JSON_PROPERTY_TOKEN_LIMIT)
  public void setTokenLimit_JsonNullable(JsonNullable<Integer> tokenLimit) {
    this.tokenLimit = tokenLimit;
  }

  public void setTokenLimit(@jakarta.annotation.Nullable Integer tokenLimit) {
    this.tokenLimit = JsonNullable.<Integer>of(tokenLimit);
  }


  public LicenseImportByDetailsPutDto goodwillTokenLimit(@jakarta.annotation.Nullable Integer goodwillTokenLimit) {
    this.goodwillTokenLimit = JsonNullable.<Integer>of(goodwillTokenLimit);
    return this;
  }

  /**
   * Get goodwillTokenLimit
   * @return goodwillTokenLimit
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public Integer getGoodwillTokenLimit() {
        return goodwillTokenLimit.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_GOODWILL_TOKEN_LIMIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getGoodwillTokenLimit_JsonNullable() {
    return goodwillTokenLimit;
  }
  
  @JsonProperty(JSON_PROPERTY_GOODWILL_TOKEN_LIMIT)
  public void setGoodwillTokenLimit_JsonNullable(JsonNullable<Integer> goodwillTokenLimit) {
    this.goodwillTokenLimit = goodwillTokenLimit;
  }

  public void setGoodwillTokenLimit(@jakarta.annotation.Nullable Integer goodwillTokenLimit) {
    this.goodwillTokenLimit = JsonNullable.<Integer>of(goodwillTokenLimit);
  }


  public LicenseImportByDetailsPutDto floatingTokenLimit(@jakarta.annotation.Nullable Integer floatingTokenLimit) {
    this.floatingTokenLimit = JsonNullable.<Integer>of(floatingTokenLimit);
    return this;
  }

  /**
   * Get floatingTokenLimit
   * @return floatingTokenLimit
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public Integer getFloatingTokenLimit() {
        return floatingTokenLimit.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_FLOATING_TOKEN_LIMIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getFloatingTokenLimit_JsonNullable() {
    return floatingTokenLimit;
  }
  
  @JsonProperty(JSON_PROPERTY_FLOATING_TOKEN_LIMIT)
  public void setFloatingTokenLimit_JsonNullable(JsonNullable<Integer> floatingTokenLimit) {
    this.floatingTokenLimit = floatingTokenLimit;
  }

  public void setFloatingTokenLimit(@jakarta.annotation.Nullable Integer floatingTokenLimit) {
    this.floatingTokenLimit = JsonNullable.<Integer>of(floatingTokenLimit);
  }


  public LicenseImportByDetailsPutDto userLimit(@jakarta.annotation.Nullable Integer userLimit) {
    this.userLimit = JsonNullable.<Integer>of(userLimit);
    return this;
  }

  /**
   * Get userLimit
   * @return userLimit
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public Integer getUserLimit() {
        return userLimit.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_USER_LIMIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getUserLimit_JsonNullable() {
    return userLimit;
  }
  
  @JsonProperty(JSON_PROPERTY_USER_LIMIT)
  public void setUserLimit_JsonNullable(JsonNullable<Integer> userLimit) {
    this.userLimit = userLimit;
  }

  public void setUserLimit(@jakarta.annotation.Nullable Integer userLimit) {
    this.userLimit = JsonNullable.<Integer>of(userLimit);
  }


  public LicenseImportByDetailsPutDto startDate(@jakarta.annotation.Nullable String startDate) {
    this.startDate = JsonNullable.<String>of(startDate);
    return this;
  }

  /**
   * Get startDate
   * @return startDate
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getStartDate() {
        return startDate.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_START_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getStartDate_JsonNullable() {
    return startDate;
  }
  
  @JsonProperty(JSON_PROPERTY_START_DATE)
  public void setStartDate_JsonNullable(JsonNullable<String> startDate) {
    this.startDate = startDate;
  }

  public void setStartDate(@jakarta.annotation.Nullable String startDate) {
    this.startDate = JsonNullable.<String>of(startDate);
  }


  public LicenseImportByDetailsPutDto expirationDate(@jakarta.annotation.Nullable String expirationDate) {
    this.expirationDate = JsonNullable.<String>of(expirationDate);
    return this;
  }

  /**
   * Get expirationDate
   * @return expirationDate
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getExpirationDate() {
        return expirationDate.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_EXPIRATION_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getExpirationDate_JsonNullable() {
    return expirationDate;
  }
  
  @JsonProperty(JSON_PROPERTY_EXPIRATION_DATE)
  public void setExpirationDate_JsonNullable(JsonNullable<String> expirationDate) {
    this.expirationDate = expirationDate;
  }

  public void setExpirationDate(@jakarta.annotation.Nullable String expirationDate) {
    this.expirationDate = JsonNullable.<String>of(expirationDate);
  }


  public LicenseImportByDetailsPutDto licenseType(@jakarta.annotation.Nullable String licenseType) {
    this.licenseType = JsonNullable.<String>of(licenseType);
    return this;
  }

  /**
   * Get licenseType
   * @return licenseType
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getLicenseType() {
        return licenseType.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_LICENSE_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLicenseType_JsonNullable() {
    return licenseType;
  }
  
  @JsonProperty(JSON_PROPERTY_LICENSE_TYPE)
  public void setLicenseType_JsonNullable(JsonNullable<String> licenseType) {
    this.licenseType = licenseType;
  }

  public void setLicenseType(@jakarta.annotation.Nullable String licenseType) {
    this.licenseType = JsonNullable.<String>of(licenseType);
  }


  public LicenseImportByDetailsPutDto softwareReleaseLimitation(@jakarta.annotation.Nullable String softwareReleaseLimitation) {
    this.softwareReleaseLimitation = JsonNullable.<String>of(softwareReleaseLimitation);
    return this;
  }

  /**
   * Get softwareReleaseLimitation
   * @return softwareReleaseLimitation
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getSoftwareReleaseLimitation() {
        return softwareReleaseLimitation.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_SOFTWARE_RELEASE_LIMITATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getSoftwareReleaseLimitation_JsonNullable() {
    return softwareReleaseLimitation;
  }
  
  @JsonProperty(JSON_PROPERTY_SOFTWARE_RELEASE_LIMITATION)
  public void setSoftwareReleaseLimitation_JsonNullable(JsonNullable<String> softwareReleaseLimitation) {
    this.softwareReleaseLimitation = softwareReleaseLimitation;
  }

  public void setSoftwareReleaseLimitation(@jakarta.annotation.Nullable String softwareReleaseLimitation) {
    this.softwareReleaseLimitation = JsonNullable.<String>of(softwareReleaseLimitation);
  }


  public LicenseImportByDetailsPutDto licenseFeatures(@jakarta.annotation.Nullable List<String> licenseFeatures) {
    this.licenseFeatures = JsonNullable.<List<String>>of(licenseFeatures);
    return this;
  }

  public LicenseImportByDetailsPutDto addLicenseFeaturesItem(String licenseFeaturesItem) {
    if (this.licenseFeatures == null || !this.licenseFeatures.isPresent()) {
      this.licenseFeatures = JsonNullable.<List<String>>of(new ArrayList<>());
    }
    try {
      this.licenseFeatures.get().add(licenseFeaturesItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get licenseFeatures
   * @return licenseFeatures
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public List<String> getLicenseFeatures() {
        return licenseFeatures.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_LICENSE_FEATURES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<String>> getLicenseFeatures_JsonNullable() {
    return licenseFeatures;
  }
  
  @JsonProperty(JSON_PROPERTY_LICENSE_FEATURES)
  public void setLicenseFeatures_JsonNullable(JsonNullable<List<String>> licenseFeatures) {
    this.licenseFeatures = licenseFeatures;
  }

  public void setLicenseFeatures(@jakarta.annotation.Nullable List<String> licenseFeatures) {
    this.licenseFeatures = JsonNullable.<List<String>>of(licenseFeatures);
  }


  public LicenseImportByDetailsPutDto licenseLimitations(@jakarta.annotation.Nullable List<LicenseImportLimitationDto> licenseLimitations) {
    this.licenseLimitations = JsonNullable.<List<LicenseImportLimitationDto>>of(licenseLimitations);
    return this;
  }

  public LicenseImportByDetailsPutDto addLicenseLimitationsItem(LicenseImportLimitationDto licenseLimitationsItem) {
    if (this.licenseLimitations == null || !this.licenseLimitations.isPresent()) {
      this.licenseLimitations = JsonNullable.<List<LicenseImportLimitationDto>>of(new ArrayList<>());
    }
    try {
      this.licenseLimitations.get().add(licenseLimitationsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get licenseLimitations
   * @return licenseLimitations
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public List<LicenseImportLimitationDto> getLicenseLimitations() {
        return licenseLimitations.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_LICENSE_LIMITATIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<LicenseImportLimitationDto>> getLicenseLimitations_JsonNullable() {
    return licenseLimitations;
  }
  
  @JsonProperty(JSON_PROPERTY_LICENSE_LIMITATIONS)
  public void setLicenseLimitations_JsonNullable(JsonNullable<List<LicenseImportLimitationDto>> licenseLimitations) {
    this.licenseLimitations = licenseLimitations;
  }

  public void setLicenseLimitations(@jakarta.annotation.Nullable List<LicenseImportLimitationDto> licenseLimitations) {
    this.licenseLimitations = JsonNullable.<List<LicenseImportLimitationDto>>of(licenseLimitations);
  }


  public LicenseImportByDetailsPutDto licenseVariables(@jakarta.annotation.Nullable List<LicenseImportVariableDto> licenseVariables) {
    this.licenseVariables = JsonNullable.<List<LicenseImportVariableDto>>of(licenseVariables);
    return this;
  }

  public LicenseImportByDetailsPutDto addLicenseVariablesItem(LicenseImportVariableDto licenseVariablesItem) {
    if (this.licenseVariables == null || !this.licenseVariables.isPresent()) {
      this.licenseVariables = JsonNullable.<List<LicenseImportVariableDto>>of(new ArrayList<>());
    }
    try {
      this.licenseVariables.get().add(licenseVariablesItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get licenseVariables
   * @return licenseVariables
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public List<LicenseImportVariableDto> getLicenseVariables() {
        return licenseVariables.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_LICENSE_VARIABLES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<LicenseImportVariableDto>> getLicenseVariables_JsonNullable() {
    return licenseVariables;
  }
  
  @JsonProperty(JSON_PROPERTY_LICENSE_VARIABLES)
  public void setLicenseVariables_JsonNullable(JsonNullable<List<LicenseImportVariableDto>> licenseVariables) {
    this.licenseVariables = licenseVariables;
  }

  public void setLicenseVariables(@jakarta.annotation.Nullable List<LicenseImportVariableDto> licenseVariables) {
    this.licenseVariables = JsonNullable.<List<LicenseImportVariableDto>>of(licenseVariables);
  }


  public LicenseImportByDetailsPutDto licenseConstrainedVariables(@jakarta.annotation.Nullable List<LicenseImportConstrainedVariableDto> licenseConstrainedVariables) {
    this.licenseConstrainedVariables = JsonNullable.<List<LicenseImportConstrainedVariableDto>>of(licenseConstrainedVariables);
    return this;
  }

  public LicenseImportByDetailsPutDto addLicenseConstrainedVariablesItem(LicenseImportConstrainedVariableDto licenseConstrainedVariablesItem) {
    if (this.licenseConstrainedVariables == null || !this.licenseConstrainedVariables.isPresent()) {
      this.licenseConstrainedVariables = JsonNullable.<List<LicenseImportConstrainedVariableDto>>of(new ArrayList<>());
    }
    try {
      this.licenseConstrainedVariables.get().add(licenseConstrainedVariablesItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get licenseConstrainedVariables
   * @return licenseConstrainedVariables
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public List<LicenseImportConstrainedVariableDto> getLicenseConstrainedVariables() {
        return licenseConstrainedVariables.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_LICENSE_CONSTRAINED_VARIABLES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<LicenseImportConstrainedVariableDto>> getLicenseConstrainedVariables_JsonNullable() {
    return licenseConstrainedVariables;
  }
  
  @JsonProperty(JSON_PROPERTY_LICENSE_CONSTRAINED_VARIABLES)
  public void setLicenseConstrainedVariables_JsonNullable(JsonNullable<List<LicenseImportConstrainedVariableDto>> licenseConstrainedVariables) {
    this.licenseConstrainedVariables = licenseConstrainedVariables;
  }

  public void setLicenseConstrainedVariables(@jakarta.annotation.Nullable List<LicenseImportConstrainedVariableDto> licenseConstrainedVariables) {
    this.licenseConstrainedVariables = JsonNullable.<List<LicenseImportConstrainedVariableDto>>of(licenseConstrainedVariables);
  }


  public LicenseImportByDetailsPutDto tags(@jakarta.annotation.Nullable List<String> tags) {
    this.tags = JsonNullable.<List<String>>of(tags);
    return this;
  }

  public LicenseImportByDetailsPutDto addTagsItem(String tagsItem) {
    if (this.tags == null || !this.tags.isPresent()) {
      this.tags = JsonNullable.<List<String>>of(new ArrayList<>());
    }
    try {
      this.tags.get().add(tagsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public List<String> getTags() {
        return tags.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<String>> getTags_JsonNullable() {
    return tags;
  }
  
  @JsonProperty(JSON_PROPERTY_TAGS)
  public void setTags_JsonNullable(JsonNullable<List<String>> tags) {
    this.tags = tags;
  }

  public void setTags(@jakarta.annotation.Nullable List<String> tags) {
    this.tags = JsonNullable.<List<String>>of(tags);
  }


  public LicenseImportByDetailsPutDto isActive(@jakarta.annotation.Nullable Boolean isActive) {
    this.isActive = JsonNullable.<Boolean>of(isActive);
    return this;
  }

  /**
   * Get isActive
   * @return isActive
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public Boolean getIsActive() {
        return isActive.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_IS_ACTIVE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getIsActive_JsonNullable() {
    return isActive;
  }
  
  @JsonProperty(JSON_PROPERTY_IS_ACTIVE)
  public void setIsActive_JsonNullable(JsonNullable<Boolean> isActive) {
    this.isActive = isActive;
  }

  public void setIsActive(@jakarta.annotation.Nullable Boolean isActive) {
    this.isActive = JsonNullable.<Boolean>of(isActive);
  }


  public LicenseImportByDetailsPutDto resumeOnError(@jakarta.annotation.Nullable Boolean resumeOnError) {
    this.resumeOnError = resumeOnError;
    return this;
  }

  /**
   * Get resumeOnError
   * @return resumeOnError
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RESUME_ON_ERROR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getResumeOnError() {
    return resumeOnError;
  }


  @JsonProperty(value = JSON_PROPERTY_RESUME_ON_ERROR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResumeOnError(@jakarta.annotation.Nullable Boolean resumeOnError) {
    this.resumeOnError = resumeOnError;
  }


  /**
   * Return true if this LicenseImportByDetailsPutDto object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LicenseImportByDetailsPutDto licenseImportByDetailsPutDto = (LicenseImportByDetailsPutDto) o;
    return Objects.equals(this.licenseKey, licenseImportByDetailsPutDto.licenseKey) &&
        Objects.equals(this.productId, licenseImportByDetailsPutDto.productId) &&
        Objects.equals(this.customerNumber, licenseImportByDetailsPutDto.customerNumber) &&
        Objects.equals(this.template, licenseImportByDetailsPutDto.template) &&
        equalsNullable(this.legacyLicenseKey, licenseImportByDetailsPutDto.legacyLicenseKey) &&
        equalsNullable(this.name, licenseImportByDetailsPutDto.name) &&
        equalsNullable(this.description, licenseImportByDetailsPutDto.description) &&
        equalsNullable(this.tokenLimit, licenseImportByDetailsPutDto.tokenLimit) &&
        equalsNullable(this.goodwillTokenLimit, licenseImportByDetailsPutDto.goodwillTokenLimit) &&
        equalsNullable(this.floatingTokenLimit, licenseImportByDetailsPutDto.floatingTokenLimit) &&
        equalsNullable(this.userLimit, licenseImportByDetailsPutDto.userLimit) &&
        equalsNullable(this.startDate, licenseImportByDetailsPutDto.startDate) &&
        equalsNullable(this.expirationDate, licenseImportByDetailsPutDto.expirationDate) &&
        equalsNullable(this.licenseType, licenseImportByDetailsPutDto.licenseType) &&
        equalsNullable(this.softwareReleaseLimitation, licenseImportByDetailsPutDto.softwareReleaseLimitation) &&
        equalsNullable(this.licenseFeatures, licenseImportByDetailsPutDto.licenseFeatures) &&
        equalsNullable(this.licenseLimitations, licenseImportByDetailsPutDto.licenseLimitations) &&
        equalsNullable(this.licenseVariables, licenseImportByDetailsPutDto.licenseVariables) &&
        equalsNullable(this.licenseConstrainedVariables, licenseImportByDetailsPutDto.licenseConstrainedVariables) &&
        equalsNullable(this.tags, licenseImportByDetailsPutDto.tags) &&
        equalsNullable(this.isActive, licenseImportByDetailsPutDto.isActive) &&
        Objects.equals(this.resumeOnError, licenseImportByDetailsPutDto.resumeOnError);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(licenseKey, productId, customerNumber, template, hashCodeNullable(legacyLicenseKey), hashCodeNullable(name), hashCodeNullable(description), hashCodeNullable(tokenLimit), hashCodeNullable(goodwillTokenLimit), hashCodeNullable(floatingTokenLimit), hashCodeNullable(userLimit), hashCodeNullable(startDate), hashCodeNullable(expirationDate), hashCodeNullable(licenseType), hashCodeNullable(softwareReleaseLimitation), hashCodeNullable(licenseFeatures), hashCodeNullable(licenseLimitations), hashCodeNullable(licenseVariables), hashCodeNullable(licenseConstrainedVariables), hashCodeNullable(tags), hashCodeNullable(isActive), resumeOnError);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LicenseImportByDetailsPutDto {\n");
    sb.append("    licenseKey: ").append(toIndentedString(licenseKey)).append("\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    customerNumber: ").append(toIndentedString(customerNumber)).append("\n");
    sb.append("    template: ").append(toIndentedString(template)).append("\n");
    sb.append("    legacyLicenseKey: ").append(toIndentedString(legacyLicenseKey)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    tokenLimit: ").append(toIndentedString(tokenLimit)).append("\n");
    sb.append("    goodwillTokenLimit: ").append(toIndentedString(goodwillTokenLimit)).append("\n");
    sb.append("    floatingTokenLimit: ").append(toIndentedString(floatingTokenLimit)).append("\n");
    sb.append("    userLimit: ").append(toIndentedString(userLimit)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    expirationDate: ").append(toIndentedString(expirationDate)).append("\n");
    sb.append("    licenseType: ").append(toIndentedString(licenseType)).append("\n");
    sb.append("    softwareReleaseLimitation: ").append(toIndentedString(softwareReleaseLimitation)).append("\n");
    sb.append("    licenseFeatures: ").append(toIndentedString(licenseFeatures)).append("\n");
    sb.append("    licenseLimitations: ").append(toIndentedString(licenseLimitations)).append("\n");
    sb.append("    licenseVariables: ").append(toIndentedString(licenseVariables)).append("\n");
    sb.append("    licenseConstrainedVariables: ").append(toIndentedString(licenseConstrainedVariables)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("    resumeOnError: ").append(toIndentedString(resumeOnError)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `license_key` to the URL query string
    if (getLicenseKey() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slicense_key%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLicenseKey()))));
    }

    // add `product_id` to the URL query string
    if (getProductId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sproduct_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProductId()))));
    }

    // add `customer_number` to the URL query string
    if (getCustomerNumber() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scustomer_number%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCustomerNumber()))));
    }

    // add `template` to the URL query string
    if (getTemplate() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stemplate%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTemplate()))));
    }

    // add `legacy_license_key` to the URL query string
    if (getLegacyLicenseKey() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slegacy_license_key%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLegacyLicenseKey()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdescription%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDescription()))));
    }

    // add `token_limit` to the URL query string
    if (getTokenLimit() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stoken_limit%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTokenLimit()))));
    }

    // add `goodwill_token_limit` to the URL query string
    if (getGoodwillTokenLimit() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sgoodwill_token_limit%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getGoodwillTokenLimit()))));
    }

    // add `floating_token_limit` to the URL query string
    if (getFloatingTokenLimit() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfloating_token_limit%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFloatingTokenLimit()))));
    }

    // add `user_limit` to the URL query string
    if (getUserLimit() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%suser_limit%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUserLimit()))));
    }

    // add `start_date` to the URL query string
    if (getStartDate() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstart_date%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStartDate()))));
    }

    // add `expiration_date` to the URL query string
    if (getExpirationDate() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sexpiration_date%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExpirationDate()))));
    }

    // add `license_type` to the URL query string
    if (getLicenseType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slicense_type%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLicenseType()))));
    }

    // add `software_release_limitation` to the URL query string
    if (getSoftwareReleaseLimitation() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssoftware_release_limitation%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSoftwareReleaseLimitation()))));
    }

    // add `license_features` to the URL query string
    if (getLicenseFeatures() != null) {
      for (int i = 0; i < getLicenseFeatures().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%slicense_features%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getLicenseFeatures().get(i)))));
      }
    }

    // add `license_limitations` to the URL query string
    if (getLicenseLimitations() != null) {
      for (int i = 0; i < getLicenseLimitations().size(); i++) {
        if (getLicenseLimitations().get(i) != null) {
          joiner.add(getLicenseLimitations().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%slicense_limitations%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `license_variables` to the URL query string
    if (getLicenseVariables() != null) {
      for (int i = 0; i < getLicenseVariables().size(); i++) {
        if (getLicenseVariables().get(i) != null) {
          joiner.add(getLicenseVariables().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%slicense_variables%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `license_constrained_variables` to the URL query string
    if (getLicenseConstrainedVariables() != null) {
      for (int i = 0; i < getLicenseConstrainedVariables().size(); i++) {
        if (getLicenseConstrainedVariables().get(i) != null) {
          joiner.add(getLicenseConstrainedVariables().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%slicense_constrained_variables%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `tags` to the URL query string
    if (getTags() != null) {
      for (int i = 0; i < getTags().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%stags%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getTags().get(i)))));
      }
    }

    // add `is_active` to the URL query string
    if (getIsActive() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sis_active%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsActive()))));
    }

    // add `resume_on_error` to the URL query string
    if (getResumeOnError() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sresume_on_error%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getResumeOnError()))));
    }

    return joiner.toString();
  }
}

