/*
 * SLASCONE API
 * Please visit our official [Documentation](https://support.slascone.com/hc/en-us/sections/360004685737-API) and/or our [GitHub repository](https://github.com/slascone/) and/or our [NuGet package](https://www.nuget.org/packages/Slascone.Client/). Always use Version 2 of this API (Version 1.3 is deprecated).
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.slascone.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.slascone.model.ResellerSortTypeDto;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.slascone.ApiClient;
/**
 * ResellerFilterDto
 */
@JsonPropertyOrder({
  ResellerFilterDto.JSON_PROPERTY_PAGE,
  ResellerFilterDto.JSON_PROPERTY_PAGE_SIZE,
  ResellerFilterDto.JSON_PROPERTY_SEARCH_TEXT,
  ResellerFilterDto.JSON_PROPERTY_PLZ_QUERY,
  ResellerFilterDto.JSON_PROPERTY_RESELLER_TYPES,
  ResellerFilterDto.JSON_PROPERTY_TAG_IDS,
  ResellerFilterDto.JSON_PROPERTY_START_CHARACTER,
  ResellerFilterDto.JSON_PROPERTY_RESELLER_SORT_TYPE,
  ResellerFilterDto.JSON_PROPERTY_DESCENDING
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0-SNAPSHOT")
public class ResellerFilterDto {
  public static final String JSON_PROPERTY_PAGE = "page";
  private JsonNullable<Integer> page = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_PAGE_SIZE = "page_size";
  private JsonNullable<Integer> pageSize = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_SEARCH_TEXT = "search_text";
  private JsonNullable<String> searchText = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_PLZ_QUERY = "plz_query";
  private JsonNullable<String> plzQuery = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_RESELLER_TYPES = "reseller_types";
  private JsonNullable<List<UUID>> resellerTypes = JsonNullable.<List<UUID>>undefined();

  public static final String JSON_PROPERTY_TAG_IDS = "tag_ids";
  private JsonNullable<List<Integer>> tagIds = JsonNullable.<List<Integer>>undefined();

  public static final String JSON_PROPERTY_START_CHARACTER = "start_character";
  private JsonNullable<String> startCharacter = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_RESELLER_SORT_TYPE = "reseller_sort_type";
  @jakarta.annotation.Nullable
  private ResellerSortTypeDto resellerSortType;

  public static final String JSON_PROPERTY_DESCENDING = "descending";
  @jakarta.annotation.Nullable
  private Boolean descending;

  public ResellerFilterDto() { 
  }

  public ResellerFilterDto page(@jakarta.annotation.Nullable Integer page) {
    this.page = JsonNullable.<Integer>of(page);
    return this;
  }

  /**
   * Get page
   * @return page
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public Integer getPage() {
        return page.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_PAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getPage_JsonNullable() {
    return page;
  }
  
  @JsonProperty(JSON_PROPERTY_PAGE)
  public void setPage_JsonNullable(JsonNullable<Integer> page) {
    this.page = page;
  }

  public void setPage(@jakarta.annotation.Nullable Integer page) {
    this.page = JsonNullable.<Integer>of(page);
  }


  public ResellerFilterDto pageSize(@jakarta.annotation.Nullable Integer pageSize) {
    this.pageSize = JsonNullable.<Integer>of(pageSize);
    return this;
  }

  /**
   * Get pageSize
   * @return pageSize
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public Integer getPageSize() {
        return pageSize.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_PAGE_SIZE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getPageSize_JsonNullable() {
    return pageSize;
  }
  
  @JsonProperty(JSON_PROPERTY_PAGE_SIZE)
  public void setPageSize_JsonNullable(JsonNullable<Integer> pageSize) {
    this.pageSize = pageSize;
  }

  public void setPageSize(@jakarta.annotation.Nullable Integer pageSize) {
    this.pageSize = JsonNullable.<Integer>of(pageSize);
  }


  public ResellerFilterDto searchText(@jakarta.annotation.Nullable String searchText) {
    this.searchText = JsonNullable.<String>of(searchText);
    return this;
  }

  /**
   * Get searchText
   * @return searchText
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getSearchText() {
        return searchText.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_SEARCH_TEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getSearchText_JsonNullable() {
    return searchText;
  }
  
  @JsonProperty(JSON_PROPERTY_SEARCH_TEXT)
  public void setSearchText_JsonNullable(JsonNullable<String> searchText) {
    this.searchText = searchText;
  }

  public void setSearchText(@jakarta.annotation.Nullable String searchText) {
    this.searchText = JsonNullable.<String>of(searchText);
  }


  public ResellerFilterDto plzQuery(@jakarta.annotation.Nullable String plzQuery) {
    this.plzQuery = JsonNullable.<String>of(plzQuery);
    return this;
  }

  /**
   * Get plzQuery
   * @return plzQuery
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getPlzQuery() {
        return plzQuery.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_PLZ_QUERY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getPlzQuery_JsonNullable() {
    return plzQuery;
  }
  
  @JsonProperty(JSON_PROPERTY_PLZ_QUERY)
  public void setPlzQuery_JsonNullable(JsonNullable<String> plzQuery) {
    this.plzQuery = plzQuery;
  }

  public void setPlzQuery(@jakarta.annotation.Nullable String plzQuery) {
    this.plzQuery = JsonNullable.<String>of(plzQuery);
  }


  public ResellerFilterDto resellerTypes(@jakarta.annotation.Nullable List<UUID> resellerTypes) {
    this.resellerTypes = JsonNullable.<List<UUID>>of(resellerTypes);
    return this;
  }

  public ResellerFilterDto addResellerTypesItem(UUID resellerTypesItem) {
    if (this.resellerTypes == null || !this.resellerTypes.isPresent()) {
      this.resellerTypes = JsonNullable.<List<UUID>>of(new ArrayList<>());
    }
    try {
      this.resellerTypes.get().add(resellerTypesItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get resellerTypes
   * @return resellerTypes
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public List<UUID> getResellerTypes() {
        return resellerTypes.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_RESELLER_TYPES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<UUID>> getResellerTypes_JsonNullable() {
    return resellerTypes;
  }
  
  @JsonProperty(JSON_PROPERTY_RESELLER_TYPES)
  public void setResellerTypes_JsonNullable(JsonNullable<List<UUID>> resellerTypes) {
    this.resellerTypes = resellerTypes;
  }

  public void setResellerTypes(@jakarta.annotation.Nullable List<UUID> resellerTypes) {
    this.resellerTypes = JsonNullable.<List<UUID>>of(resellerTypes);
  }


  public ResellerFilterDto tagIds(@jakarta.annotation.Nullable List<Integer> tagIds) {
    this.tagIds = JsonNullable.<List<Integer>>of(tagIds);
    return this;
  }

  public ResellerFilterDto addTagIdsItem(Integer tagIdsItem) {
    if (this.tagIds == null || !this.tagIds.isPresent()) {
      this.tagIds = JsonNullable.<List<Integer>>of(new ArrayList<>());
    }
    try {
      this.tagIds.get().add(tagIdsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get tagIds
   * @return tagIds
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public List<Integer> getTagIds() {
        return tagIds.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_TAG_IDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<Integer>> getTagIds_JsonNullable() {
    return tagIds;
  }
  
  @JsonProperty(JSON_PROPERTY_TAG_IDS)
  public void setTagIds_JsonNullable(JsonNullable<List<Integer>> tagIds) {
    this.tagIds = tagIds;
  }

  public void setTagIds(@jakarta.annotation.Nullable List<Integer> tagIds) {
    this.tagIds = JsonNullable.<List<Integer>>of(tagIds);
  }


  public ResellerFilterDto startCharacter(@jakarta.annotation.Nullable String startCharacter) {
    this.startCharacter = JsonNullable.<String>of(startCharacter);
    return this;
  }

  /**
   * Get startCharacter
   * @return startCharacter
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getStartCharacter() {
        return startCharacter.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_START_CHARACTER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getStartCharacter_JsonNullable() {
    return startCharacter;
  }
  
  @JsonProperty(JSON_PROPERTY_START_CHARACTER)
  public void setStartCharacter_JsonNullable(JsonNullable<String> startCharacter) {
    this.startCharacter = startCharacter;
  }

  public void setStartCharacter(@jakarta.annotation.Nullable String startCharacter) {
    this.startCharacter = JsonNullable.<String>of(startCharacter);
  }


  public ResellerFilterDto resellerSortType(@jakarta.annotation.Nullable ResellerSortTypeDto resellerSortType) {
    this.resellerSortType = resellerSortType;
    return this;
  }

  /**
   * Get resellerSortType
   * @return resellerSortType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RESELLER_SORT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ResellerSortTypeDto getResellerSortType() {
    return resellerSortType;
  }


  @JsonProperty(value = JSON_PROPERTY_RESELLER_SORT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResellerSortType(@jakarta.annotation.Nullable ResellerSortTypeDto resellerSortType) {
    this.resellerSortType = resellerSortType;
  }


  public ResellerFilterDto descending(@jakarta.annotation.Nullable Boolean descending) {
    this.descending = descending;
    return this;
  }

  /**
   * Get descending
   * @return descending
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCENDING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getDescending() {
    return descending;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCENDING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescending(@jakarta.annotation.Nullable Boolean descending) {
    this.descending = descending;
  }


  /**
   * Return true if this ResellerFilterDto object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResellerFilterDto resellerFilterDto = (ResellerFilterDto) o;
    return equalsNullable(this.page, resellerFilterDto.page) &&
        equalsNullable(this.pageSize, resellerFilterDto.pageSize) &&
        equalsNullable(this.searchText, resellerFilterDto.searchText) &&
        equalsNullable(this.plzQuery, resellerFilterDto.plzQuery) &&
        equalsNullable(this.resellerTypes, resellerFilterDto.resellerTypes) &&
        equalsNullable(this.tagIds, resellerFilterDto.tagIds) &&
        equalsNullable(this.startCharacter, resellerFilterDto.startCharacter) &&
        Objects.equals(this.resellerSortType, resellerFilterDto.resellerSortType) &&
        Objects.equals(this.descending, resellerFilterDto.descending);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(page), hashCodeNullable(pageSize), hashCodeNullable(searchText), hashCodeNullable(plzQuery), hashCodeNullable(resellerTypes), hashCodeNullable(tagIds), hashCodeNullable(startCharacter), resellerSortType, descending);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResellerFilterDto {\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    searchText: ").append(toIndentedString(searchText)).append("\n");
    sb.append("    plzQuery: ").append(toIndentedString(plzQuery)).append("\n");
    sb.append("    resellerTypes: ").append(toIndentedString(resellerTypes)).append("\n");
    sb.append("    tagIds: ").append(toIndentedString(tagIds)).append("\n");
    sb.append("    startCharacter: ").append(toIndentedString(startCharacter)).append("\n");
    sb.append("    resellerSortType: ").append(toIndentedString(resellerSortType)).append("\n");
    sb.append("    descending: ").append(toIndentedString(descending)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `page` to the URL query string
    if (getPage() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPage()))));
    }

    // add `page_size` to the URL query string
    if (getPageSize() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spage_size%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPageSize()))));
    }

    // add `search_text` to the URL query string
    if (getSearchText() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssearch_text%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSearchText()))));
    }

    // add `plz_query` to the URL query string
    if (getPlzQuery() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%splz_query%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPlzQuery()))));
    }

    // add `reseller_types` to the URL query string
    if (getResellerTypes() != null) {
      for (int i = 0; i < getResellerTypes().size(); i++) {
        if (getResellerTypes().get(i) != null) {
          joiner.add(String.format(java.util.Locale.ROOT, "%sreseller_types%s%s=%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
              ApiClient.urlEncode(ApiClient.valueToString(getResellerTypes().get(i)))));
        }
      }
    }

    // add `tag_ids` to the URL query string
    if (getTagIds() != null) {
      for (int i = 0; i < getTagIds().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%stag_ids%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getTagIds().get(i)))));
      }
    }

    // add `start_character` to the URL query string
    if (getStartCharacter() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstart_character%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStartCharacter()))));
    }

    // add `reseller_sort_type` to the URL query string
    if (getResellerSortType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sreseller_sort_type%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getResellerSortType()))));
    }

    // add `descending` to the URL query string
    if (getDescending() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdescending%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDescending()))));
    }

    return joiner.toString();
  }
}

