/*
 * SLASCONE API
 * Please visit our official [Documentation](https://support.slascone.com/hc/en-us/sections/360004685737-API) and/or our [GitHub repository](https://github.com/slascone/) and/or our [NuGet package](https://www.nuget.org/packages/Slascone.Client/). Always use Version 2 of this API (Version 1.3 is deprecated).
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.slascone.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.slascone.model.ResellerDto;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.slascone.ApiClient;
/**
 * ResellerLazyLoadDto
 */
@JsonPropertyOrder({
  ResellerLazyLoadDto.JSON_PROPERTY_RESELLERS,
  ResellerLazyLoadDto.JSON_PROPERTY_MAX_COUNT,
  ResellerLazyLoadDto.JSON_PROPERTY_RESELLER_CHARACTER
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0-SNAPSHOT")
public class ResellerLazyLoadDto {
  public static final String JSON_PROPERTY_RESELLERS = "resellers";
  private JsonNullable<List<ResellerDto>> resellers = JsonNullable.<List<ResellerDto>>undefined();

  public static final String JSON_PROPERTY_MAX_COUNT = "max_count";
  @jakarta.annotation.Nullable
  private Integer maxCount;

  public static final String JSON_PROPERTY_RESELLER_CHARACTER = "reseller_character";
  private JsonNullable<List<String>> resellerCharacter = JsonNullable.<List<String>>undefined();

  public ResellerLazyLoadDto() { 
  }

  public ResellerLazyLoadDto resellers(@jakarta.annotation.Nullable List<ResellerDto> resellers) {
    this.resellers = JsonNullable.<List<ResellerDto>>of(resellers);
    return this;
  }

  public ResellerLazyLoadDto addResellersItem(ResellerDto resellersItem) {
    if (this.resellers == null || !this.resellers.isPresent()) {
      this.resellers = JsonNullable.<List<ResellerDto>>of(new ArrayList<>());
    }
    try {
      this.resellers.get().add(resellersItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get resellers
   * @return resellers
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public List<ResellerDto> getResellers() {
        return resellers.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_RESELLERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<ResellerDto>> getResellers_JsonNullable() {
    return resellers;
  }
  
  @JsonProperty(JSON_PROPERTY_RESELLERS)
  public void setResellers_JsonNullable(JsonNullable<List<ResellerDto>> resellers) {
    this.resellers = resellers;
  }

  public void setResellers(@jakarta.annotation.Nullable List<ResellerDto> resellers) {
    this.resellers = JsonNullable.<List<ResellerDto>>of(resellers);
  }


  public ResellerLazyLoadDto maxCount(@jakarta.annotation.Nullable Integer maxCount) {
    this.maxCount = maxCount;
    return this;
  }

  /**
   * Get maxCount
   * @return maxCount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MAX_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getMaxCount() {
    return maxCount;
  }


  @JsonProperty(value = JSON_PROPERTY_MAX_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxCount(@jakarta.annotation.Nullable Integer maxCount) {
    this.maxCount = maxCount;
  }


  public ResellerLazyLoadDto resellerCharacter(@jakarta.annotation.Nullable List<String> resellerCharacter) {
    this.resellerCharacter = JsonNullable.<List<String>>of(resellerCharacter);
    return this;
  }

  public ResellerLazyLoadDto addResellerCharacterItem(String resellerCharacterItem) {
    if (this.resellerCharacter == null || !this.resellerCharacter.isPresent()) {
      this.resellerCharacter = JsonNullable.<List<String>>of(new ArrayList<>());
    }
    try {
      this.resellerCharacter.get().add(resellerCharacterItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get resellerCharacter
   * @return resellerCharacter
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public List<String> getResellerCharacter() {
        return resellerCharacter.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_RESELLER_CHARACTER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<String>> getResellerCharacter_JsonNullable() {
    return resellerCharacter;
  }
  
  @JsonProperty(JSON_PROPERTY_RESELLER_CHARACTER)
  public void setResellerCharacter_JsonNullable(JsonNullable<List<String>> resellerCharacter) {
    this.resellerCharacter = resellerCharacter;
  }

  public void setResellerCharacter(@jakarta.annotation.Nullable List<String> resellerCharacter) {
    this.resellerCharacter = JsonNullable.<List<String>>of(resellerCharacter);
  }


  /**
   * Return true if this ResellerLazyLoadDto object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResellerLazyLoadDto resellerLazyLoadDto = (ResellerLazyLoadDto) o;
    return equalsNullable(this.resellers, resellerLazyLoadDto.resellers) &&
        Objects.equals(this.maxCount, resellerLazyLoadDto.maxCount) &&
        equalsNullable(this.resellerCharacter, resellerLazyLoadDto.resellerCharacter);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(resellers), maxCount, hashCodeNullable(resellerCharacter));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResellerLazyLoadDto {\n");
    sb.append("    resellers: ").append(toIndentedString(resellers)).append("\n");
    sb.append("    maxCount: ").append(toIndentedString(maxCount)).append("\n");
    sb.append("    resellerCharacter: ").append(toIndentedString(resellerCharacter)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `resellers` to the URL query string
    if (getResellers() != null) {
      for (int i = 0; i < getResellers().size(); i++) {
        if (getResellers().get(i) != null) {
          joiner.add(getResellers().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sresellers%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `max_count` to the URL query string
    if (getMaxCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smax_count%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMaxCount()))));
    }

    // add `reseller_character` to the URL query string
    if (getResellerCharacter() != null) {
      for (int i = 0; i < getResellerCharacter().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sreseller_character%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getResellerCharacter().get(i)))));
      }
    }

    return joiner.toString();
  }
}

