/*
 * SLASCONE API
 * Please visit our official [Documentation](https://support.slascone.com/hc/en-us/sections/360004685737-API) and/or our [GitHub repository](https://github.com/slascone/) and/or our [NuGet package](https://www.nuget.org/packages/Slascone.Client/). Always use Version 2 of this API (Version 1.3 is deprecated).
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.slascone.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.slascone.JSON;

/**
 * UsageFeatureNameDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class UsageFeatureNameDto {
  public static final String SERIALIZED_NAME_USAGE_FEATURE_NAME = "usage_feature_name";
  @SerializedName(SERIALIZED_NAME_USAGE_FEATURE_NAME)
  @javax.annotation.Nonnull
  private String usageFeatureName;

  public static final String SERIALIZED_NAME_USAGE_MODULE_NAME = "usage_module_name";
  @SerializedName(SERIALIZED_NAME_USAGE_MODULE_NAME)
  @javax.annotation.Nullable
  private String usageModuleName;

  public static final String SERIALIZED_NAME_TIMESTAMP_UTC = "timestamp_utc";
  @SerializedName(SERIALIZED_NAME_TIMESTAMP_UTC)
  @javax.annotation.Nullable
  private OffsetDateTime timestampUtc;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  @javax.annotation.Nullable
  private Double value;

  public UsageFeatureNameDto() {
  }

  public UsageFeatureNameDto usageFeatureName(@javax.annotation.Nonnull String usageFeatureName) {
    this.usageFeatureName = usageFeatureName;
    return this;
  }

  /**
   * Get usageFeatureName
   * @return usageFeatureName
   */
  @javax.annotation.Nonnull
  public String getUsageFeatureName() {
    return usageFeatureName;
  }

  public void setUsageFeatureName(@javax.annotation.Nonnull String usageFeatureName) {
    this.usageFeatureName = usageFeatureName;
  }


  public UsageFeatureNameDto usageModuleName(@javax.annotation.Nullable String usageModuleName) {
    this.usageModuleName = usageModuleName;
    return this;
  }

  /**
   * Get usageModuleName
   * @return usageModuleName
   */
  @javax.annotation.Nullable
  public String getUsageModuleName() {
    return usageModuleName;
  }

  public void setUsageModuleName(@javax.annotation.Nullable String usageModuleName) {
    this.usageModuleName = usageModuleName;
  }


  public UsageFeatureNameDto timestampUtc(@javax.annotation.Nullable OffsetDateTime timestampUtc) {
    this.timestampUtc = timestampUtc;
    return this;
  }

  /**
   * Get timestampUtc
   * @return timestampUtc
   */
  @javax.annotation.Nullable
  public OffsetDateTime getTimestampUtc() {
    return timestampUtc;
  }

  public void setTimestampUtc(@javax.annotation.Nullable OffsetDateTime timestampUtc) {
    this.timestampUtc = timestampUtc;
  }


  public UsageFeatureNameDto value(@javax.annotation.Nullable Double value) {
    this.value = value;
    return this;
  }

  /**
   * Get value
   * @return value
   */
  @javax.annotation.Nullable
  public Double getValue() {
    return value;
  }

  public void setValue(@javax.annotation.Nullable Double value) {
    this.value = value;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsageFeatureNameDto usageFeatureNameDto = (UsageFeatureNameDto) o;
    return Objects.equals(this.usageFeatureName, usageFeatureNameDto.usageFeatureName) &&
        Objects.equals(this.usageModuleName, usageFeatureNameDto.usageModuleName) &&
        Objects.equals(this.timestampUtc, usageFeatureNameDto.timestampUtc) &&
        Objects.equals(this.value, usageFeatureNameDto.value);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(usageFeatureName, usageModuleName, timestampUtc, value);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsageFeatureNameDto {\n");
    sb.append("    usageFeatureName: ").append(toIndentedString(usageFeatureName)).append("\n");
    sb.append("    usageModuleName: ").append(toIndentedString(usageModuleName)).append("\n");
    sb.append("    timestampUtc: ").append(toIndentedString(timestampUtc)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("usage_feature_name", "usage_module_name", "timestamp_utc", "value"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("usage_feature_name"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to UsageFeatureNameDto
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UsageFeatureNameDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UsageFeatureNameDto is not found in the empty JSON string", UsageFeatureNameDto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!UsageFeatureNameDto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `UsageFeatureNameDto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : UsageFeatureNameDto.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("usage_feature_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `usage_feature_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("usage_feature_name").toString()));
      }
      if ((jsonObj.get("usage_module_name") != null && !jsonObj.get("usage_module_name").isJsonNull()) && !jsonObj.get("usage_module_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `usage_module_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("usage_module_name").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UsageFeatureNameDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UsageFeatureNameDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UsageFeatureNameDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UsageFeatureNameDto.class));

       return (TypeAdapter<T>) new TypeAdapter<UsageFeatureNameDto>() {
           @Override
           public void write(JsonWriter out, UsageFeatureNameDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UsageFeatureNameDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of UsageFeatureNameDto given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UsageFeatureNameDto
   * @throws IOException if the JSON string is invalid with respect to UsageFeatureNameDto
   */
  public static UsageFeatureNameDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UsageFeatureNameDto.class);
  }

  /**
   * Convert an instance of UsageFeatureNameDto to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

