/*
 * SLASCONE API
 * Please visit our official [Documentation](https://support.slascone.com/hc/en-us/sections/360004685737-API) and/or our [GitHub repository](https://github.com/slascone/) and/or our [NuGet package](https://www.nuget.org/packages/Slascone.Client/). Always use Version 2 of this API (Version 1.3 is deprecated).
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.slascone.model;

import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.slascone.ApiClient;
/**
 * UserEmailTemplateDto
 */
@JsonPropertyOrder({
  UserEmailTemplateDto.JSON_PROPERTY_ID,
  UserEmailTemplateDto.JSON_PROPERTY_NAME,
  UserEmailTemplateDto.JSON_PROPERTY_LANGUAGE,
  UserEmailTemplateDto.JSON_PROPERTY_SUBJECT,
  UserEmailTemplateDto.JSON_PROPERTY_BODY,
  UserEmailTemplateDto.JSON_PROPERTY_PARENT_ID,
  UserEmailTemplateDto.JSON_PROPERTY_SUB_EMAIL_TEMPLATES,
  UserEmailTemplateDto.JSON_PROPERTY_CREATED_DATE_UTC,
  UserEmailTemplateDto.JSON_PROPERTY_MODIFIED_DATE_UTC,
  UserEmailTemplateDto.JSON_PROPERTY_LAST_MODIFIED_BY,
  UserEmailTemplateDto.JSON_PROPERTY_PURPOSE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0-SNAPSHOT")
public class UserEmailTemplateDto {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private UUID id;

  public static final String JSON_PROPERTY_NAME = "name";
  private JsonNullable<String> name = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_LANGUAGE = "language";
  private JsonNullable<String> language = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_SUBJECT = "subject";
  private JsonNullable<String> subject = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_BODY = "body";
  private JsonNullable<String> body = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_PARENT_ID = "parent_id";
  private JsonNullable<UUID> parentId = JsonNullable.<UUID>undefined();

  public static final String JSON_PROPERTY_SUB_EMAIL_TEMPLATES = "sub_email_templates";
  private JsonNullable<List<UserEmailTemplateDto>> subEmailTemplates = JsonNullable.<List<UserEmailTemplateDto>>undefined();

  public static final String JSON_PROPERTY_CREATED_DATE_UTC = "created_date_utc";
  private JsonNullable<OffsetDateTime> createdDateUtc = JsonNullable.<OffsetDateTime>undefined();

  public static final String JSON_PROPERTY_MODIFIED_DATE_UTC = "modified_date_utc";
  private JsonNullable<OffsetDateTime> modifiedDateUtc = JsonNullable.<OffsetDateTime>undefined();

  public static final String JSON_PROPERTY_LAST_MODIFIED_BY = "last_modified_by";
  private JsonNullable<String> lastModifiedBy = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_PURPOSE = "purpose";
  private JsonNullable<String> purpose = JsonNullable.<String>undefined();

  public UserEmailTemplateDto() { 
  }

  public UserEmailTemplateDto id(@jakarta.annotation.Nullable UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable UUID id) {
    this.id = id;
  }


  public UserEmailTemplateDto name(@jakarta.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getName() {
        return name.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getName_JsonNullable() {
    return name;
  }
  
  @JsonProperty(JSON_PROPERTY_NAME)
  public void setName_JsonNullable(JsonNullable<String> name) {
    this.name = name;
  }

  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
  }


  public UserEmailTemplateDto language(@jakarta.annotation.Nullable String language) {
    this.language = JsonNullable.<String>of(language);
    return this;
  }

  /**
   * Get language
   * @return language
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getLanguage() {
        return language.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_LANGUAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLanguage_JsonNullable() {
    return language;
  }
  
  @JsonProperty(JSON_PROPERTY_LANGUAGE)
  public void setLanguage_JsonNullable(JsonNullable<String> language) {
    this.language = language;
  }

  public void setLanguage(@jakarta.annotation.Nullable String language) {
    this.language = JsonNullable.<String>of(language);
  }


  public UserEmailTemplateDto subject(@jakarta.annotation.Nullable String subject) {
    this.subject = JsonNullable.<String>of(subject);
    return this;
  }

  /**
   * Get subject
   * @return subject
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getSubject() {
        return subject.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_SUBJECT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getSubject_JsonNullable() {
    return subject;
  }
  
  @JsonProperty(JSON_PROPERTY_SUBJECT)
  public void setSubject_JsonNullable(JsonNullable<String> subject) {
    this.subject = subject;
  }

  public void setSubject(@jakarta.annotation.Nullable String subject) {
    this.subject = JsonNullable.<String>of(subject);
  }


  public UserEmailTemplateDto body(@jakarta.annotation.Nullable String body) {
    this.body = JsonNullable.<String>of(body);
    return this;
  }

  /**
   * Get body
   * @return body
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getBody() {
        return body.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_BODY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getBody_JsonNullable() {
    return body;
  }
  
  @JsonProperty(JSON_PROPERTY_BODY)
  public void setBody_JsonNullable(JsonNullable<String> body) {
    this.body = body;
  }

  public void setBody(@jakarta.annotation.Nullable String body) {
    this.body = JsonNullable.<String>of(body);
  }


  public UserEmailTemplateDto parentId(@jakarta.annotation.Nullable UUID parentId) {
    this.parentId = JsonNullable.<UUID>of(parentId);
    return this;
  }

  /**
   * Get parentId
   * @return parentId
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public UUID getParentId() {
        return parentId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_PARENT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<UUID> getParentId_JsonNullable() {
    return parentId;
  }
  
  @JsonProperty(JSON_PROPERTY_PARENT_ID)
  public void setParentId_JsonNullable(JsonNullable<UUID> parentId) {
    this.parentId = parentId;
  }

  public void setParentId(@jakarta.annotation.Nullable UUID parentId) {
    this.parentId = JsonNullable.<UUID>of(parentId);
  }


  public UserEmailTemplateDto subEmailTemplates(@jakarta.annotation.Nullable List<UserEmailTemplateDto> subEmailTemplates) {
    this.subEmailTemplates = JsonNullable.<List<UserEmailTemplateDto>>of(subEmailTemplates);
    return this;
  }

  public UserEmailTemplateDto addSubEmailTemplatesItem(UserEmailTemplateDto subEmailTemplatesItem) {
    if (this.subEmailTemplates == null || !this.subEmailTemplates.isPresent()) {
      this.subEmailTemplates = JsonNullable.<List<UserEmailTemplateDto>>of(new ArrayList<>());
    }
    try {
      this.subEmailTemplates.get().add(subEmailTemplatesItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get subEmailTemplates
   * @return subEmailTemplates
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public List<UserEmailTemplateDto> getSubEmailTemplates() {
        return subEmailTemplates.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_SUB_EMAIL_TEMPLATES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<UserEmailTemplateDto>> getSubEmailTemplates_JsonNullable() {
    return subEmailTemplates;
  }
  
  @JsonProperty(JSON_PROPERTY_SUB_EMAIL_TEMPLATES)
  public void setSubEmailTemplates_JsonNullable(JsonNullable<List<UserEmailTemplateDto>> subEmailTemplates) {
    this.subEmailTemplates = subEmailTemplates;
  }

  public void setSubEmailTemplates(@jakarta.annotation.Nullable List<UserEmailTemplateDto> subEmailTemplates) {
    this.subEmailTemplates = JsonNullable.<List<UserEmailTemplateDto>>of(subEmailTemplates);
  }


  public UserEmailTemplateDto createdDateUtc(@jakarta.annotation.Nullable OffsetDateTime createdDateUtc) {
    this.createdDateUtc = JsonNullable.<OffsetDateTime>of(createdDateUtc);
    return this;
  }

  /**
   * Get createdDateUtc
   * @return createdDateUtc
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public OffsetDateTime getCreatedDateUtc() {
        return createdDateUtc.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_CREATED_DATE_UTC, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getCreatedDateUtc_JsonNullable() {
    return createdDateUtc;
  }
  
  @JsonProperty(JSON_PROPERTY_CREATED_DATE_UTC)
  public void setCreatedDateUtc_JsonNullable(JsonNullable<OffsetDateTime> createdDateUtc) {
    this.createdDateUtc = createdDateUtc;
  }

  public void setCreatedDateUtc(@jakarta.annotation.Nullable OffsetDateTime createdDateUtc) {
    this.createdDateUtc = JsonNullable.<OffsetDateTime>of(createdDateUtc);
  }


  public UserEmailTemplateDto modifiedDateUtc(@jakarta.annotation.Nullable OffsetDateTime modifiedDateUtc) {
    this.modifiedDateUtc = JsonNullable.<OffsetDateTime>of(modifiedDateUtc);
    return this;
  }

  /**
   * Get modifiedDateUtc
   * @return modifiedDateUtc
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public OffsetDateTime getModifiedDateUtc() {
        return modifiedDateUtc.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_MODIFIED_DATE_UTC, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getModifiedDateUtc_JsonNullable() {
    return modifiedDateUtc;
  }
  
  @JsonProperty(JSON_PROPERTY_MODIFIED_DATE_UTC)
  public void setModifiedDateUtc_JsonNullable(JsonNullable<OffsetDateTime> modifiedDateUtc) {
    this.modifiedDateUtc = modifiedDateUtc;
  }

  public void setModifiedDateUtc(@jakarta.annotation.Nullable OffsetDateTime modifiedDateUtc) {
    this.modifiedDateUtc = JsonNullable.<OffsetDateTime>of(modifiedDateUtc);
  }


  public UserEmailTemplateDto lastModifiedBy(@jakarta.annotation.Nullable String lastModifiedBy) {
    this.lastModifiedBy = JsonNullable.<String>of(lastModifiedBy);
    return this;
  }

  /**
   * Get lastModifiedBy
   * @return lastModifiedBy
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getLastModifiedBy() {
        return lastModifiedBy.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_LAST_MODIFIED_BY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLastModifiedBy_JsonNullable() {
    return lastModifiedBy;
  }
  
  @JsonProperty(JSON_PROPERTY_LAST_MODIFIED_BY)
  public void setLastModifiedBy_JsonNullable(JsonNullable<String> lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }

  public void setLastModifiedBy(@jakarta.annotation.Nullable String lastModifiedBy) {
    this.lastModifiedBy = JsonNullable.<String>of(lastModifiedBy);
  }


  public UserEmailTemplateDto purpose(@jakarta.annotation.Nullable String purpose) {
    this.purpose = JsonNullable.<String>of(purpose);
    return this;
  }

  /**
   * Get purpose
   * @return purpose
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getPurpose() {
        return purpose.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_PURPOSE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getPurpose_JsonNullable() {
    return purpose;
  }
  
  @JsonProperty(JSON_PROPERTY_PURPOSE)
  public void setPurpose_JsonNullable(JsonNullable<String> purpose) {
    this.purpose = purpose;
  }

  public void setPurpose(@jakarta.annotation.Nullable String purpose) {
    this.purpose = JsonNullable.<String>of(purpose);
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   * @param key the name of the property
   * @param value the value of the property
   * @return self reference
   */
  @JsonAnySetter
  public UserEmailTemplateDto putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) properties.
   * @return the additional (undeclared) properties
   */
  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   * @param key the name of the property
   * @return the additional (undeclared) property with the specified name
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }

  /**
   * Return true if this UserEmailTemplateDto object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserEmailTemplateDto userEmailTemplateDto = (UserEmailTemplateDto) o;
    return Objects.equals(this.id, userEmailTemplateDto.id) &&
        equalsNullable(this.name, userEmailTemplateDto.name) &&
        equalsNullable(this.language, userEmailTemplateDto.language) &&
        equalsNullable(this.subject, userEmailTemplateDto.subject) &&
        equalsNullable(this.body, userEmailTemplateDto.body) &&
        equalsNullable(this.parentId, userEmailTemplateDto.parentId) &&
        equalsNullable(this.subEmailTemplates, userEmailTemplateDto.subEmailTemplates) &&
        equalsNullable(this.createdDateUtc, userEmailTemplateDto.createdDateUtc) &&
        equalsNullable(this.modifiedDateUtc, userEmailTemplateDto.modifiedDateUtc) &&
        equalsNullable(this.lastModifiedBy, userEmailTemplateDto.lastModifiedBy) &&
        equalsNullable(this.purpose, userEmailTemplateDto.purpose)&&
        Objects.equals(this.additionalProperties, userEmailTemplateDto.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, hashCodeNullable(name), hashCodeNullable(language), hashCodeNullable(subject), hashCodeNullable(body), hashCodeNullable(parentId), hashCodeNullable(subEmailTemplates), hashCodeNullable(createdDateUtc), hashCodeNullable(modifiedDateUtc), hashCodeNullable(lastModifiedBy), hashCodeNullable(purpose), additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserEmailTemplateDto {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    subEmailTemplates: ").append(toIndentedString(subEmailTemplates)).append("\n");
    sb.append("    createdDateUtc: ").append(toIndentedString(createdDateUtc)).append("\n");
    sb.append("    modifiedDateUtc: ").append(toIndentedString(modifiedDateUtc)).append("\n");
    sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");
    sb.append("    purpose: ").append(toIndentedString(purpose)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `language` to the URL query string
    if (getLanguage() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slanguage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLanguage()))));
    }

    // add `subject` to the URL query string
    if (getSubject() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssubject%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSubject()))));
    }

    // add `body` to the URL query string
    if (getBody() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbody%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBody()))));
    }

    // add `parent_id` to the URL query string
    if (getParentId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sparent_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getParentId()))));
    }

    // add `sub_email_templates` to the URL query string
    if (getSubEmailTemplates() != null) {
      for (int i = 0; i < getSubEmailTemplates().size(); i++) {
        if (getSubEmailTemplates().get(i) != null) {
          joiner.add(getSubEmailTemplates().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%ssub_email_templates%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `created_date_utc` to the URL query string
    if (getCreatedDateUtc() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screated_date_utc%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedDateUtc()))));
    }

    // add `modified_date_utc` to the URL query string
    if (getModifiedDateUtc() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smodified_date_utc%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getModifiedDateUtc()))));
    }

    // add `last_modified_by` to the URL query string
    if (getLastModifiedBy() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slast_modified_by%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLastModifiedBy()))));
    }

    // add `purpose` to the URL query string
    if (getPurpose() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spurpose%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPurpose()))));
    }

    return joiner.toString();
  }
}

