/*
 * SLASCONE API
 * Please visit our official [Documentation](https://support.slascone.com/hc/en-us/sections/360004685737-API) and/or our [GitHub repository](https://github.com/slascone/) and/or our [NuGet package](https://www.nuget.org/packages/Slascone.Client/). Always use Version 2 of this API (Version 1.3 is deprecated).
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.slascone.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.slascone.model.AlertMode;
import com.slascone.model.EmailTemplateDto;
import com.slascone.model.TemplateDto;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AlertDto
 */
class AlertDtoTest {
    private final AlertDto model = new AlertDto();

    /**
     * Model tests for AlertDto
     */
    @Test
    void testAlertDto() {
        // TODO: test AlertDto
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'isActive'
     */
    @Test
    void isActiveTest() {
        // TODO: test isActive
    }

    /**
     * Test the property 'alertDays'
     */
    @Test
    void alertDaysTest() {
        // TODO: test alertDays
    }

    /**
     * Test the property 'mode'
     */
    @Test
    void modeTest() {
        // TODO: test mode
    }

    /**
     * Test the property 'templateId'
     */
    @Test
    void templateIdTest() {
        // TODO: test templateId
    }

    /**
     * Test the property 'template'
     */
    @Test
    void templateTest() {
        // TODO: test template
    }

    /**
     * Test the property 'emailTemplateId'
     */
    @Test
    void emailTemplateIdTest() {
        // TODO: test emailTemplateId
    }

    /**
     * Test the property 'emailTemplate'
     */
    @Test
    void emailTemplateTest() {
        // TODO: test emailTemplate
    }

    /**
     * Test the property 'createdDateUtc'
     */
    @Test
    void createdDateUtcTest() {
        // TODO: test createdDateUtc
    }

}
