/*
 * SLASCONE API
 * Please visit our official [Documentation](https://support.slascone.com/hc/en-us/sections/360004685737-API) and/or our [GitHub repository](https://github.com/slascone/) and/or our [NuGet package](https://www.nuget.org/packages/Slascone.Client/). Always use Version 2 of this API (Version 1.3 is deprecated).
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.slascone.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.slascone.model.CustomerTypeDto;
import com.slascone.model.ResourceDto;
import com.slascone.model.TagAssignmentDto;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CustomerDto
 */
class CustomerDtoTest {
    private final CustomerDto model = new CustomerDto();

    /**
     * Model tests for CustomerDto
     */
    @Test
    void testCustomerDto() {
        // TODO: test CustomerDto
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'companyName'
     */
    @Test
    void companyNameTest() {
        // TODO: test companyName
    }

    /**
     * Test the property 'customerNumber'
     */
    @Test
    void customerNumberTest() {
        // TODO: test customerNumber
    }

    /**
     * Test the property 'customerType'
     */
    @Test
    void customerTypeTest() {
        // TODO: test customerType
    }

    /**
     * Test the property 'email'
     */
    @Test
    void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'street'
     */
    @Test
    void streetTest() {
        // TODO: test street
    }

    /**
     * Test the property 'city'
     */
    @Test
    void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'postalcode'
     */
    @Test
    void postalcodeTest() {
        // TODO: test postalcode
    }

    /**
     * Test the property 'country'
     */
    @Test
    void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'phone'
     */
    @Test
    void phoneTest() {
        // TODO: test phone
    }

    /**
     * Test the property 'prospectNumber'
     */
    @Test
    void prospectNumberTest() {
        // TODO: test prospectNumber
    }

    /**
     * Test the property 'longitude'
     */
    @Test
    void longitudeTest() {
        // TODO: test longitude
    }

    /**
     * Test the property 'latitude'
     */
    @Test
    void latitudeTest() {
        // TODO: test latitude
    }

    /**
     * Test the property 'createdDateUtc'
     */
    @Test
    void createdDateUtcTest() {
        // TODO: test createdDateUtc
    }

    /**
     * Test the property 'modifiedDateUtc'
     */
    @Test
    void modifiedDateUtcTest() {
        // TODO: test modifiedDateUtc
    }

    /**
     * Test the property 'lastModifiedBy'
     */
    @Test
    void lastModifiedByTest() {
        // TODO: test lastModifiedBy
    }

    /**
     * Test the property 'tagAssignments'
     */
    @Test
    void tagAssignmentsTest() {
        // TODO: test tagAssignments
    }

    /**
     * Test the property 'logo'
     */
    @Test
    void logoTest() {
        // TODO: test logo
    }

    /**
     * Test the property 'resellerId'
     */
    @Test
    void resellerIdTest() {
        // TODO: test resellerId
    }

}
