/*
 * SLASCONE API
 * Please visit our official [Documentation](https://support.slascone.com/hc/en-us/sections/360004685737-API) and/or our [GitHub repository](https://github.com/slascone/) and/or our [NuGet package](https://www.nuget.org/packages/Slascone.Client/). Always use Version 2 of this API (Version 1.3 is deprecated).
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.slascone.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.slascone.model.ClientType;
import com.slascone.model.CustomerAccountDto;
import com.slascone.model.DateValidity;
import com.slascone.model.LicenseTypeDto;
import com.slascone.model.LicenseUserDto;
import com.slascone.model.ProvisioningConstrainedVariableDto;
import com.slascone.model.ProvisioningFeatureDto;
import com.slascone.model.ProvisioningLimitationDto;
import com.slascone.model.ProvisioningMode;
import com.slascone.model.ProvisioningVariableDto;
import com.slascone.model.SoftwareReleaseLimitationDto;
import com.slascone.model.SoftwareShipmentDto;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for LicenseInfoDto
 */
class LicenseInfoDtoTest {
    private final LicenseInfoDto model = new LicenseInfoDto();

    /**
     * Model tests for LicenseInfoDto
     */
    @Test
    void testLicenseInfoDto() {
        // TODO: test LicenseInfoDto
    }

    /**
     * Test the property 'customer'
     */
    @Test
    void customerTest() {
        // TODO: test customer
    }

    /**
     * Test the property 'licenseName'
     */
    @Test
    void licenseNameTest() {
        // TODO: test licenseName
    }

    /**
     * Test the property 'licenseKey'
     */
    @Test
    void licenseKeyTest() {
        // TODO: test licenseKey
    }

    /**
     * Test the property 'tokenKey'
     */
    @Test
    void tokenKeyTest() {
        // TODO: test tokenKey
    }

    /**
     * Test the property 'legacyLicenseKey'
     */
    @Test
    void legacyLicenseKeyTest() {
        // TODO: test legacyLicenseKey
    }

    /**
     * Test the property 'clientId'
     */
    @Test
    void clientIdTest() {
        // TODO: test clientId
    }

    /**
     * Test the property 'clientName'
     */
    @Test
    void clientNameTest() {
        // TODO: test clientName
    }

    /**
     * Test the property 'clientDescription'
     */
    @Test
    void clientDescriptionTest() {
        // TODO: test clientDescription
    }

    /**
     * Test the property 'productName'
     */
    @Test
    void productNameTest() {
        // TODO: test productName
    }

    /**
     * Test the property 'productId'
     */
    @Test
    void productIdTest() {
        // TODO: test productId
    }

    /**
     * Test the property 'templateName'
     */
    @Test
    void templateNameTest() {
        // TODO: test templateName
    }

    /**
     * Test the property 'templateId'
     */
    @Test
    void templateIdTest() {
        // TODO: test templateId
    }

    /**
     * Test the property 'provisioningMode'
     */
    @Test
    void provisioningModeTest() {
        // TODO: test provisioningMode
    }

    /**
     * Test the property 'clientType'
     */
    @Test
    void clientTypeTest() {
        // TODO: test clientType
    }

    /**
     * Test the property 'isLicenseActive'
     */
    @Test
    void isLicenseActiveTest() {
        // TODO: test isLicenseActive
    }

    /**
     * Test the property 'isLicenseExpired'
     */
    @Test
    void isLicenseExpiredTest() {
        // TODO: test isLicenseExpired
    }

    /**
     * Test the property 'isLicenseValid'
     */
    @Test
    void isLicenseValidTest() {
        // TODO: test isLicenseValid
    }

    /**
     * Test the property 'startDateUtc'
     */
    @Test
    void startDateUtcTest() {
        // TODO: test startDateUtc
    }

    /**
     * Test the property 'expirationDateUtc'
     */
    @Test
    void expirationDateUtcTest() {
        // TODO: test expirationDateUtc
    }

    /**
     * Test the property 'dateValidity'
     */
    @Test
    void dateValidityTest() {
        // TODO: test dateValidity
    }

    /**
     * Test the property 'tokenLimit'
     */
    @Test
    void tokenLimitTest() {
        // TODO: test tokenLimit
    }

    /**
     * Test the property 'floatingTokenLimit'
     */
    @Test
    void floatingTokenLimitTest() {
        // TODO: test floatingTokenLimit
    }

    /**
     * Test the property 'isTemporary'
     */
    @Test
    void isTemporaryTest() {
        // TODO: test isTemporary
    }

    /**
     * Test the property 'isSoftwareVersionValid'
     */
    @Test
    void isSoftwareVersionValidTest() {
        // TODO: test isSoftwareVersionValid
    }

    /**
     * Test the property 'softwareReleaseLimitation'
     */
    @Test
    void softwareReleaseLimitationTest() {
        // TODO: test softwareReleaseLimitation
    }

    /**
     * Test the property 'isNewerSoftwareShipmentAvailable'
     */
    @Test
    void isNewerSoftwareShipmentAvailableTest() {
        // TODO: test isNewerSoftwareShipmentAvailable
    }

    /**
     * Test the property 'latestSoftwareShipment'
     */
    @Test
    void latestSoftwareShipmentTest() {
        // TODO: test latestSoftwareShipment
    }

    /**
     * Test the property 'sessionPeriod'
     */
    @Test
    void sessionPeriodTest() {
        // TODO: test sessionPeriod
    }

    /**
     * Test the property 'heartbeatPeriod'
     */
    @Test
    void heartbeatPeriodTest() {
        // TODO: test heartbeatPeriod
    }

    /**
     * Test the property 'freeride'
     */
    @Test
    void freerideTest() {
        // TODO: test freeride
    }

    /**
     * Test the property 'enforceSoftwareVersionUpgrade'
     */
    @Test
    void enforceSoftwareVersionUpgradeTest() {
        // TODO: test enforceSoftwareVersionUpgrade
    }

    /**
     * Test the property 'features'
     */
    @Test
    void featuresTest() {
        // TODO: test features
    }

    /**
     * Test the property 'limitations'
     */
    @Test
    void limitationsTest() {
        // TODO: test limitations
    }

    /**
     * Test the property 'variables'
     */
    @Test
    void variablesTest() {
        // TODO: test variables
    }

    /**
     * Test the property 'constrainedVariables'
     */
    @Test
    void constrainedVariablesTest() {
        // TODO: test constrainedVariables
    }

    /**
     * Test the property 'licenseUsers'
     */
    @Test
    void licenseUsersTest() {
        // TODO: test licenseUsers
    }

    /**
     * Test the property 'createdDateUtc'
     */
    @Test
    void createdDateUtcTest() {
        // TODO: test createdDateUtc
    }

    /**
     * Test the property 'licenseType'
     */
    @Test
    void licenseTypeTest() {
        // TODO: test licenseType
    }

}
